Repository OCA/field-service, pull requests merged in 2018-12, with the labels that each got.

#34 [ADD]12586: fsm_gantt module has been added to enhance fsm order vs person timeline view
  fieldservice/__manifest__.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person.py
  fieldservice/static/src/js/fsm_gantt.js
  fieldservice/static/src/js/fsm_gantt_person_filter.js
  fieldservice/static/src/less/fsm_gantt_person_filter.less
  fieldservice/static/src/xml/fsm_gantt_person_filter.xml
  fieldservice/views/fsm_order.xml
Labels: enhancement

#48 [FIX] config and menu
  fieldservice/models/res_config_settings.py
  fieldservice/views/menu.xml
  fieldservice/views/res_config_settings.xml
Labels: bug

#52 [FIX] Missing dependency
  fieldservice/__manifest__.py
Labels: bug

#50 [11.0][ADD] fieldservice_agreement module
  fieldservice_agreement/__init__.py
  fieldservice_agreement/__manifest__.py
  fieldservice_agreement/models/__init__.py
  fieldservice_agreement/models/agreement.py
  fieldservice_agreement/models/fsm_order.py
  fieldservice_agreement/readme/CONFIGURE.rst
  fieldservice_agreement/readme/CONTRIBUTORS.rst
  fieldservice_agreement/readme/CREDITS.rst
  fieldservice_agreement/readme/DESCRIPTION.rst
  fieldservice_agreement/readme/ROADMAP.rst
  fieldservice_agreement/readme/USAGE.rst
  fieldservice_agreement/static/description/icon.png
  fieldservice_agreement/views/agreement_view.xml
  fieldservice_agreement/views/fsm_order_view.xml
  oca_dependencies.txt
Labels: approved, needs review

#59 [IMP]12573: make custom color for fsm stage will reflect to geoengine mapping
  fieldservice/data/fsm_stage.xml
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_stage.py
  fieldservice/readme/CONFIGURE.rst
  fieldservice/static/src/js/fsm_gantt.js
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_stage.xml
Labels: needs review
