Repository OCA/field-service, pull requests merged in 2019-11, with the labels that each got.

#376 [IMP] fieldservice: Add Owned Locations to Partner
  fieldservice/models/res_partner.py
  fieldservice/views/res_partner.xml
Labels: approved, enhancement, needs review

#385 [FIX] fieldservice_project: CSS download failure
  fieldservice_project/__manifest__.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/project_views.xml
Labels: approved, bug, needs review

#395 [FIX] fieldservice_account: Error FSM Account
  fieldservice_account/wizard/fsm_wizard.py
Labels: approved, bug, needs review

#394 [FIX] fieldservie_stock: Convert Error FSM Stock
  fieldservice_stock/models/fsm_wizard.py
Labels: approved, bug, needs review

#367 [FIX] Travis and Runbot errors
  .travis.yml
  fieldservice/demo/fsm_demo.xml
  fieldservice/demo/fsm_equipment.xml
  fieldservice/demo/fsm_location.xml
  fieldservice/demo/fsm_person.xml
  fieldservice/models/res_partner.py
  fieldservice/tests/test_fsm_location.py
  fieldservice/tests/test_fsm_order.py
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/demo/fsm_location.xml
  fieldservice_account/init_hook.py
  fieldservice_account/models/fsm_location.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/report/fsm_order_report_template.xml
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/views/fsm_order.xml
  fieldservice_agreement/__manifest__.py
  fieldservice_agreement/models/agreement.py
  fieldservice_agreement/models/fsm_person.py
  fieldservice_agreement/tests/test_fsm_agreement.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_delivery/__manifest__.py
  fieldservice_geoengine/__manifest__.py
  fieldservice_isp_flow/__manifest__.py
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/models/fsm_equipment.py
  fieldservice_partner_multi_relation/__manifest__.py
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_repair/__manifest__.py
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/security/ir.model.access.csv
  fieldservice_skill/__manifest__.py
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/readme/DESCRIPTION.rst
  fieldservice_stock/__manifest__.py
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/stock.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_move_line.py
  fieldservice_stock/models/stock_picking.py
  fieldservice_stock/models/stock_request.py
  fieldservice_stock/models/stock_rule.py
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock_account/__manifest__.py
  fieldservice_stock_account_analytic/__manifest__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle_stock/__manifest__.py
Labels: approved, bug, needs review

#326 [ADD] fsm_location_builder
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_location_builder/README.rst
  fieldservice_location_builder/__init__.py
  fieldservice_location_builder/__manifest__.py
  fieldservice_location_builder/models/__init__.py
  fieldservice_location_builder/models/fsm_location_level.py
  fieldservice_location_builder/readme/CONTRIBUTORS.rst
  fieldservice_location_builder/readme/DESCRIPTION.rst
  fieldservice_location_builder/readme/ROADMAP.rst
  fieldservice_location_builder/readme/USAGE.rst
  fieldservice_location_builder/static/description/icon.png
  fieldservice_location_builder/static/description/index.html
  fieldservice_location_builder/views/fsm_location_level.xml
  fieldservice_location_builder/wizard/__init__.py
  fieldservice_location_builder/wizard/fsm_location_builder_wizard.py
  fieldservice_location_builder/wizard/fsm_location_builder_wizard.xml
Labels: approved, enhancement, needs review

#397 [12.0][IMP] fieldservice: Add Google Map
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
Labels: approved, enhancement, needs review

#400 [FIX] fieldservice_stock_account_analytic: Positional Arguments
  fieldservice_stock_account_analytic/models/fsm_order.py
Labels: approved, bug, needs review

#407 [IMP] fieldservice_recurring: Add team_id field in Recurring FS Orders
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_recurring.xml
Labels: approved, enhancement, needs review

#398 [12.0][ADD] fieldservice_google_map
  fieldservice_google_map/README.rst
  fieldservice_google_map/__init__.py
  fieldservice_google_map/__manifest__.py
  fieldservice_google_map/models/__init__.py
  fieldservice_google_map/models/fsm_location.py
  fieldservice_google_map/models/fsm_order.py
  fieldservice_google_map/readme/CONFIGURE.rst
  fieldservice_google_map/readme/CONTRIBUTORS.rst
  fieldservice_google_map/readme/CREDITS.rst
  fieldservice_google_map/readme/DESCRIPTION.rst
  fieldservice_google_map/readme/INSTALL.rst
  fieldservice_google_map/readme/USAGE.rst
  fieldservice_google_map/static/description/icon.png
  fieldservice_google_map/static/description/index.html
  fieldservice_google_map/views/fsm_location.xml
  fieldservice_google_map/views/fsm_order.xml
Labels: enhancement, needs review

#404 [FIX] fieldservice_account: Extend FSM Account Wizard
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/wizard/fsm_wizard.py
Labels: approved, bug, needs review

#409 [FIX] fieldservice_stock_account_analytic: AttributeError: 'account.i…
  fieldservice_stock_account_analytic/models/fsm_order.py
Labels: approved, bug, needs review

#410 [FIX] fieldservice_isp_flow: Remove Duplicate Method + Return Super
  fieldservice_isp_flow/models/fsm_order.py
Labels: approved, bug

#412 [FIX] fieldservice_isp_flow: ETA Missing on Form
  fieldservice_isp_flow/views/fsm_order.xml
Labels: approved, bug, needs review
