Repository OCA/field-service, pull requests merged in 2019-12, with the labels that each got.

#417 [FIX] fieldservice_stock_account
  fieldservice_stock_account/models/fsm_order.py
Labels: approved, bug

#420 [FIX] fieldservice_recurring: test
  fieldservice_recurring/tests/test_fsm_recurring.py
Labels: bug

#419 [FIX] fieldservice
  fieldservice/views/res_partner.xml
Labels: approved, bug, needs review

#427 [IMP] fieldservice_isp_account: Search Company ID
  fieldservice_isp_account/models/fsm_order.py
Labels: approved

#422 [FIX] fieldservice_sale_recurring
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: approved, bug, needs review

#421 [IMP] fieldservice: FSM Template
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_template.py
  fieldservice/tests/__init__.py
  fieldservice/tests/test_fsm_order.py
  fieldservice/tests/test_fsm_order_template_onchange.py
  fieldservice/views/fsm_template.xml
Labels: approved, enhancement, needs review

#428 [FIX] fieldservice_analytic_account: Analytic Account Company Dependant
  fieldservice_account_analytic/models/fsm_location.py
Labels: approved, bug, needs review

#429 [FIX] fieldservice_stock: Multiple back-orders if multiple moves
  fieldservice_stock/models/stock_move.py
Labels: approved, bug, needs review

#426 [FIX] fieldservice: Multi Company Stages & Teams
  fieldservice/models/fsm_order.py
Labels: approved, bug, needs review

#434 [FIX] fieldservice_isp_account: Show the header at the top
  fieldservice_isp_account/views/fsm_order.xml
Labels: approved, bug, needs review

#433 [FIX] fieldservice_account: Show FSM smart button on vendor bills
  fieldservice_account/models/account_invoice.py
Labels: approved, bug, needs review

#440 [12.0][IMP] fieldservice: Remove route
  fieldservice/__manifest__.py
  fieldservice/data/ir_sequence.xml
  fieldservice/models/__init__.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_route.py
  fieldservice/security/ir.model.access.csv
  fieldservice/security/ir_rule.xml
  fieldservice/views/fsm_route.xml
  fieldservice/views/menu.xml
  fieldservice_account_analytic/__manifest__.py
  fieldservice_account_analytic/views/fsm_route.xml
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_route.py
  fieldservice_vehicle/views/fsm_route.xml
Labels: approved, enhancement, needs review

#431 [12.0][IMP] fieldservice_stock
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/views/fsm_order.xml
Labels: approved, enhancement, needs review, ready to merge

#441 [IMP] fieldservice: Add team in template
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_template.py
  fieldservice/tests/test_fsm_order_template_onchange.py
  fieldservice/views/fsm_template.xml
Labels: approved, enhancement, needs review

#408 [ADD][12.0] fieldservice_google_marker_icon_picker
  fieldservice_google_marker_icon_picker/README.rst
  fieldservice_google_marker_icon_picker/__init__.py
  fieldservice_google_marker_icon_picker/__manifest__.py
  fieldservice_google_marker_icon_picker/models/__init__.py
  fieldservice_google_marker_icon_picker/models/fsm_stage.py
  fieldservice_google_marker_icon_picker/readme/CONFIGURE.rst
  fieldservice_google_marker_icon_picker/readme/CONTRIBUTORS.rst
  fieldservice_google_marker_icon_picker/readme/CREDITS.rst
  fieldservice_google_marker_icon_picker/readme/DESCRIPTION.rst
  fieldservice_google_marker_icon_picker/readme/INSTALL.rst
  fieldservice_google_marker_icon_picker/readme/USAGE.rst
  fieldservice_google_marker_icon_picker/static/description/icon.png
  fieldservice_google_marker_icon_picker/static/description/index.html
  fieldservice_google_marker_icon_picker/views/fsm_stage.xml
Labels: approved, enhancement, needs review, ready to merge

#446 [IMP] fieldservice_vehicle_stock
  fieldservice_vehicle_stock/data/fsm_stock_data.xml
Labels: approved, enhancement, needs review, ready to merge

#432 [12.0] [ADD] fieldservice_route
  fieldservice_route/README.rst
  fieldservice_route/__init__.py
  fieldservice_route/__manifest__.py
  fieldservice_route/data/fsm_route_day_data.xml
  fieldservice_route/data/fsm_stage_data.xml
  fieldservice_route/data/ir_sequence.xml
  fieldservice_route/models/__init__.py
  fieldservice_route/models/fsm_location.py
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route.py
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/models/fsm_stage.py
  fieldservice_route/readme/CONFIGURE.rst
  fieldservice_route/readme/CONTRIBUTORS.rst
  fieldservice_route/readme/CREDITS.rst
  fieldservice_route/readme/DESCRIPTION.rst
  fieldservice_route/readme/USAGE.rst
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/static/description/icon.png
  fieldservice_route/static/description/index.html
  fieldservice_route/tests/__init__.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_location.xml
  fieldservice_route/views/fsm_order.xml
  fieldservice_route/views/fsm_route.xml
  fieldservice_route/views/fsm_route_day.xml
  fieldservice_route/views/fsm_route_dayroute.xml
  fieldservice_route/views/menu.xml
Labels: approved, enhancement, needs review, ready to merge

#444 [IMP] fieldservice_sale_stock
  fieldservice_sale_stock/models/sale_order.py
Labels: approved, enhancement, needs review

#437 [12.0][ADD] fieldservice_route_vehicle
  fieldservice_route_vehicle/README.rst
  fieldservice_route_vehicle/__init__.py
  fieldservice_route_vehicle/__manifest__.py
  fieldservice_route_vehicle/models/__init__.py
  fieldservice_route_vehicle/models/fsm_route.py
  fieldservice_route_vehicle/models/fsm_route_dayroute.py
  fieldservice_route_vehicle/readme/CONFIGURE.rst
  fieldservice_route_vehicle/readme/CONTRIBUTORS.rst
  fieldservice_route_vehicle/readme/CREDITS.rst
  fieldservice_route_vehicle/readme/DESCRIPTION.rst
  fieldservice_route_vehicle/readme/ROADMAP.rst
  fieldservice_route_vehicle/readme/USAGE.rst
  fieldservice_route_vehicle/static/description/icon.png
  fieldservice_route_vehicle/static/description/index.html
  fieldservice_route_vehicle/views/fsm_route.xml
  fieldservice_route_vehicle/views/fsm_route_dayroute.xml
Labels: approved, enhancement, needs review, ready to merge

#458 [IMP] fieldservice_route_vehicle
  fieldservice_route_vehicle/views/fsm_route_dayroute.xml
Labels: approved, enhancement, needs review

#456 [FIX] fieldservice_sale_recurring: Product view
  fieldservice_sale_recurring/views/product_template.xml
Labels: approved, bug
