Repository OCA/field-service, pull requests merged in 2019-04, with the labels that each got.

#165 [IMP] multi-company support
  fieldservice/__manifest__.py
  fieldservice/models/fsm_branch.py
  fieldservice/models/fsm_district.py
  fieldservice/models/fsm_equipment.py
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person.py
  fieldservice/models/fsm_region.py
  fieldservice/models/fsm_stage.py
  fieldservice/models/fsm_team.py
  fieldservice/models/fsm_territory.py
  fieldservice/security/company_security.xml
  fieldservice/views/fsm_branch.xml
  fieldservice/views/fsm_district.xml
  fieldservice/views/fsm_equipment.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/fsm_region.xml
  fieldservice/views/fsm_stage.xml
  fieldservice/views/fsm_team.xml
  fieldservice/views/fsm_territory.xml
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/security/vehicle_security.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
Labels: approved, needs review

#169 [MIG][12.0] fieldservice_distribution
  fieldservice_distribution/README.rst
  fieldservice_distribution/__init__.py
  fieldservice_distribution/__manifest__.py
  fieldservice_distribution/models/__init__.py
  fieldservice_distribution/models/fsm_location.py
  fieldservice_distribution/readme/CONTRIBUTORS.rst
  fieldservice_distribution/readme/CREDITS.rst
  fieldservice_distribution/readme/DESCRIPTION.rst
  fieldservice_distribution/readme/ROADMAP.rst
  fieldservice_distribution/readme/USAGE.rst
  fieldservice_distribution/static/description/icon.png
  fieldservice_distribution/static/description/index.html
  fieldservice_distribution/views/fsm_location.xml
Labels: approved

#167 [MIG][12.0] fieldservice_sale
  fieldservice_sale/README.rst
  fieldservice_sale/__init__.py
  fieldservice_sale/__manifest__.py
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_location.py
  fieldservice_sale/readme/CONFIGURE.rst
  fieldservice_sale/readme/CONTRIBUTORS.rst
  fieldservice_sale/readme/CREDITS.rst
  fieldservice_sale/readme/DESCRIPTION.rst
  fieldservice_sale/readme/INSTALL.rst
  fieldservice_sale/readme/ROADMAP.rst
  fieldservice_sale/readme/USAGE.rst
  fieldservice_sale/static/description/icon.png
  fieldservice_sale/static/description/index.html
  fieldservice_sale/views/fsm_location.xml
Labels: approved, needs review

#168 [MIG][12.0] fieldservice_vehicle
  fieldservice_vehicle/README.rst
  fieldservice_vehicle/__init__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_route.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/readme/CONFIGURE.rst
  fieldservice_vehicle/readme/CONTRIBUTORS.rst
  fieldservice_vehicle/readme/CREDITS.rst
  fieldservice_vehicle/readme/DESCRIPTION.rst
  fieldservice_vehicle/readme/INSTALL.rst
  fieldservice_vehicle/readme/ROADMAP.rst
  fieldservice_vehicle/readme/USAGE.rst
  fieldservice_vehicle/security/ir.model.access.csv
  fieldservice_vehicle/security/res_groups.xml
  fieldservice_vehicle/static/description/icon.png
  fieldservice_vehicle/static/description/index.html
  fieldservice_vehicle/views/fsm_route.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
Labels: approved, needs review

#172 [MIG][12.0] fieldservice_skill
  fieldservice_skill/README.rst
  fieldservice_skill/__init__.py
  fieldservice_skill/__manifest__.py
  fieldservice_skill/models/__init__.py
  fieldservice_skill/models/fsm_category.py
  fieldservice_skill/models/fsm_order.py
  fieldservice_skill/models/fsm_person.py
  fieldservice_skill/models/fsm_person_skill.py
  fieldservice_skill/models/fsm_template.py
  fieldservice_skill/readme/CONFIGURE.rst
  fieldservice_skill/readme/CONTRIBUTORS.rst
  fieldservice_skill/readme/CREDITS.rst
  fieldservice_skill/readme/DESCRIPTION.rst
  fieldservice_skill/readme/INSTALL.rst
  fieldservice_skill/readme/ROADMAP.rst
  fieldservice_skill/readme/USAGE.rst
  fieldservice_skill/security/ir.model.access.csv
  fieldservice_skill/static/description/icon.png
  fieldservice_skill/static/description/index.html
  fieldservice_skill/views/fsm_category.xml
  fieldservice_skill/views/fsm_order.xml
  fieldservice_skill/views/fsm_person.xml
  fieldservice_skill/views/fsm_person_skill.xml
  fieldservice_skill/views/fsm_template.xml
  fieldservice_skill/views/hr_skill.xml
  oca_dependencies.txt
Labels: approved, needs review

#177 [12.0][IMP] fieldservice: Added contacts in dependency.
  fieldservice/__manifest__.py
  fieldservice/models/fsm_location.py
Labels: approved, needs review

#171 [MIG][12.0] fieldservice_agreement
  fieldservice_agreement/README.rst
  fieldservice_agreement/__init__.py
  fieldservice_agreement/__manifest__.py
  fieldservice_agreement/models/__init__.py
  fieldservice_agreement/models/agreement.py
  fieldservice_agreement/models/fsm_equipment.py
  fieldservice_agreement/models/fsm_order.py
  fieldservice_agreement/readme/CONFIGURE.rst
  fieldservice_agreement/readme/CONTRIBUTORS.rst
  fieldservice_agreement/readme/CREDITS.rst
  fieldservice_agreement/readme/DESCRIPTION.rst
  fieldservice_agreement/readme/ROADMAP.rst
  fieldservice_agreement/readme/USAGE.rst
  fieldservice_agreement/static/description/icon.png
  fieldservice_agreement/static/description/index.html
  fieldservice_agreement/views/agreement_view.xml
  fieldservice_agreement/views/fsm_equipment_view.xml
  fieldservice_agreement/views/fsm_order_view.xml
  oca_dependencies.txt
Labels: approved, needs review

#181 [FIX] fieldservice: Issue #180
  fieldservice/data/fsm_stage.xml
  fieldservice/security/res_groups.xml
Labels: approved, bug

#174 [MIG][12.0] fieldservice_stock
  fieldservice_stock/README.rst
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/data/fsm_stock_data.xml
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_equipment.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/product_template.py
  fieldservice_stock/models/stock.py
  fieldservice_stock/models/stock_production_lot.py
  fieldservice_stock/readme/CONFIGURE.rst
  fieldservice_stock/readme/CONTRIBUTORS.rst
  fieldservice_stock/readme/CREDITS.rst
  fieldservice_stock/readme/DESCRIPTION.rst
  fieldservice_stock/readme/INSTALL.rst
  fieldservice_stock/readme/ROADMAP.rst
  fieldservice_stock/readme/USAGE.rst
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock/static/description/icon.png
  fieldservice_stock/static/description/index.html
  fieldservice_stock/views/fsm_equipment.xml
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/product_template.xml
  fieldservice_stock/views/stock.xml
  fieldservice_stock/views/stock_production_lot.xml
  oca_dependencies.txt
Labels: needs review

#175 [MIG][12.0] fieldservice_delivery
  fieldservice_delivery/README.rst
  fieldservice_delivery/__init__.py
  fieldservice_delivery/__manifest__.py
  fieldservice_delivery/models/__init__.py
  fieldservice_delivery/models/fsm_order.py
  fieldservice_delivery/readme/CONFIGURE.rst
  fieldservice_delivery/readme/CONTRIBUTORS.rst
  fieldservice_delivery/readme/CREDITS.rst
  fieldservice_delivery/readme/DESCRIPTION.rst
  fieldservice_delivery/readme/INSTALL.rst
  fieldservice_delivery/readme/ROADMAP.rst
  fieldservice_delivery/readme/USAGE.rst
  fieldservice_delivery/static/description/icon.png
  fieldservice_delivery/static/description/index.html
  fieldservice_delivery/views/fsm_order.xml
Labels: approved, needs review

#176 [MIG][12.0] fieldservice_maintenance
  fieldservice_maintenance/README.rst
  fieldservice_maintenance/__init__.py
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/models/__init__.py
  fieldservice_maintenance/models/fsm_equipment.py
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_maintenance/models/maintenance.py
  fieldservice_maintenance/readme/CONFIGURE.rst
  fieldservice_maintenance/readme/CONTRIBUTORS.rst
  fieldservice_maintenance/readme/CREDITS.rst
  fieldservice_maintenance/readme/DESCRIPTION.rst
  fieldservice_maintenance/readme/INSTALL.rst
  fieldservice_maintenance/readme/ROADMAP.rst
  fieldservice_maintenance/readme/USAGE.rst
  fieldservice_maintenance/static/description/icon.png
  fieldservice_maintenance/static/description/index.html
  fieldservice_maintenance/views/fsm_equipment_view.xml
  fieldservice_maintenance/views/fsm_order_view.xml
  fieldservice_maintenance/views/maintenance_view.xml
Labels: approved, needs review

#173 [MIG][12.0] fieldservice_repair
  fieldservice_repair/README.rst
  fieldservice_repair/__init__.py
  fieldservice_repair/__manifest__.py
  fieldservice_repair/models/__init__.py
  fieldservice_repair/models/fsm_order.py
  fieldservice_repair/readme/CONFIGURE.rst
  fieldservice_repair/readme/CONTRIBUTORS.rst
  fieldservice_repair/readme/CREDITS.rst
  fieldservice_repair/readme/DESCRIPTION.rst
  fieldservice_repair/readme/INSTALL.rst
  fieldservice_repair/readme/ROADMAP.rst
  fieldservice_repair/readme/USAGE.rst
  fieldservice_repair/static/description/icon.png
  fieldservice_repair/static/description/index.html
  fieldservice_repair/views/fsm_order_view.xml
Labels: approved, needs review

#183 [12.0][IMP] fieldservice_stock:Improved code.
  fieldservice_stock/models/stock.py
Labels: bug

#185 [11.0][FIX] code issue
  fieldservice_maintenance/models/maintenance.py
  fieldservice_maintenance/readme/CONTRIBUTORS.rst
Labels: bug

#178 [MIG][12.0] fieldservice_vehicle_stock
  fieldservice_vehicle_stock/README.rst
  fieldservice_vehicle_stock/__init__.py
  fieldservice_vehicle_stock/__manifest__.py
  fieldservice_vehicle_stock/data/fsm_stock_data.xml
  fieldservice_vehicle_stock/models/__init__.py
  fieldservice_vehicle_stock/models/fsm_order.py
  fieldservice_vehicle_stock/models/fsm_vehicle.py
  fieldservice_vehicle_stock/readme/CONFIGURE.rst
  fieldservice_vehicle_stock/readme/CONTRIBUTORS.rst
  fieldservice_vehicle_stock/readme/CREDITS.rst
  fieldservice_vehicle_stock/readme/DESCRIPTION.rst
  fieldservice_vehicle_stock/readme/INSTALL.rst
  fieldservice_vehicle_stock/readme/ROADMAP.rst
  fieldservice_vehicle_stock/readme/USAGE.rst
  fieldservice_vehicle_stock/static/description/icon.png
  fieldservice_vehicle_stock/static/description/index.html
  fieldservice_vehicle_stock/views/fsm_vehicle.xml
Labels: approved, needs review

#170 [ADD][12.0] fieldservice_geoengine
  .travis.yml
  fieldservice_geoengine/__init__.py
  fieldservice_geoengine/__manifest__.py
  fieldservice_geoengine/models/__init__.py
  fieldservice_geoengine/models/fsm_location.py
  fieldservice_geoengine/models/fsm_order.py
  fieldservice_geoengine/views/fsm_order.xml
  fieldservice_geoengine/views/fsm_team.xml
  oca_dependencies.txt
  requirements.txt
Labels: approved, needs review

#191 [FIX]fieldservice migration issue related to less vs scss
  fieldservice/static/src/scss/fsm_gantt_person_filter.scss
  fieldservice/static/src/scss/team_dashboard.scss
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_team.xml
Labels: approved, needs review

#195 [FIX][11.0] minor code errors
  fieldservice/models/fsm_order.py
  fieldservice_substatus/models/fsm_order.py
  fieldservice_substatus/models/fsm_stage_status.py
Labels: approved, needs review

#192 [MIG][12.0] fieldservice_partner_multi_relation
  fieldservice_partner_multi_relation/README.rst
  fieldservice_partner_multi_relation/__init__.py
  fieldservice_partner_multi_relation/__manifest__.py
  fieldservice_partner_multi_relation/data/demo.xml
  fieldservice_partner_multi_relation/models/__init__.py
  fieldservice_partner_multi_relation/models/res_partner.py
  fieldservice_partner_multi_relation/models/res_partner_relation_type.py
  fieldservice_partner_multi_relation/readme/CONFIGURE.rst
  fieldservice_partner_multi_relation/readme/CONTRIBUTORS.rst
  fieldservice_partner_multi_relation/readme/CREDITS.rst
  fieldservice_partner_multi_relation/readme/DESCRIPTION.rst
  fieldservice_partner_multi_relation/readme/INSTALL.rst
  fieldservice_partner_multi_relation/readme/ROADMAP.rst
  fieldservice_partner_multi_relation/readme/USAGE.rst
  fieldservice_partner_multi_relation/static/description/icon.png
  fieldservice_partner_multi_relation/static/description/index.html
  oca_dependencies.txt
Labels: approved, needs review

#203 [FIX][12.0] fieldservice_maintenance
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_maintenance/models/maintenance.py
Labels: needs review

#193 [MIG][12.0] fieldservice_substatus
  fieldservice_substatus/README.rst
  fieldservice_substatus/__init__.py
  fieldservice_substatus/__manifest__.py
  fieldservice_substatus/data/fsm_stage_status.xml
  fieldservice_substatus/models/__init__.py
  fieldservice_substatus/models/fsm_order.py
  fieldservice_substatus/models/fsm_stage.py
  fieldservice_substatus/models/fsm_stage_status.py
  fieldservice_substatus/readme/CONFIGURE.rst
  fieldservice_substatus/readme/CONTRIBUTORS.rst
  fieldservice_substatus/readme/CREDITS.rst
  fieldservice_substatus/readme/DESCRIPTION.rst
  fieldservice_substatus/readme/INSTALL.rst
  fieldservice_substatus/readme/ROADMAP.rst
  fieldservice_substatus/readme/USAGE.rst
  fieldservice_substatus/security/ir.model.access.csv
  fieldservice_substatus/static/description/icon.png
  fieldservice_substatus/static/description/index.html
  fieldservice_substatus/views/fsm_order.xml
  fieldservice_substatus/views/fsm_stage.xml
  fieldservice_substatus/views/fsm_stage_status.xml
Labels: approved, needs review

#194 [MIG][12.0] fieldservice_account
  fieldservice_account/README.rst
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/data/time_products.xml
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_invoice.py
  fieldservice_account/models/analytic_account.py
  fieldservice_account/models/fsm_location.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/models/fsm_person.py
  fieldservice_account/readme/CONFIGURE.rst
  fieldservice_account/readme/CONTRIBUTORS.rst
  fieldservice_account/readme/CREDITS.rst
  fieldservice_account/readme/DESCRIPTION.rst
  fieldservice_account/readme/INSTALL.rst
  fieldservice_account/readme/USAGE.rst
  fieldservice_account/static/description/icon.png
  fieldservice_account/static/description/index.html
  fieldservice_account/views/account.xml
  fieldservice_account/views/account_invoice_view.xml
  fieldservice_account/views/fsm_location.xml
  fieldservice_account/views/fsm_order.xml
  fieldservice_account/views/fsm_person.xml
Labels: approved, needs review

#198 [FIX][12.0] fieldservice_geoengine
  fieldservice_geoengine/__manifest__.py
  fieldservice_geoengine/security/res_groups.xml
  fieldservice_geoengine/static/description/icon.png
  fieldservice_geoengine/views/fsm_order.xml
Labels: approved, bug, needs review
