Repository OCA/field-service, pull requests merged in 2019-07, with the labels that each got.

#248 [IMP] fieldservice_account: FSM_Account Bill to Contact/Location, Check Acc Stage Move, Timesheet Permissions
  fieldservice_account/__manifest__.py
  fieldservice_account/data/ir_rule.xml
  fieldservice_account/models/fsm_order.py
  fieldservice_account/security/ir.model.access.csv
  fieldservice_account/views/fsm_order.xml
  fieldservice_account/views/hr_timesheet.xml
Labels: approved, bug, needs review

#249 [IMP] fieldservice_sale: Add Sales Person
  fieldservice_sale/views/fsm_location.xml
Labels: enhancement, needs review

#250 [IMP] fieldservice: Group By Error, Stage Change Check, show Scheduled, My Orders
  fieldservice/models/fsm_order.py
  fieldservice/views/fsm_order.xml
Labels: approved, enhancement

#254 [IMP] Add Today and Future Order Filters
  fieldservice/views/fsm_order.xml
Labels: approved, enhancement, needs review

#253 [FIX] fieldservice_vehicle_stock: Allow worker to deliver from order
  fieldservice_vehicle_stock/__manifest__.py
  fieldservice_vehicle_stock/data/fsm_stock_data.xml
  fieldservice_vehicle_stock/models/__init__.py
  fieldservice_vehicle_stock/models/fsm_order.py
  fieldservice_vehicle_stock/models/stock_request.py
  fieldservice_vehicle_stock/security/ir.model.access.csv
  fieldservice_vehicle_stock/views/fsm_order.xml
  fieldservice_vehicle_stock/views/fsm_vehicle.xml
Labels: bug, needs review

#241 [IMP] fieldservice: Support multiple equipments on service request
  fieldservice/models/fsm_order.py
  fieldservice/views/fsm_order.xml
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_repair/models/fsm_order.py
Labels: enhancement, needs review

#259 [FIX] fieldservice: Documentation syntax
  fieldservice/readme/CONFIGURE.rst
  fieldservice/readme/INSTALL.rst
  fieldservice/readme/USAGE.rst
Labels: bug

#258 [FIX][12.0] fieldservice_geoengine
  fieldservice_geoengine/models/fsm_order.py
Labels: bug, needs review

#274 [FIX] Bugs bill_to view and add default value to allow automatic crea…
  fieldservice_account/models/fsm_order.py
  fieldservice_account/views/fsm_order.xml
Labels: approved, bug

#270 [FIX] fieldservice_maintenance: formatting
  fieldservice_maintenance/models/fsm_order.py
Labels: bug, needs review

#269 [FIX] fieldservice_repair: formatting
  fieldservice_repair/models/fsm_order.py
Labels: bug, needs review

#261 [IMP] fieldservice_account: Autopopulate description
  fieldservice_account/__manifest__.py
  fieldservice_account/migrations/12.0.2.0.0/pre-migration.py
  fieldservice_account/models/analytic_account.py
  fieldservice_account/views/fsm_order.xml
Labels: enhancement, needs review

#268 [FIX] fieldservice_delivery: Add carrier_id to procurement
  fieldservice_delivery/models/__init__.py
  fieldservice_delivery/models/fsm_order.py
  fieldservice_delivery/models/stock.py
  fieldservice_delivery/models/stock_request.py
Labels: bug, needs review

#260 [IMP] fieldservice: Context Fix Active ID, Show Start with EnRoute, add Calendar to Teams
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/res_config_settings.py
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_team.xml
Labels: enhancement, needs review

#276 [FIX] fieldservice_account: migration script
  fieldservice_account/migrations/12.0.2.0.0/post-migration.py
Labels: bug

#251 [12.0][MIG] fieldservice_recurring
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_recurring/README.rst
  fieldservice_recurring/__init__.py
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/data/ir_sequence.xml
  fieldservice_recurring/data/recurring_cron.xml
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_recurring_template.py
  fieldservice_recurring/readme/CONFIGURE.rst
  fieldservice_recurring/readme/CONTRIBUTORS.rst
  fieldservice_recurring/readme/CREDITS.rst
  fieldservice_recurring/readme/DESCRIPTION.rst
  fieldservice_recurring/readme/INSTALL.rst
  fieldservice_recurring/readme/ROADMAP.rst
  fieldservice_recurring/readme/USAGE.rst
  fieldservice_recurring/security/ir.model.access.csv
  fieldservice_recurring/security/recurring_security.xml
  fieldservice_recurring/security/res_groups.xml
  fieldservice_recurring/static/description/icon.png
  fieldservice_recurring/static/description/index.html
  fieldservice_recurring/tests/__init__.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_frequency.xml
  fieldservice_recurring/views/fsm_frequency_set.xml
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_recurring_template.xml
Labels: approved, migration, needs review

#273 [12.0][IMP] fieldservice_account, add test scripts
  fieldservice_account/tests/__init__.py
  fieldservice_account/tests/test_fsm_account.py
Labels: enhancement, needs review

#286 [FIX] fieldservice_geoengine: Add Calendar to Team Order View
  fieldservice_geoengine/views/fsm_team.xml
Labels: bug

#288 [IMP] fieldservice_stock: Remove description
  fieldservice_stock/models/fsm_equipment.py
Labels: enhancement

#287 [IMP] fieldservice_maintenance: Remove description
  fieldservice_maintenance/models/fsm_order.py
Labels: enhancement

#284 [IMP] fieldservice_recurring: Add button-box to recurring order form
  fieldservice_recurring/views/fsm_recurring.xml
Labels: approved

#294 [12.0][FIX] fieldservice Remove required attribute from view
  fieldservice/__manifest__.py
  fieldservice/views/fsm_location.xml
Labels: approved, bug, needs review

#293 [IMP] fieldservice: Move Location Down
  fieldservice/views/fsm_order.xml
Labels: approved, enhancement, needs review

#257 [12.0][IMP] fieldservice: Add tests
  fieldservice/__manifest__.py
  fieldservice/demo/fsm_demo.xml
  fieldservice/demo/fsm_equipment.xml
  fieldservice/demo/fsm_location.xml
  fieldservice/demo/fsm_person.xml
  fieldservice/tests/__init__.py
  fieldservice/tests/test_fsm_equipment.py
  fieldservice/tests/test_fsm_location.py
  fieldservice/tests/test_fsm_order.py
  fieldservice/tests/test_fsm_person.py
  fieldservice/tests/test_fsm_team.py
  fieldservice/tests/test_fsm_wizard.py
Labels: approved, enhancement, needs review

#296 [FIX] fieldservice_account: Wrong journals
  fieldservice_account/__manifest__.py
  fieldservice_account/models/fsm_order.py
Labels: approved, bug, needs review
