Repository OCA/field-service, pull requests merged in 2019-09, with the labels that each got.

#322 [ADD] fieldservice_project
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/readme/CONTRIBUTORS.rst
  fieldservice_project/readme/CREDITS.rst
  fieldservice_project/readme/DESCRIPTION.rst
  fieldservice_project/readme/ROADMAP.rst
  fieldservice_project/readme/USAGE.rst
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
Labels: approved, enhancement, needs review

#323 [IMP] fieldservice
  fieldservice/__manifest__.py
  fieldservice/models/fsm_order.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/security/res_groups.xml
  fieldservice/views/fsm_equipment.xml
  fieldservice/views/res_config_settings.xml
  fieldservice_substatus/__manifest__.py
  fieldservice_substatus/views/fsm_stage_status.xml
Labels: approved, enhancement

#324 [IMP] fieldservice: Add person_ids to search view
  fieldservice/views/fsm_order.xml
Labels: approved, enhancement, needs review

#325 [IMP] fieldservice: Add stage_id to Locations List view
  fieldservice/views/fsm_location.xml
Labels: approved, enhancement, needs review

#342 [IMP] fieldservice: Allow dispatcher to delete order in default stage
  fieldservice/__manifest__.py
  fieldservice/models/fsm_order.py
  fieldservice/security/ir.model.access.csv
Labels: approved, enhancement, needs review

#330 [IMP][12.0] fieldservice_recurring
  fieldservice_recurring/models/fsm_order.py
Labels: approved, enhancement, needs review

#345 [FIX] fieldservice_stock: Warehouse Not Readonly + Submit Stage Fix
  fieldservice_stock/models/fsm_order.py
Labels: approved, bug, needs review

#349 [12.0][IMP] fieldservice add name in order form.
  fieldservice/views/fsm_order.xml
Labels: approved, enhancement, needs review
