Repository OCA/field-service, pull requests merged in 2019-08, with the labels that each got.

#289 [IMP] FSM Improvements (Bugs: #265, #272, #263, #277, #266)
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person.py
  fieldservice_account/models/fsm_order.py
  fieldservice_purchase/models/fsm_person.py
Labels: approved, bug, needs review

#299 [FIX] fieldservice_geoengine
  fieldservice_geoengine/__manifest__.py
  fieldservice_geoengine/models/fsm_location.py
  fieldservice_geoengine/models/fsm_order.py
  fieldservice_geoengine/views/fsm_order.xml
  fieldservice_geoengine/views/fsm_team.xml
Labels: bug, needs review

#308 [FIX] fieldservice_vehicle_stock: AttributeError: 'bool' object has n…
  fieldservice_vehicle_stock/data/fsm_stock_data.xml
Labels: approved, bug, needs review

#238 [FIX] fieldservice_stock: Move Direction to Stock Request
  fieldservice_stock/__manifest__.py
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/stock.py
  fieldservice_stock/models/stock_request.py
  fieldservice_stock/models/stock_request_order.py
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/stock.xml
  fieldservice_stock/views/stock_request.xml
  fieldservice_stock/views/stock_request_order.xml
Labels: approved, bug, needs review

#300 [FIX] fieldservice: Location name + Multi-Company
  fieldservice/__manifest__.py
  fieldservice/models/fsm_category.py
  fieldservice/models/fsm_equipment.py
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_route.py
  fieldservice/models/fsm_tag.py
  fieldservice/models/fsm_team.py
  fieldservice/models/fsm_template.py
  fieldservice/report/fsm_order_report_template.xml
  fieldservice/security/ir_rule.xml
  fieldservice/views/fsm_category.xml
  fieldservice/views/fsm_equipment.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_route.xml
  fieldservice/views/fsm_tag.xml
  fieldservice/views/fsm_team.xml
  fieldservice/views/fsm_template.xml
Labels: bug, needs review

#315 [12.0][FIX]fieldservice_recurring - create all recurring orders at confirmation
  fieldservice_recurring/models/fsm_recurring.py
Labels: approved, bug, needs review

#305 [IMP] fieldservice_account
  fieldservice_account/models/fsm_order.py
Labels: approved, enhancement, needs review

#316 [IMP] fieldservice_stock
  fieldservice_stock/__manifest__.py
  fieldservice_stock/models/stock_request.py
Labels: approved, enhancement, needs review

#304 [12.0][ADD] fieldservice_stock_account
  fieldservice_stock_account/README.rst
  fieldservice_stock_account/__init__.py
  fieldservice_stock_account/__manifest__.py
  fieldservice_stock_account/models/__init__.py
  fieldservice_stock_account/models/fsm_order.py
  fieldservice_stock_account/readme/CONTRIBUTORS.rst
  fieldservice_stock_account/readme/CREDITS.rst
  fieldservice_stock_account/readme/DESCRIPTION.rst
  fieldservice_stock_account/readme/USAGE.rst
  fieldservice_stock_account/static/description/icon.png
  fieldservice_stock_account/static/description/index.html
  oca_dependencies.txt
Labels: approved, enhancement, needs review

#301 [ADD] fieldservice_stock_account_analytic
  fieldservice_stock_account_analytic/README.rst
  fieldservice_stock_account_analytic/__init__.py
  fieldservice_stock_account_analytic/__manifest__.py
  fieldservice_stock_account_analytic/models/__init__.py
  fieldservice_stock_account_analytic/models/fsm_order.py
  fieldservice_stock_account_analytic/models/stock_request.py
  fieldservice_stock_account_analytic/readme/CONTRIBUTORS.rst
  fieldservice_stock_account_analytic/readme/DESCRIPTION.rst
  fieldservice_stock_account_analytic/readme/ROADMAP.rst
  fieldservice_stock_account_analytic/readme/USAGE.rst
  fieldservice_stock_account_analytic/static/description/icon.png
  fieldservice_stock_account_analytic/static/description/index.html
  oca_dependencies.txt
Labels: approved, enhancement, needs review

#314 [12.0][FIX] fieldservice_recurring: Add missing fields to prepare
  fieldservice_recurring/models/fsm_recurring.py
Labels: approved, bug

#313 [12.0][IMP] fieldservice_recurring: Add button to navigate from Orders to Recurring Orders
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/readme/CONTRIBUTORS.rst
  fieldservice_recurring/views/fsm_order.xml
Labels: approved, enhancement

#303 [12.0][IMP] fieldservice_agreement, add unit test
  fieldservice_agreement/tests/__init__.py
  fieldservice_agreement/tests/test_fsm_agreement.py
Labels: approved, enhancement, needs review

#302 [12.0][IMP] fieldservice
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_stage.py
  fieldservice/models/res_config_settings.py
  fieldservice/security/ir_rule.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_stage.xml
  fieldservice/views/res_config_settings.xml
Labels: approved, enhancement, needs review
