Repository OCA/field-service, pull requests merged in 2019-02, with the labels that each got.

#132 [FIX] .travis.yml: Specific postgis version 2.3
  .travis.yml
Labels: needs review

#138 [FIX] Cost computation
  fieldservice_account/models/account_invoice.py
Labels: approved, bug

#139 [ADD] fieldservice_substatus
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_substatus/README.rst
  fieldservice_substatus/__init__.py
  fieldservice_substatus/__manifest__.py
  fieldservice_substatus/data/fsm_stage_status.xml
  fieldservice_substatus/models/__init__.py
  fieldservice_substatus/models/fsm_order.py
  fieldservice_substatus/models/fsm_stage.py
  fieldservice_substatus/models/fsm_stage_status.py
  fieldservice_substatus/readme/CONFIGURE.rst
  fieldservice_substatus/readme/CONTRIBUTORS.rst
  fieldservice_substatus/readme/CREDITS.rst
  fieldservice_substatus/readme/DESCRIPTION.rst
  fieldservice_substatus/readme/INSTALL.rst
  fieldservice_substatus/readme/ROADMAP.rst
  fieldservice_substatus/readme/USAGE.rst
  fieldservice_substatus/security/ir.model.access.csv
  fieldservice_substatus/static/description/icon.png
  fieldservice_substatus/static/description/index.html
  fieldservice_substatus/views/fsm_order.xml
  fieldservice_substatus/views/fsm_stage.xml
  fieldservice_substatus/views/fsm_stage_status.xml
Labels: enhancement
