Repository OCA/field-service, pull requests merged in 2019-05, with the labels that each got.

#206 [FIX] fieldservice_stock: Add missing Submit button
  fieldservice_stock/models/stock.py
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/stock.xml
  fieldservice_vehicle_stock/data/fsm_stock_data.xml
Labels: needs review

#207 [FIX] fieldservice: copy_notes on fsm.location
  fieldservice/models/fsm_order.py
  fieldservice_delivery/views/fsm_order.xml
  fieldservice_stock/__manifest__.py
  fieldservice_stock/models/stock.py
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/stock.xml
  fieldservice_substatus/data/fsm_stage.xml
  fieldservice_substatus/models/fsm_stage.py
Labels: bug

#179 [ADD][11.0] fieldservice_recurring
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_recurring/README.rst
  fieldservice_recurring/__init__.py
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/data/ir_sequence.xml
  fieldservice_recurring/data/recurring_cron.xml
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_recurring_template.py
  fieldservice_recurring/readme/CONFIGURE.rst
  fieldservice_recurring/readme/CONTRIBUTORS.rst
  fieldservice_recurring/readme/CREDITS.rst
  fieldservice_recurring/readme/DESCRIPTION.rst
  fieldservice_recurring/readme/INSTALL.rst
  fieldservice_recurring/readme/ROADMAP.rst
  fieldservice_recurring/readme/USAGE.rst
  fieldservice_recurring/security/ir.model.access.csv
  fieldservice_recurring/security/recurring_security.xml
  fieldservice_recurring/security/res_groups.xml
  fieldservice_recurring/static/description/icon.png
  fieldservice_recurring/views/fsm_frequency.xml
  fieldservice_recurring/views/fsm_frequency_set.xml
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_recurring_template.xml
Labels: needs review

#216 [FIX] Sort location by complete_name
  fieldservice/models/fsm_location.py
Labels: approved, needs review

#211 [IMP][12.0] fieldservice: Improved onchange method.
  fieldservice/models/fsm_order.py
Labels: approved, needs review

#217 [FIX] Show developer mode menu items to Manager group
  fieldservice/views/menu.xml
Labels: approved, enhancement, needs review

#214 [IMP] fieldservice: Add an option to auto-fill workers on location
  fieldservice/models/__init__.py
  fieldservice/models/fsm_location.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
Labels: approved, enhancement

#222 [12.0][FIX] Issue 187: Expected Singleton
  fieldservice/models/fsm_order.py
Labels: approved, bug, needs review

#223 [IMP]16335: fieldservice improvement to support preferred worker filer based on selected location #215
  fieldservice/models/fsm_person.py
Labels: approved, enhancement

#215 [IMP] fieldservice: Sort workers on location
  fieldservice/__manifest__.py
  fieldservice/models/__init__.py
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_location_person.py
  fieldservice/models/fsm_person.py
  fieldservice/models/res_config_settings.py
  fieldservice/security/ir.model.access.csv
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_location_person.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/menu.xml
Labels: approved, enhancement, needs review

#227 [FIX] fieldservice_account: access rights
  fieldservice_account/__manifest__.py
  fieldservice_account/security/ir.model.access.csv
Labels: approved, bug, needs review

#229 [FIX] fieldservice: FSM Location Chatter (PM #554)
  fieldservice/models/fsm_location.py
Labels: approved, bug, needs review

#225 [IMP] fieldservice_stock: Add direction to views
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/stock.py
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/stock.xml
Labels: approved, enhancement, needs review
