Repository OCA/field-service, pull requests merged in 2019-10, with the labels that each got.

#352 [IMP] FSM Repair Order Type
  fieldservice_repair/__manifest__.py
  fieldservice_repair/data/fsm_order_type.xml
  fieldservice_repair/models/fsm_order.py
Labels: approved, enhancement, needs review

#351 [IMP] FSM Maintenance Type
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/data/fsm_order_type.xml
  fieldservice_maintenance/models/fsm_order.py
Labels: approved, enhancement, needs review

#356 [IMP] README.md
  README.md
Labels: enhancement, needs review

#338 [12.0][fix] fieldservice_recurring - remove customer_id
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_recurring.xml
Labels: approved, enhancement, needs review

#360 [FIX] Missing variable for Weblate
  .travis.yml
Labels: bug

#336 [12][IMP] fieldservice_account add customer_id (moved from base module)
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/demo/fsm_location.xml
  fieldservice_account/models/__init__.py
  fieldservice_account/models/fsm_location.py
  fieldservice_account/models/fsm_location_person.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/report/fsm_order_report_template.xml
  fieldservice_account/views/fsm_location.xml
  fieldservice_account/views/fsm_order.xml
  fieldservice_account/views/fsm_person.xml
  fieldservice_account/views/fsm_route.xml
  fieldservice_account/wizard/__init__.py
  fieldservice_account/wizard/fsm_wizard.py
Labels: enhancement, needs review

#335 [12][IMP]fieldservice remove customer_id
  fieldservice/demo/fsm_location.xml
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_location_person.py
  fieldservice/models/fsm_order.py
  fieldservice/report/fsm_order_report_template.xml
  fieldservice/tests/test_fsm_location.py
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_location_person.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/fsm_route.xml
  fieldservice/wizard/fsm_wizard.py
Labels: enhancement, needs review

#361 [FIX] Repo description
  README.md
Labels: approved, bug, needs review

#347 [FIX] Datetime Error
  fieldservice_stock/models/stock_request.py
Labels: bug

#353 [IMP] Add FSM Order to Vendor Bill List View
  fieldservice_account/views/account_invoice_view.xml
Labels: approved, enhancement, needs review

#334 [12.0][ADD] fieldservice_default_flow
  fieldservice_default_flow/__init__.py
  fieldservice_default_flow/__manifest__.py
  fieldservice_default_flow/data/fsm_stage.xml
  fieldservice_default_flow/models/__init__.py
  fieldservice_default_flow/models/fsm_order.py
  fieldservice_default_flow/readme/CONFIGURE.rst
  fieldservice_default_flow/readme/CONTRIBUTORS.rst
  fieldservice_default_flow/readme/CREDITS.rst
  fieldservice_default_flow/readme/DESCRIPTION.rst
  fieldservice_default_flow/readme/ROADMAP.rst
  fieldservice_default_flow/readme/USAGE.rst
  fieldservice_default_flow/static/description/icon.png
  fieldservice_default_flow/static/description/index.html
  fieldservice_default_flow/views/fsm_order.xml
Labels: approved, enhancement, needs review

#333 [12.0]fieldservice - Remove most of the stages and its validation logic
  fieldservice/data/fsm_stage.xml
  fieldservice/models/fsm_order.py
  fieldservice/readme/CONTRIBUTORS.rst
  fieldservice/views/fsm_order.xml
Labels: enhancement, needs review

#357 [ADD] fieldservice_crm
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/readme/CONFIGURE.rst
  fieldservice_crm/readme/CONTRIBUTORS.rst
  fieldservice_crm/readme/CREDITS.rst
  fieldservice_crm/readme/DESCRIPTION.rst
  fieldservice_crm/readme/INSTALL.rst
  fieldservice_crm/readme/ROADMAP.rst
  fieldservice_crm/readme/USAGE.rst
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
Labels: approved, enhancement, needs review

#362 [REN] default_flow --> isp_flow
  README.md
  fieldservice/__manifest__.py
  fieldservice/data/fsm_stage.xml
  fieldservice/models/fsm_order_type.py
  fieldservice_account/report/fsm_order_report_template.xml
  fieldservice_account/views/fsm_route.xml
  fieldservice_agreement/views/agreement_view.xml
  fieldservice_agreement/views/fsm_order_view.xml
  fieldservice_default_flow/__init__.py
  fieldservice_default_flow/models/__init__.py
  fieldservice_isp_flow/README.rst
  fieldservice_isp_flow/__init__.py
  fieldservice_isp_flow/__manifest__.py
  fieldservice_isp_flow/data/fsm_stage.xml
  fieldservice_isp_flow/models/__init__.py
  fieldservice_isp_flow/models/fsm_order.py
  fieldservice_isp_flow/readme/CONFIGURE.rst
  fieldservice_isp_flow/readme/CONTRIBUTORS.rst
  fieldservice_isp_flow/readme/CREDITS.rst
  fieldservice_isp_flow/readme/DESCRIPTION.rst
  fieldservice_isp_flow/readme/ROADMAP.rst
  fieldservice_isp_flow/readme/USAGE.rst
  fieldservice_isp_flow/static/description/icon.png
  fieldservice_isp_flow/static/description/index.html
  fieldservice_isp_flow/views/fsm_order.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
  fieldservice_sale/readme/CONTRIBUTORS.rst
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/data/base_automation.xml
  fieldservice_stage_server_action/data/fsm_stage.xml
  fieldservice_stage_server_action/data/ir_server_action.xml
  fieldservice_stage_server_action/readme/CONFIGURE.rst
  fieldservice_stage_server_action/readme/CONTRIBUTORS.rst
  fieldservice_stage_server_action/readme/DESCRIPTION.rst
  fieldservice_stage_server_action/readme/USAGE.rst
  fieldservice_stock/models/stock_request.py
  fieldservice_substatus/data/fsm_stage.xml
  fieldservice_substatus/data/fsm_stage_status.xml
Labels: approved, enhancement, needs review

#368 [FIX] Unassigned Unscheduled Order Filters
  fieldservice/views/fsm_order.xml
  fieldservice_isp_flow/views/fsm_order.xml
Labels: approved, bug, needs review

#369 [FIX] Team kanban dashboard
  fieldservice/static/src/scss/team_dashboard.scss
Labels: approved, bug, needs review

#364 [12.0][RM] Unnecessary dependence on hr and fieldservice_stock module
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/models/fsm_equipment.py
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_maintenance/readme/CONTRIBUTORS.rst
  fieldservice_maintenance/views/fsm_equipment_view.xml
Labels: approved, bug, needs review

#375 [IMP] fieldservice_stock: SRO to SR Tree
  fieldservice_stock/models/stock_request.py
  fieldservice_stock/views/fsm_order.xml
Labels: approved, enhancement, needs review

#377 [FIX] fieldservice: Copy Notes Error
  fieldservice/models/fsm_order.py
Labels: approved, bug, needs review
