Repository OCA/field-service, pull requests merged in 2020-06, with the labels that each got.

#575 [IMP] fieldservice_isp_flow: ISP Stage Notifications
  fieldservice_isp_flow/models/fsm_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#568 [ADD] Field Service Change Management
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_change_management/README.rst
  fieldservice_change_management/__init__.py
  fieldservice_change_management/__manifest__.py
  fieldservice_change_management/data/change_log_impact.xml
  fieldservice_change_management/data/change_log_stage.xml
  fieldservice_change_management/data/change_log_type.xml
  fieldservice_change_management/data/ir_sequence.xml
  fieldservice_change_management/models/__init__.py
  fieldservice_change_management/models/change_log.py
  fieldservice_change_management/models/change_log_impact.py
  fieldservice_change_management/models/change_log_stage.py
  fieldservice_change_management/models/change_log_tags.py
  fieldservice_change_management/models/change_log_type.py
  fieldservice_change_management/models/fsm_location.py
  fieldservice_change_management/readme/CONFIGURE.rst
  fieldservice_change_management/readme/CONTRIBUTORS.rst
  fieldservice_change_management/readme/CREDITS.rst
  fieldservice_change_management/readme/DESCRIPTION.rst
  fieldservice_change_management/readme/INSTALL.rst
  fieldservice_change_management/readme/ROADMAP.rst
  fieldservice_change_management/readme/USAGE.rst
  fieldservice_change_management/report/change_log_reports.xml
  fieldservice_change_management/security/ir.model.access.csv
  fieldservice_change_management/security/security.xml
  fieldservice_change_management/static/description/icon.png
  fieldservice_change_management/static/description/icon.svg
  fieldservice_change_management/views/change_log.xml
  fieldservice_change_management/views/change_log_impact.xml
  fieldservice_change_management/views/change_log_stage.xml
  fieldservice_change_management/views/change_log_tags.xml
  fieldservice_change_management/views/change_log_type.xml
  fieldservice_change_management/views/fsm_location.xml
Labels: bot is merging ⏳, enhancement, needs review

#530 [IMP] fieldservice: Location Search Full Name + Parent Loc Dir + Stage Notifications
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#577 [IMP] fieldservice_change_management (Add default search context)
  fieldservice_change_management/views/fsm_location.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#559 [IMP] fieldservice_activity: Improved code
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/tests/test_fsm_activity.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#574 [IMP] fieldservice_substatus: Track Visibility + Notifications
  fieldservice_substatus/__manifest__.py
  fieldservice_substatus/data/mail_data.xml
  fieldservice_substatus/models/fsm_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#581 [12.0][IMP] fieldservice_recurring
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/views/fsm_recurring.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#550 [ADD] fieldservice_stage_validation
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_stage_validation/README.rst
  fieldservice_stage_validation/__init__.py
  fieldservice_stage_validation/__manifest__.py
  fieldservice_stage_validation/models/__init__.py
  fieldservice_stage_validation/models/fsm_equipment.py
  fieldservice_stage_validation/models/fsm_location.py
  fieldservice_stage_validation/models/fsm_order.py
  fieldservice_stage_validation/models/fsm_person.py
  fieldservice_stage_validation/models/fsm_stage.py
  fieldservice_stage_validation/readme/CONFIGURE.rst
  fieldservice_stage_validation/readme/CONTRIBUTORS.rst
  fieldservice_stage_validation/readme/DESCRIPTION.rst
  fieldservice_stage_validation/readme/ROADMAP.rst
  fieldservice_stage_validation/readme/USAGE.rst
  fieldservice_stage_validation/static/description/icon.png
  fieldservice_stage_validation/static/description/index.html
  fieldservice_stage_validation/views/fsm_stage.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge, work in progress
