Repository OCA/field-service, pull requests merged in 2020-08, with the labels that each got.

#600 [13.0] [MIG] fieldservice_vehicle
  fieldservice_vehicle/README.rst
  fieldservice_vehicle/__init__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/i18n/de.po
  fieldservice_vehicle/i18n/es.po
  fieldservice_vehicle/i18n/es_CL.po
  fieldservice_vehicle/i18n/fieldservice_vehicle.pot
  fieldservice_vehicle/i18n/pt_BR.po
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_order.py
  fieldservice_vehicle/models/fsm_person.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/readme/CONFIGURE.rst
  fieldservice_vehicle/readme/CONTRIBUTORS.rst
  fieldservice_vehicle/readme/CREDITS.rst
  fieldservice_vehicle/readme/DESCRIPTION.rst
  fieldservice_vehicle/readme/INSTALL.rst
  fieldservice_vehicle/readme/ROADMAP.rst
  fieldservice_vehicle/readme/USAGE.rst
  fieldservice_vehicle/security/ir.model.access.csv
  fieldservice_vehicle/security/res_groups.xml
  fieldservice_vehicle/static/description/icon.png
  fieldservice_vehicle/static/description/index.html
  fieldservice_vehicle/views/fsm_order.xml
  fieldservice_vehicle/views/fsm_person.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
Labels: approved, bot is merging ⏳, migration, needs review

#630 [12.0][IMP] fieldservice_isp_account:- Gave Access to portal user.
  fieldservice_isp_account/__manifest__.py
  fieldservice_isp_account/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#609 [FIX] fieldservice: fix timezone issue with Order filters
  fieldservice/views/fsm_order.xml
Labels: approved, bug, needs review, ready to merge

#616 [12.0][IMP] fieldservice_skill:- Gave Access to portal user.
  fieldservice_skill/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#617 [12.0][IMP] fieldservice_vehicle:- Gave Access to portal user.
  fieldservice_vehicle/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#614 [FIX] fieldservice_distribution (Smart Button Count)
  fieldservice_distribution/models/fsm_location.py
  fieldservice_distribution/views/fsm_location.xml
Labels: approved, bot is merging ⏳, bug, needs review
