Repository OCA/field-service, pull requests merged in 2020-05, with the labels that each got.

#566 [FIX] fieldservice_sale
  fieldservice_sale/__manifest__.py
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_branch.py
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/readme/ROADMAP.rst
  fieldservice_sale/views/fsm_branch.xml
Labels: approved, bot is merging ⏳, bug, needs review

#551 [IMP] fieldservice: 'Assigned To' calendar filter
  fieldservice/models/__init__.py
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice/security/ir.model.access.csv
  fieldservice/views/fsm_order.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#561 [FIX] fieldervice_account_payment
  fieldservice_account_payment/models/account_payment.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#563 [IMP] fieldservice_route_account: Show invoices
  fieldservice_route_account/__init__.py
  fieldservice_route_account/models/account_payment.py
  fieldservice_route_account/models/fsm_route_dayroute.py
  fieldservice_route_account/views/fsm_route_dayroute.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#570 [FIX] fieldservice_sale: Singleton error
  fieldservice_sale/models/sale_order.py
Labels: approved, bot is merging ⏳, bug, needs review

#565 [FIX] fieldservice_sale_stock: Set the FSM order on the procurement g…
  fieldservice_sale_stock/models/sale_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#572 [IMP] fieldservice: Check holidays
  fieldservice/__manifest__.py
  fieldservice/models/fsm_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#569 [FIX] fieldservice_route_account
  fieldservice_route_account/models/fsm_route_dayroute.py
Labels: approved, bot is merging ⏳, bug, needs review

#573 [FIX] fieldservice_account_payment
  fieldservice_account_payment/models/account_payment.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge
