Repository OCA/field-service, pull requests merged in 2020-11, with the labels that each got.

#666 [FIX] fieldservice: resource views
  fieldservice/__manifest__.py
  fieldservice/views/fsm_schedule.xml
  fieldservice/views/menu.xml
Labels: approved, bot is merging ⏳, bug

#663 [IMP] fieldservice: basic security
  fieldservice/security/ir.model.access.csv
  fieldservice/security/ir_rule.xml
  fieldservice/security/res_groups.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/menu.xml
  fieldservice/views/res_partner.xml
  fieldservice_route/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#608 [13.0] [MIG] Forward Port from 12.0
  fieldservice/__manifest__.py
  fieldservice/models/__init__.py
  fieldservice/models/fsm_equipment.py
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_order_type.py
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/models/res_partner.py
  fieldservice/security/ir.model.access.csv
  fieldservice/views/fsm_equipment.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_order_type.xml
  fieldservice/views/res_config_settings.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#645 [12.0][FIX] Improved compute_fsm_order_ids method
  fieldservice_account_payment/models/account_payment.py
  fieldservice_account_payment/models/fsm_order.py
Labels: approved, bot is merging ⏳, ready to merge

#601 [13.0] [MIG] fieldservice_fleet
  fieldservice_fleet/README.rst
  fieldservice_fleet/__init__.py
  fieldservice_fleet/__manifest__.py
  fieldservice_fleet/hooks.py
  fieldservice_fleet/i18n/es.po
  fieldservice_fleet/i18n/es_CL.po
  fieldservice_fleet/i18n/fieldservice_fleet.pot
  fieldservice_fleet/i18n/pt_BR.po
  fieldservice_fleet/models/__init__.py
  fieldservice_fleet/models/fleet_vehicle.py
  fieldservice_fleet/models/fsm_vehicle.py
  fieldservice_fleet/readme/CONFIGURE.rst
  fieldservice_fleet/readme/CONTRIBUTORS.rst
  fieldservice_fleet/readme/CREDITS.rst
  fieldservice_fleet/readme/DESCRIPTION.rst
  fieldservice_fleet/readme/INSTALL.rst
  fieldservice_fleet/readme/ROADMAP.rst
  fieldservice_fleet/readme/USAGE.rst
  fieldservice_fleet/static/description/icon.png
  fieldservice_fleet/static/description/index.html
  fieldservice_fleet/tests/__init__.py
  fieldservice_fleet/tests/test_fsm_fleet_wizard.py
  fieldservice_fleet/views/fleet_vehicle.xml
  fieldservice_fleet/views/fsm_vehicle.xml
  fieldservice_fleet/wizard/__init__.py
  fieldservice_fleet/wizard/fsm_fleet_wizard.py
  fieldservice_fleet/wizard/fsm_fleet_wizard.xml
  setup/fieldservice_fleet/odoo/addons/fieldservice_fleet
  setup/fieldservice_fleet/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#604 [13.0] [MIG] fieldservice_stage_server_action
  fieldservice_stage_server_action/README.rst
  fieldservice_stage_server_action/__init__.py
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/data/base_automation.xml
  fieldservice_stage_server_action/data/fsm_stage.xml
  fieldservice_stage_server_action/data/ir_server_action.xml
  fieldservice_stage_server_action/i18n/de.po
  fieldservice_stage_server_action/i18n/es.po
  fieldservice_stage_server_action/i18n/es_CL.po
  fieldservice_stage_server_action/i18n/fieldservice_stage_server_action.pot
  fieldservice_stage_server_action/i18n/pt_BR.po
  fieldservice_stage_server_action/models/__init__.py
  fieldservice_stage_server_action/models/fsm_stage.py
  fieldservice_stage_server_action/readme/CONFIGURE.rst
  fieldservice_stage_server_action/readme/CONTRIBUTORS.rst
  fieldservice_stage_server_action/readme/DESCRIPTION.rst
  fieldservice_stage_server_action/readme/USAGE.rst
  fieldservice_stage_server_action/static/description/icon.png
  fieldservice_stage_server_action/static/description/index.html
  fieldservice_stage_server_action/views/fsm_stage.xml
Labels: approved, bot is merging ⏳, migration, needs review

#603 [13.0] [MIG] fieldservice_stage_validation
  fieldservice_stage_validation/README.rst
  fieldservice_stage_validation/__init__.py
  fieldservice_stage_validation/__manifest__.py
  fieldservice_stage_validation/i18n/fieldservice_stage_validation.pot
  fieldservice_stage_validation/i18n/pt_PT.po
  fieldservice_stage_validation/models/__init__.py
  fieldservice_stage_validation/models/fsm_equipment.py
  fieldservice_stage_validation/models/fsm_location.py
  fieldservice_stage_validation/models/fsm_order.py
  fieldservice_stage_validation/models/fsm_person.py
  fieldservice_stage_validation/models/fsm_stage.py
  fieldservice_stage_validation/readme/CONFIGURE.rst
  fieldservice_stage_validation/readme/CONTRIBUTORS.rst
  fieldservice_stage_validation/readme/DESCRIPTION.rst
  fieldservice_stage_validation/readme/ROADMAP.rst
  fieldservice_stage_validation/readme/USAGE.rst
  fieldservice_stage_validation/static/description/icon.png
  fieldservice_stage_validation/static/description/index.html
  fieldservice_stage_validation/tests/__init__.py
  fieldservice_stage_validation/tests/test_fsm_stage_validation.py
  fieldservice_stage_validation/views/fsm_stage.xml
  setup/fieldservice_stage_validation/odoo/addons/fieldservice_stage_validation
  setup/fieldservice_stage_validation/setup.py
Labels: approved, bot is merging ⏳, migration, needs review
