Repository OCA/field-service, pull requests merged in 2020-04, with the labels that each got.

#537 [FIX] fieldservice_vehicle_stock
  fieldservice_vehicle_stock/models/stock_picking.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#539 [IMP] fieldservice_route
  fieldservice_route/views/fsm_route_dayroute.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#540 [FIX] fieldservice_route_stock
  fieldservice_route_stock/models/fsm_route_dayroute.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#543 [IMP] fieldservice_project: Default Project From Team on Order
  fieldservice_project/__manifest__.py
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/views/fsm_team.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#542 [IMP] fieldservice_isp_account: Default Set Project and Task
  fieldservice_isp_account/__manifest__.py
  fieldservice_isp_account/views/fsm_order.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#546 [FIX] fieldservice_sale: Access rights
  fieldservice_sale/__manifest__.py
  fieldservice_sale/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, bug, needs review

#544 [FIX] fieldservice_crm: Access rights
  fieldservice_crm/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, bug, needs review

#538 [FIX] fieldservice_route_vehicle
  fieldservice_route_vehicle/models/fsm_route.py
Labels: approved, bot is merging ⏳, bug, needs review

#545 [FIX] fieldservice_purchase: Access rights
  fieldservice_purchase/__manifest__.py
  fieldservice_purchase/security/ir.model.access.csv
Labels: bot is merging ⏳, bug, needs review

#526 [IMP] fieldservice_stock: Set the FSM location when creating equipment
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/stock_move.py
Labels: bot is merging ⏳, enhancement, needs review

#528 [FIX] fieldservice_maintenance: Split files and convert equipments
  fieldservice_maintenance/__init__.py
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/hooks.py
  fieldservice_maintenance/models/__init__.py
  fieldservice_maintenance/models/maintenance_equipment.py
  fieldservice_maintenance/models/maintenance_request.py
  fieldservice_maintenance/views/maintenance_equipment_view.xml
  fieldservice_maintenance/views/maintenance_request_view.xml
Labels: bot is merging ⏳, bug, needs review

#529 [IMP] fieldservice_stock: Add "Create FSM Equipment" option to Operation Types
  fieldservice/__manifest__.py
  fieldservice/models/fsm_equipment.py
  fieldservice/views/fsm_equipment.xml
  fieldservice_stock/__manifest__.py
  fieldservice_stock/migrations/12.0.2.0.0/post-migration.py
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_picking_type.py
  fieldservice_stock/readme/CONFIGURE.rst
  fieldservice_stock/views/product_template.xml
  fieldservice_stock/views/stock_picking_type.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#549 [IMP] fieldservice_stock: Request Workflow Adjustment
  fieldservice_stock/models/stock_request.py
  fieldservice_stock/models/stock_request_order.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#558 [FIX] fieldservice (Report Error)
  fieldservice/report/fsm_order_report_template.xml
Labels: approved, bot is merging ⏳, bug, needs review
