Repository OCA/field-service, pull requests merged in 2020-12, with the labels that each got.

#639 [12.0][IMP] fieldservice_stock: Improve Current Inventory Location
  fieldservice_stock/models/fsm_equipment.py
  fieldservice_stock/readme/CONTRIBUTORS.rst
  fieldservice_stock/tests/__init__.py
  fieldservice_stock/tests/test_fsm_equipment.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#681 [FIX] fieldservice_activity: Clean up activities when changing the template
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, bug

#679 [FIX] fieldservice_activity: Test case
  fieldservice_activity/tests/test_fsm_activity.py
Labels: approved, bug
