Repository OCA/field-service, pull requests merged in 2020-10, with the labels that each got.

#649 [IMP] fieldservice_isp_account: No Update Data .xml
  fieldservice_isp_account/data/time_products.xml
Labels: approved, bot is merging ⏳

#642 Added a Geo-Locate button to the FSM Location form
  fieldservice/models/fsm_location.py
  fieldservice/views/fsm_location.xml
Labels: approved, bot is merging ⏳, enhancement

#436 [IMP] fieldservice_sale_recurring: Add test
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/demo/frequency_demo.xml
  fieldservice_recurring/demo/frequency_set_demo.xml
  fieldservice_recurring/demo/recur_template_demo.xml
  fieldservice_sale_recurring/tests/__init__.py
  fieldservice_sale_recurring/tests/test_fsm_sale_recurring.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#661 [IMP] fieldservice_maintenance: Add Tests
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_maintenance/models/maintenance_request.py
  fieldservice_maintenance/readme/CONTRIBUTORS.rst
  fieldservice_maintenance/tests/__init__.py
  fieldservice_maintenance/tests/test_fsm_maintenance.py
Labels: approved, bot is merging ⏳, needs review

#606 [IMP] fieldservice: Order complete button permission
  fieldservice/views/fsm_order.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#607 [13.0] [MIG] fieldservice_activity
  fieldservice_activity/README.rst
  fieldservice_activity/__init__.py
  fieldservice_activity/__manifest__.py
  fieldservice_activity/i18n/es_AR.po
  fieldservice_activity/i18n/es_CL.po
  fieldservice_activity/i18n/fieldservice_activity.pot
  fieldservice_activity/i18n/pt_BR.po
  fieldservice_activity/i18n/pt_PT.po
  fieldservice_activity/models/__init__.py
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/models/fsm_template.py
  fieldservice_activity/readme/CONFIGURE.rst
  fieldservice_activity/readme/CONTRIBUTORS.rst
  fieldservice_activity/readme/CREDITS.rst
  fieldservice_activity/readme/DESCRIPTION.rst
  fieldservice_activity/readme/USAGE.rst
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/static/description/icon.png
  fieldservice_activity/static/description/index.html
  fieldservice_activity/tests/__init__.py
  fieldservice_activity/tests/test_fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge

#654 [13.0] [MIG] fieldservice_geoengine
  .travis.yml
  fieldservice_geoengine/README.rst
  fieldservice_geoengine/__init__.py
  fieldservice_geoengine/__manifest__.py
  fieldservice_geoengine/i18n/de.po
  fieldservice_geoengine/i18n/es.po
  fieldservice_geoengine/i18n/es_AR.po
  fieldservice_geoengine/i18n/es_CL.po
  fieldservice_geoengine/i18n/fieldservice_geoengine.pot
  fieldservice_geoengine/i18n/pt_BR.po
  fieldservice_geoengine/models/__init__.py
  fieldservice_geoengine/models/fsm_location.py
  fieldservice_geoengine/models/fsm_order.py
  fieldservice_geoengine/readme/CONFIGURE.rst
  fieldservice_geoengine/readme/CONTRIBUTORS.rst
  fieldservice_geoengine/readme/CREDITS.rst
  fieldservice_geoengine/readme/DESCRIPTION.rst
  fieldservice_geoengine/readme/INSTALL.rst
  fieldservice_geoengine/readme/ROADMAP.rst
  fieldservice_geoengine/readme/USAGE.rst
  fieldservice_geoengine/security/res_groups.xml
  fieldservice_geoengine/static/description/icon.png
  fieldservice_geoengine/static/description/index.html
  fieldservice_geoengine/views/fsm_order.xml
  fieldservice_geoengine/views/fsm_team.xml
  oca_dependencies.txt
  requirements.txt
  setup/fieldservice_geoengine/odoo/addons/fieldservice_geoengine
  setup/fieldservice_geoengine/setup.py
Labels: approved, bot is merging ⏳, migration, needs review

#602 [13.0] [MIG] fieldservice_skill
  fieldservice_skill/README.rst
  fieldservice_skill/__init__.py
  fieldservice_skill/__manifest__.py
  fieldservice_skill/i18n/de.po
  fieldservice_skill/i18n/es.po
  fieldservice_skill/i18n/es_CL.po
  fieldservice_skill/i18n/fieldservice_skill.pot
  fieldservice_skill/i18n/pt_BR.po
  fieldservice_skill/models/__init__.py
  fieldservice_skill/models/fsm_category.py
  fieldservice_skill/models/fsm_order.py
  fieldservice_skill/models/fsm_person.py
  fieldservice_skill/models/fsm_person_skill.py
  fieldservice_skill/models/fsm_template.py
  fieldservice_skill/models/hr_skill.py
  fieldservice_skill/readme/CONFIGURE.rst
  fieldservice_skill/readme/CONTRIBUTORS.rst
  fieldservice_skill/readme/CREDITS.rst
  fieldservice_skill/readme/DESCRIPTION.rst
  fieldservice_skill/readme/INSTALL.rst
  fieldservice_skill/readme/ROADMAP.rst
  fieldservice_skill/readme/USAGE.rst
  fieldservice_skill/security/ir.model.access.csv
  fieldservice_skill/static/description/icon.png
  fieldservice_skill/static/description/index.html
  fieldservice_skill/tests/__init__.py
  fieldservice_skill/tests/test_fsm_skill.py
  fieldservice_skill/views/fsm_category.xml
  fieldservice_skill/views/fsm_order.xml
  fieldservice_skill/views/fsm_person.xml
  fieldservice_skill/views/fsm_person_skill.xml
  fieldservice_skill/views/fsm_template.xml
  fieldservice_skill/views/hr_skill.xml
  setup/fieldservice_skill/odoo/addons/fieldservice_skill
  setup/fieldservice_skill/setup.py
Labels: approved, bot is merging ⏳, migration, needs review, ready to merge
