Repository OCA/field-service, pull requests merged in 2020-09, with the labels that each got.

#580 [12.0][FIX] fieldservice_maintenance
  fieldservice_maintenance/README.rst
  fieldservice_maintenance/data/fsm_order_type.xml
  fieldservice_maintenance/models/__init__.py
  fieldservice_maintenance/models/fsm_equipment.py
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_maintenance/models/fsm_order_type.py
  fieldservice_maintenance/models/maintenance_equipment.py
  fieldservice_maintenance/models/maintenance_request.py
  fieldservice_maintenance/readme/CONTRIBUTORS.rst
  fieldservice_maintenance/views/fsm_order_view.xml
Labels: approved, bug, needs review

#583 [12.0][FIX] fieldservice_repair
  fieldservice_repair/README.rst
  fieldservice_repair/data/fsm_order_type.xml
  fieldservice_repair/models/__init__.py
  fieldservice_repair/models/fsm_order.py
  fieldservice_repair/models/fsm_order_type.py
  fieldservice_repair/readme/CONTRIBUTORS.rst
  fieldservice_repair/views/fsm_order_view.xml
Labels: approved, bot is merging ⏳, bug, needs review

#636 [FIX] FSM Invoice Double Timesheet Entry
  fieldservice_isp_account/models/fsm_order.py
Labels: approved, bot is merging ⏳

#585 [12.0][ADD] fieldservice_mgmtsystem_nonconformity
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_mgmtsystem_nonconformity/README.rst
  fieldservice_mgmtsystem_nonconformity/__init__.py
  fieldservice_mgmtsystem_nonconformity/__manifest__.py
  fieldservice_mgmtsystem_nonconformity/i18n/pt_BR.po
  fieldservice_mgmtsystem_nonconformity/models/__init__.py
  fieldservice_mgmtsystem_nonconformity/models/fsm_order.py
  fieldservice_mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py
  fieldservice_mgmtsystem_nonconformity/readme/CONTRIBUTORS.rst
  fieldservice_mgmtsystem_nonconformity/readme/DESCRIPTION.rst
  fieldservice_mgmtsystem_nonconformity/readme/USAGE.rst
  fieldservice_mgmtsystem_nonconformity/static/description/icon.png
  fieldservice_mgmtsystem_nonconformity/static/description/index.html
  fieldservice_mgmtsystem_nonconformity/views/mgmtsystem_nonconformity.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#615 [IMP] fieldservice: Give Access to portal user
  fieldservice/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#620 [IMP] fieldservice_activity: Give access to portal user
  fieldservice_activity/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#621 [IMP] fieldservice_route: Give access to portal user
  fieldservice_route/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#623 [IMP] fieldservice_stock: Give access to portal user
  fieldservice_stock/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
