Repository OCA/field-service, pull requests merged in 2020-02, with the labels that each got.

#494 [DEL] Remove fsm_location_person.py From Fielservice Account Analytic
  fieldservice_account_analytic/models/__init__.py
  fieldservice_account_analytic/models/fsm_location_person.py
Labels: approved

#493 [FIX] fieldservice_stock: Don't error if some moves were deleted by previous logic
  fieldservice_stock/models/stock_move_line.py
Labels: approved, bug

#495 [FIX] fieldservice_vehicle_stock
  fieldservice_vehicle_stock/models/stock_picking.py
Labels: approved, bug, needs review

#498 [IMP] fieldservice_sale_stock
  fieldservice_sale_stock/models/sale_order.py
Labels: approved, enhancement, needs review

#501 [12.0] [FIX] Dependency correction of module fieldservice_vehicle_stock
  fieldservice_vehicle_stock/__manifest__.py
Labels: approved, bug, needs review, ready to merge

#500 [IMP] fieldservice_account: Add Groups (Smart Buttons and List view)
  fieldservice_account/views/account_invoice.xml
  fieldservice_account/views/fsm_order.xml
Labels: approved, enhancement, needs review, ready to merge

#479 [IMP] fieldservice_account_analytic: Filter Location/Contact
  fieldservice_account_analytic/__manifest__.py
  fieldservice_account_analytic/models/__init__.py
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_account_analytic/models/res_company.py
  fieldservice_account_analytic/models/res_config_settings.py
  fieldservice_account_analytic/views/res_config_settings.xml
Labels: approved, enhancement, ready to merge

#506 [FIX] fieldservice_route_vehicle: Don't error when computing default values
  fieldservice_route_vehicle/models/fsm_route_dayroute.py
Labels: approved, bug, needs review

#503 [12.0][IMP] fieldservice_google_marker_icon_picker: Added Choose stage color field
  fieldservice_google_marker_icon_picker/__manifest__.py
  fieldservice_google_marker_icon_picker/models/fsm_stage.py
  fieldservice_google_marker_icon_picker/views/fsm_stage.xml
  requirements.txt
Labels: approved, enhancement, needs review, ready to merge

#502 [12.0][IMP] fieldservice: Improved Color code functionality
  fieldservice/models/fsm_stage.py
Labels: approved, enhancement, needs review, ready to merge

#486 [IMP] fieldservice_sale: Add Tests
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/tests/__init__.py
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_order.py
Labels: needs review

#512 [FIX] fieldservice_sale
  fieldservice_sale/models/sale_order.py
Labels: approved, bug, needs review

#511 [12.0][IMP] fieldservice_stock
  fieldservice_stock/views/fsm_order.xml
Labels: approved, enhancement, needs review

#508 [MIG][13.0] base_territory
  base_territory/README.rst
  base_territory/__init__.py
  base_territory/__manifest__.py
  base_territory/demo/base_territory_demo.xml
  base_territory/models/__init__.py
  base_territory/models/res_branch.py
  base_territory/models/res_country.py
  base_territory/models/res_district.py
  base_territory/models/res_region.py
  base_territory/models/res_territory.py
  base_territory/readme/CONTRIBUTORS.rst
  base_territory/readme/CREDITS.rst
  base_territory/readme/DESCRIPTION.rst
  base_territory/readme/USAGE.rst
  base_territory/security/ir.model.access.csv
  base_territory/static/description/icon.png
  base_territory/static/description/index.html
  base_territory/views/menu.xml
  base_territory/views/res_branch.xml
  base_territory/views/res_country.xml
  base_territory/views/res_district.xml
  base_territory/views/res_region.xml
  base_territory/views/res_territory.xml
Labels: approved, migration, needs review

#510 [FIX] fieldservice_vehicle_stock: Expected singleton: stock.picking
  fieldservice_vehicle_stock/models/stock_picking.py
Labels: approved, bug, needs review, ready to merge

#507 [ADD] fieldservice_size
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_size/README.rst
  fieldservice_size/__init__.py
  fieldservice_size/__manifest__.py
  fieldservice_size/models/__init__.py
  fieldservice_size/models/fsm_location.py
  fieldservice_size/models/fsm_location_size.py
  fieldservice_size/models/fsm_order.py
  fieldservice_size/models/fsm_size.py
  fieldservice_size/readme/CONFIGURE.rst
  fieldservice_size/readme/CONTRIBUTORS.rst
  fieldservice_size/readme/DESCRIPTION.rst
  fieldservice_size/readme/ROADMAP.rst
  fieldservice_size/readme/USAGE.rst
  fieldservice_size/security/ir.model.access.csv
  fieldservice_size/tests/test_fsm_order.py
  fieldservice_size/views/fsm_location.xml
  fieldservice_size/views/fsm_order.xml
  fieldservice_size/views/fsm_size.xml
  fieldservice_size/views/menu.xml
Labels: approved, enhancement, needs review, ready to merge
