Repository OCA/field-service, pull requests merged in 2020-03, with the labels that each got.

#515 [FIX] fieldservice: False team from template
  fieldservice/models/fsm_order.py
Labels: approved, bug, needs review, ready to merge

#491 [IMP] fieldservice: Minor changes
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/views/fsm_order.xml
Labels: approved, enhancement, needs review, ready to merge

#496 [IMP] fieldservice_route_vehicle
  fieldservice_route_vehicle/models/fsm_route.py
  fieldservice_route_vehicle/models/fsm_route_dayroute.py
  fieldservice_route_vehicle/views/fsm_route.xml
Labels: approved, enhancement, needs review, ready to merge

#497 [IMP] fieldservice_route_stock
  fieldservice_route_stock/__manifest__.py
  fieldservice_route_stock/models/__init__.py
  fieldservice_route_stock/models/fsm_route.py
  fieldservice_route_stock/models/fsm_route_dayroute.py
  fieldservice_route_stock/views/fsm_route.xml
  fieldservice_route_stock/views/fsm_route_dayroute.xml
Labels: approved, enhancement, needs review, ready to merge

#522 [FIX] fieldservice: Keep type when changing template
  fieldservice/models/fsm_order.py
Labels: approved, bug, needs review

#499 [FIX] fieldservice_location_builder: Timezone Error + Dependency Error
  fieldservice_location_builder/__manifest__.py
  fieldservice_location_builder/wizard/fsm_location_builder_wizard.py
Labels: approved, bug, needs review, ready to merge

#527 [IMP] fieldservice: Show locations owned by children (contacts/addres…
  fieldservice/models/res_partner.py
Labels: approved, enhancement, needs review

#534 [IMP] fieldservice_vehicle
  fieldservice_vehicle/models/fsm_order.py
Labels: approved, enhancement, needs review

#531 [IMP] fieldservice_route
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_route_dayroute.xml
Labels: approved, enhancement, needs review

#536 [FIX] fieldservice_fleet: Travis errors
  fieldservice_fleet/readme/CONFIGURE.rst
Labels: approved, bug, needs review, ready to merge

#532 [IMP] fieldservice_route_stock
  fieldservice_route_stock/models/fsm_route.py
  fieldservice_route_stock/models/fsm_route_dayroute.py
  fieldservice_route_stock/views/fsm_route_dayroute.xml
Labels: approved, enhancement, needs review, ready to merge

#533 [IMP] fieldservice_route_vehicle
  fieldservice_route_vehicle/models/__init__.py
  fieldservice_route_vehicle/models/fsm_order.py
  fieldservice_route_vehicle/models/fsm_route.py
  fieldservice_route_vehicle/models/fsm_route_dayroute.py
Labels: approved, enhancement, needs review, ready to merge

#535 [FIX] fieldservice_size: Travis error
  fieldservice_size/models/fsm_size.py
Labels: approved, bug, needs review
