Repository OCA/field-service, pull requests merged in 2020-01, with the labels that each got.

#461 [FIX] Improved code.
  fieldservice_sale/models/sale_order.py
Labels: approved, bug

#460 [IMP] Add Activites Setting + Template Notebook
  fieldservice/models/res_config_settings.py
  fieldservice/views/fsm_template.xml
  fieldservice/views/res_config_settings.xml
Labels: approved, enhancement, needs review

#465 [FIX] fieldservice_sale
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
Labels: approved, bug, needs review

#459 [ADD] fieldservice_activity
  fieldservice_activity/README.rst
  fieldservice_activity/__init__.py
  fieldservice_activity/__manifest__.py
  fieldservice_activity/models/__init__.py
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/models/fsm_template.py
  fieldservice_activity/readme/CONFIGURE.rst
  fieldservice_activity/readme/CONTRIBUTORS.rst
  fieldservice_activity/readme/CREDITS.rst
  fieldservice_activity/readme/DESCRIPTION.rst
  fieldservice_activity/readme/USAGE.rst
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/static/description/icon.png
  fieldservice_activity/static/description/index.html
  fieldservice_activity/tests/__init__.py
  fieldservice_activity/tests/test_fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
Labels: approved, enhancement, needs review, ready to merge

#451 [12.0][ADD] fieldservice_route_stock
  fieldservice_route_stock/README.rst
  fieldservice_route_stock/__init__.py
  fieldservice_route_stock/__manifest__.py
  fieldservice_route_stock/models/__init__.py
  fieldservice_route_stock/models/fsm_route_dayroute.py
  fieldservice_route_stock/models/stock_inventory.py
  fieldservice_route_stock/readme/CONTRIBUTORS.rst
  fieldservice_route_stock/readme/CREDITS.rst
  fieldservice_route_stock/readme/DESCRIPTION.rst
  fieldservice_route_stock/readme/USAGE.rst
  fieldservice_route_stock/tests/__init__.py
  fieldservice_route_stock/tests/test_fieldservice_route_stock.py
  fieldservice_route_stock/views/fsm_route_dayroute.xml
Labels: approved, enhancement, needs review, ready to merge

#472 [IMP] fieldservice_account
  fieldservice_account/views/account_invoice.xml
  fieldservice_account/views/fsm_order.xml
Labels: approved, enhancement, needs review

#470 [IMP] fieldservice_sale_stock
  fieldservice_sale_stock/models/sale_order.py
Labels: approved, enhancement, needs review

#471 [IMP] fieldservice_vehicle
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_order.py
  fieldservice_vehicle/models/fsm_person.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/views/fsm_order.xml
  fieldservice_vehicle/views/fsm_person.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
Labels: approved, enhancement, needs review

#477 [IMP] fieldservice_account: FSO on vendor bills
  fieldservice_account/views/account_invoice.xml
Labels: approved, enhancement, needs review

#474 [IMP] fieldservice_account_analytic: Set Default Customer
  fieldservice_account_analytic/models/fsm_location.py
Labels: approved, enhancement, needs review

#455 [IMP] fieldservice_isp_account: m2m between fsm.order and invoice
  fieldservice_isp_account/models/fsm_order.py
Labels: approved, enhancement, needs review, ready to merge

#478 [FIX] fieldservice_sale
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
Labels: approved, bug, needs review
