Repository OCA/field-service, pull requests merged in 2020-07, with the labels that each got.

#582 [12.0] Add field internal_type in fsm.order.type
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_order_type.py
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_order_type.xml
Labels: approved, bot is merging ⏳, bug, enhancement, needs review, ready to merge

#596 [13.0] [IMP] fieldservice_recurring: black, isort, prettier
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/tests/test_fsm_recurring.py
Labels: bot is merging ⏳, migration, needs review

#599 [13.0] [MIG] fieldservice_crm
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/i18n/de.po
  fieldservice_crm/i18n/es_CL.po
  fieldservice_crm/i18n/fieldservice_crm.pot
  fieldservice_crm/i18n/pt_BR.po
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/readme/CONFIGURE.rst
  fieldservice_crm/readme/CONTRIBUTORS.rst
  fieldservice_crm/readme/CREDITS.rst
  fieldservice_crm/readme/DESCRIPTION.rst
  fieldservice_crm/readme/INSTALL.rst
  fieldservice_crm/readme/ROADMAP.rst
  fieldservice_crm/readme/USAGE.rst
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/static/description/index.html
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
Labels: approved, bot is merging ⏳, migration, needs review

#605 [IMP] fieldservice_stage_server_action: Remove dependency
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/readme/CONTRIBUTORS.rst
  fieldservice_stage_server_action/views/fsm_stage.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge
