Repository OCA/field-service, pull requests merged in 2021-12, with the labels that each got.

#858 [14.0] [IMP] fieldservice: toggle active FSMPerson
  fieldservice/models/fsm_person.py
  fieldservice/tests/test_fsm_person.py
  fieldservice/tests/test_fsm_wizard.py
  fieldservice/views/fsm_person.xml
  fieldservice/wizard/fsm_wizard.py
Labels: enhancement, needs fixing, approved, bot is merging ⏳

#790 [ADD] fieldservice_account - 2 smart buttons, one for invoices, one for bills
  fieldservice_account/models/fsm_order.py
  fieldservice_account/views/fsm_order.xml
Labels: enhancement, bot is merging ⏳

#857 [14.0] [MIG] fieldservice_size
  fieldservice_size/README.rst
  fieldservice_size/__init__.py
  fieldservice_size/__manifest__.py
  fieldservice_size/i18n/es.po
  fieldservice_size/i18n/fieldservice_size.pot
  fieldservice_size/i18n/it.po
  fieldservice_size/i18n/pt_BR.po
  fieldservice_size/models/__init__.py
  fieldservice_size/models/fsm_location.py
  fieldservice_size/models/fsm_location_size.py
  fieldservice_size/models/fsm_order.py
  fieldservice_size/models/fsm_size.py
  fieldservice_size/readme/CONFIGURE.rst
  fieldservice_size/readme/CONTRIBUTORS.rst
  fieldservice_size/readme/DESCRIPTION.rst
  fieldservice_size/readme/ROADMAP.rst
  fieldservice_size/readme/USAGE.rst
  fieldservice_size/security/ir.model.access.csv
  fieldservice_size/static/description/icon.png
  fieldservice_size/static/description/index.html
  fieldservice_size/tests/test_fsm_order.py
  fieldservice_size/views/fsm_location.xml
  fieldservice_size/views/fsm_order.xml
  fieldservice_size/views/fsm_size.xml
  fieldservice_size/views/menu.xml
  setup/fieldservice_size/odoo/addons/fieldservice_size
  setup/fieldservice_size/setup.py
Labels: migration, bot is merging ⏳

#845 [13.0][IMP] Migration Script : fieldservice_stock
  fieldservice_stock/migrations/13.0.1.0.0/post-migration.py
  fieldservice_stock/migrations/13.0.1.0.0/pre-migration.py
  fieldservice_stock/readme/CONTRIBUTORS.rst
  fieldservice_stock/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#851 [12.0][FIX] Removed forced overwrite of fsm.order's Scheduled Date End
  fieldservice/models/fsm_order.py
Labels: approved, bot is merging ⏳

#815 [12.0][FIX]Fixed _compute_request_late methods
  fieldservice/models/fsm_order.py
  fieldservice_recurring/models/fsm_order.py
Labels: bot is merging ⏳

#859 [14.0][MIG] fieldservice_recurring
  fieldservice_recurring/README.rst
  fieldservice_recurring/__init__.py
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/data/ir_sequence.xml
  fieldservice_recurring/data/recurring_cron.xml
  fieldservice_recurring/i18n/de.po
  fieldservice_recurring/i18n/es.po
  fieldservice_recurring/i18n/es_AR.po
  fieldservice_recurring/i18n/es_CL.po
  fieldservice_recurring/i18n/fieldservice_recurring.pot
  fieldservice_recurring/i18n/it.po
  fieldservice_recurring/i18n/pt_BR.po
  fieldservice_recurring/i18n/tr.po
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_recurring_template.py
  fieldservice_recurring/readme/CONFIGURE.rst
  fieldservice_recurring/readme/CONTRIBUTORS.rst
  fieldservice_recurring/readme/CREDITS.rst
  fieldservice_recurring/readme/DESCRIPTION.rst
  fieldservice_recurring/readme/INSTALL.rst
  fieldservice_recurring/readme/ROADMAP.rst
  fieldservice_recurring/readme/USAGE.rst
  fieldservice_recurring/security/ir.model.access.csv
  fieldservice_recurring/security/recurring_security.xml
  fieldservice_recurring/security/res_groups.xml
  fieldservice_recurring/static/description/icon.png
  fieldservice_recurring/static/description/index.html
  fieldservice_recurring/tests/__init__.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_frequency.xml
  fieldservice_recurring/views/fsm_frequency_set.xml
  fieldservice_recurring/views/fsm_order.xml
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_recurring_template.xml
  setup/fieldservice_recurring/odoo/addons/fieldservice_recurring
  setup/fieldservice_recurring/setup.py
Labels: migration, bot is merging ⏳

#748 [14.0][IMP] fieldservice: add fsm_location as res.partner type
  fieldservice/models/res_partner.py
  fieldservice/tests/test_fsm_location.py
Labels: enhancement, bot is merging ⏳

#853 [14.0][FIX]fieldservice: Cannot Enable Field Service Timeline
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
Labels: bot is merging ⏳

#864 [14.0][FIX] Fixed an issue of type error while on form view load
  fieldservice_stock/views/fsm_order.xml
Labels: bot is merging ⏳

#852 [12.0][IMP] Removed automatic Scheduled Date Start from FSM.Order Creation
  fieldservice/models/fsm_order.py
  fieldservice/tests/test_fsm_order.py
  fieldservice/tests/test_fsm_team.py
Labels: needs fixing, bot is merging ⏳

#866 [14.0][FIX] fieldservice_recurring: Fix api.constraint with recordset
  fieldservice_recurring/models/fsm_frequency.py
Labels: bot is merging ⏳

#868 [14.0][PORT] fieldservice_recurring: Add demo data
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/demo/frequency_demo.xml
  fieldservice_recurring/demo/frequency_set_demo.xml
  fieldservice_recurring/demo/recur_template_demo.xml
Labels: bot is merging ⏳

#869 [14.0][FW] [IMP] fieldservice: basic security
  fieldservice/security/ir.model.access.csv
  fieldservice/security/ir_rule.xml
  fieldservice/security/res_groups.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/menu.xml
  fieldservice/views/res_partner.xml
Labels: bot is merging ⏳

#873 [14.0][FW][12.0] Fix default datetime on FSM Order's request_early #850
  fieldservice/models/fsm_order.py
Labels: bot is merging ⏳

#870 [14.0][FW] [12.0][FIX]Added float_time widget to fsm.order form view
  fieldservice/views/fsm_order.xml
Labels: approved, bot is merging ⏳

#871 [14.0][FW] [12.0][FIX]Fixed _compute_request_late methods
  fieldservice/models/fsm_order.py
  fieldservice_recurring/models/fsm_order.py
Labels: bot is merging ⏳
