Repository OCA/field-service, pull requests merged in 2021-06, with the labels that each got.

#744 [14.0][MIG]fieldservice_account
  fieldservice_account/README.rst
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/i18n/de.po
  fieldservice_account/i18n/es.po
  fieldservice_account/i18n/es_CL.po
  fieldservice_account/i18n/fieldservice_account.pot
  fieldservice_account/i18n/it.po
  fieldservice_account/i18n/pt_BR.po
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_move.py
  fieldservice_account/models/account_move_line.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/readme/CONFIGURE.rst
  fieldservice_account/readme/CONTRIBUTORS.rst
  fieldservice_account/readme/CREDITS.rst
  fieldservice_account/readme/DESCRIPTION.rst
  fieldservice_account/readme/INSTALL.rst
  fieldservice_account/readme/USAGE.rst
  fieldservice_account/security/ir.model.access.csv
  fieldservice_account/static/description/icon.png
  fieldservice_account/static/description/index.html
  fieldservice_account/tests/__init__.py
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/views/account_move.xml
  fieldservice_account/views/fsm_order.xml
  setup/fieldservice_account/odoo/addons/fieldservice_account
  setup/fieldservice_account/setup.py
Labels: approved, bot is merging ⏳, migration

#791 [14.0][FIX] fieldservice_timeline.
  fieldservice_timeline/static/src/js/fsm_gantt_person_filter.js
  fieldservice_timeline/static/src/xml/fsm_gantt_person_filter.xml
Labels: bot is merging ⏳

#799 [14.0][FIX] fieldservice
  fieldservice/models/fsm_location.py
Labels: bot is merging ⏳, bug

#801 [14.0][MIG] fieldservice_crm
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/i18n/de.po
  fieldservice_crm/i18n/es_AR.po
  fieldservice_crm/i18n/es_CL.po
  fieldservice_crm/i18n/fieldservice_crm.pot
  fieldservice_crm/i18n/pt_BR.po
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/readme/CONFIGURE.rst
  fieldservice_crm/readme/CONTRIBUTORS.rst
  fieldservice_crm/readme/CREDITS.rst
  fieldservice_crm/readme/DESCRIPTION.rst
  fieldservice_crm/readme/INSTALL.rst
  fieldservice_crm/readme/ROADMAP.rst
  fieldservice_crm/readme/USAGE.rst
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/static/description/index.html
  fieldservice_crm/tests/__init__.py
  fieldservice_crm/tests/test_fsm_crm.py
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
  setup/fieldservice_crm/odoo/addons/fieldservice_crm
  setup/fieldservice_crm/setup.py
Labels: approved, bot is merging ⏳

#796 [12.0][FIX] fieldservice (Create Worker Error)
  fieldservice/views/fsm_person.xml
Labels: approved, bot is merging ⏳
