Repository OCA/field-service, pull requests merged in 2021-07, with the labels that each got.

#794 [12.0][FIX] Fieldservice_Stock: Fix inventory_location_id default
  fieldservice_stock/models/fsm_location.py
Labels: bot is merging ⏳

#793 [14.0][FIX] fieldservice
  fieldservice/models/fsm_person.py
Labels: bot is merging ⏳, bug

#789 [14.0][FIX]fieldservice_timeline
  fieldservice_timeline/__init__.py
  fieldservice_timeline/models/__init__.py
  fieldservice_timeline/models/fsm_person.py
Labels: bot is merging ⏳, bug

#763 [14.0][MIG] fieldservice_account_analytic
  fieldservice_account_analytic/README.rst
  fieldservice_account_analytic/__init__.py
  fieldservice_account_analytic/__manifest__.py
  fieldservice_account_analytic/data/ir_rule.xml
  fieldservice_account_analytic/demo/fsm_location.xml
  fieldservice_account_analytic/i18n/es.po
  fieldservice_account_analytic/i18n/es_AR.po
  fieldservice_account_analytic/i18n/es_CL.po
  fieldservice_account_analytic/i18n/fieldservice_account_analytic.pot
  fieldservice_account_analytic/i18n/pt_BR.po
  fieldservice_account_analytic/i18n/pt_PT.po
  fieldservice_account_analytic/init_hook.py
  fieldservice_account_analytic/migrations/14.0.1.0.0/post-migration.py
  fieldservice_account_analytic/models/__init__.py
  fieldservice_account_analytic/models/account_move.py
  fieldservice_account_analytic/models/analytic_account.py
  fieldservice_account_analytic/models/fsm_location.py
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_account_analytic/models/res_company.py
  fieldservice_account_analytic/models/res_config_settings.py
  fieldservice_account_analytic/readme/CONFIGURE.rst
  fieldservice_account_analytic/readme/CONTRIBUTORS.rst
  fieldservice_account_analytic/readme/CREDITS.rst
  fieldservice_account_analytic/readme/DESCRIPTION.rst
  fieldservice_account_analytic/readme/INSTALL.rst
  fieldservice_account_analytic/readme/USAGE.rst
  fieldservice_account_analytic/report/fsm_order_report_template.xml
  fieldservice_account_analytic/security/ir.model.access.csv
  fieldservice_account_analytic/static/description/icon.png
  fieldservice_account_analytic/static/description/index.html
  fieldservice_account_analytic/tests/__init__.py
  fieldservice_account_analytic/tests/test_fsm_account_wizard.py
  fieldservice_account_analytic/views/fsm_location.xml
  fieldservice_account_analytic/views/fsm_order.xml
  fieldservice_account_analytic/views/res_config_settings.xml
  fieldservice_account_analytic/wizard/__init__.py
  fieldservice_account_analytic/wizard/fsm_wizard.py
  setup/fieldservice_account_analytic/odoo/addons/fieldservice_account_analytic
  setup/fieldservice_account_analytic/setup.py
Labels: approved, migration

#780 [14.0][MIG] fieldservice_route
  fieldservice_route/README.rst
  fieldservice_route/__init__.py
  fieldservice_route/__manifest__.py
  fieldservice_route/data/fsm_route_day_data.xml
  fieldservice_route/data/fsm_stage_data.xml
  fieldservice_route/data/ir_sequence.xml
  fieldservice_route/i18n/es_CL.po
  fieldservice_route/i18n/fieldservice_route.pot
  fieldservice_route/i18n/pt_BR.po
  fieldservice_route/i18n/pt_PT.po
  fieldservice_route/migrations/14.0.1.0.0/pre-migration.py
  fieldservice_route/models/__init__.py
  fieldservice_route/models/fsm_location.py
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route.py
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/models/fsm_stage.py
  fieldservice_route/readme/CONFIGURE.rst
  fieldservice_route/readme/CONTRIBUTORS.rst
  fieldservice_route/readme/CREDITS.rst
  fieldservice_route/readme/DESCRIPTION.rst
  fieldservice_route/readme/USAGE.rst
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/static/description/icon.png
  fieldservice_route/static/description/index.html
  fieldservice_route/tests/__init__.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_location.xml
  fieldservice_route/views/fsm_order.xml
  fieldservice_route/views/fsm_route.xml
  fieldservice_route/views/fsm_route_day.xml
  fieldservice_route/views/fsm_route_dayroute.xml
  fieldservice_route/views/menu.xml
  setup/fieldservice_route/odoo/addons/fieldservice_route
  setup/fieldservice_route/setup.py
Labels: bot is merging ⏳, migration

#820 [14.0] [mig] fieldservice_stock
  fieldservice_stock/README.rst
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/data/fsm_stock_data.xml
  fieldservice_stock/i18n/de.po
  fieldservice_stock/i18n/es.po
  fieldservice_stock/i18n/es_CL.po
  fieldservice_stock/i18n/fieldservice_stock.pot
  fieldservice_stock/i18n/pt_BR.po
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/fsm_wizard.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/res_territory.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_picking.py
  fieldservice_stock/models/stock_rule.py
  fieldservice_stock/readme/CONFIGURE.rst
  fieldservice_stock/readme/CONTRIBUTORS.rst
  fieldservice_stock/readme/CREDITS.rst
  fieldservice_stock/readme/DESCRIPTION.rst
  fieldservice_stock/readme/INSTALL.rst
  fieldservice_stock/readme/ROADMAP.rst
  fieldservice_stock/readme/USAGE.rst
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock/static/description/icon.png
  fieldservice_stock/static/description/index.html
  fieldservice_stock/tests/__init__.py
  fieldservice_stock/tests/test_fsm_stock.py
  fieldservice_stock/tests/test_fsm_wizard.py
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/res_territory.xml
  fieldservice_stock/views/stock.xml
  setup/fieldservice_stock/odoo/addons/fieldservice_stock
  setup/fieldservice_stock/setup.py
Labels: approved, bot is merging ⏳

#760 [14.0][MIG] fieldservice_distribution
  fieldservice_distribution/README.rst
  fieldservice_distribution/__init__.py
  fieldservice_distribution/__manifest__.py
  fieldservice_distribution/i18n/de.po
  fieldservice_distribution/i18n/es.po
  fieldservice_distribution/i18n/es_AR.po
  fieldservice_distribution/i18n/es_CL.po
  fieldservice_distribution/i18n/fieldservice_distribution.pot
  fieldservice_distribution/i18n/pt_BR.po
  fieldservice_distribution/models/__init__.py
  fieldservice_distribution/models/fsm_location.py
  fieldservice_distribution/readme/CONTRIBUTORS.rst
  fieldservice_distribution/readme/CREDITS.rst
  fieldservice_distribution/readme/DESCRIPTION.rst
  fieldservice_distribution/readme/ROADMAP.rst
  fieldservice_distribution/readme/USAGE.rst
  fieldservice_distribution/static/description/icon.png
  fieldservice_distribution/static/description/index.html
  fieldservice_distribution/tests/__init__.py
  fieldservice_distribution/tests/test_fsm_distribution.py
  fieldservice_distribution/views/fsm_location.xml
  setup/fieldservice_distribution/odoo/addons/fieldservice_distribution
  setup/fieldservice_distribution/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#722 [14.0][MIG] fieldservice_isp_flow
  fieldservice_isp_flow/README.rst
  fieldservice_isp_flow/__init__.py
  fieldservice_isp_flow/__manifest__.py
  fieldservice_isp_flow/data/fsm_stage.xml
  fieldservice_isp_flow/i18n/de.po
  fieldservice_isp_flow/i18n/es.po
  fieldservice_isp_flow/i18n/es_CL.po
  fieldservice_isp_flow/i18n/fieldservice_isp_flow.pot
  fieldservice_isp_flow/i18n/pt_BR.po
  fieldservice_isp_flow/models/__init__.py
  fieldservice_isp_flow/models/fsm_order.py
  fieldservice_isp_flow/readme/CONFIGURE.rst
  fieldservice_isp_flow/readme/CONTRIBUTORS.rst
  fieldservice_isp_flow/readme/CREDITS.rst
  fieldservice_isp_flow/readme/DESCRIPTION.rst
  fieldservice_isp_flow/readme/ROADMAP.rst
  fieldservice_isp_flow/readme/USAGE.rst
  fieldservice_isp_flow/static/description/icon.png
  fieldservice_isp_flow/static/description/index.html
  fieldservice_isp_flow/tests/__init__.py
  fieldservice_isp_flow/tests/test_fsm_isp_flow.py
  fieldservice_isp_flow/views/fsm_order.xml
  setup/fieldservice_isp_flow/odoo/addons/fieldservice_isp_flow
  setup/fieldservice_isp_flow/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#819 [14.0][MIG] fieldservice_partner_multi_relation
  fieldservice_partner_multi_relation/README.rst
  fieldservice_partner_multi_relation/__init__.py
  fieldservice_partner_multi_relation/__manifest__.py
  fieldservice_partner_multi_relation/data/demo.xml
  fieldservice_partner_multi_relation/i18n/de.po
  fieldservice_partner_multi_relation/i18n/es.po
  fieldservice_partner_multi_relation/i18n/es_CL.po
  fieldservice_partner_multi_relation/i18n/fieldservice_partner_multi_relation.pot
  fieldservice_partner_multi_relation/i18n/pt_BR.po
  fieldservice_partner_multi_relation/models/__init__.py
  fieldservice_partner_multi_relation/models/fsm_location.py
  fieldservice_partner_multi_relation/models/res_partner.py
  fieldservice_partner_multi_relation/models/res_partner_relation_all.py
  fieldservice_partner_multi_relation/models/res_partner_relation_type.py
  fieldservice_partner_multi_relation/readme/CONFIGURE.rst
  fieldservice_partner_multi_relation/readme/CONTRIBUTORS.rst
  fieldservice_partner_multi_relation/readme/CREDITS.rst
  fieldservice_partner_multi_relation/readme/DESCRIPTION.rst
  fieldservice_partner_multi_relation/readme/INSTALL.rst
  fieldservice_partner_multi_relation/readme/ROADMAP.rst
  fieldservice_partner_multi_relation/readme/USAGE.rst
  fieldservice_partner_multi_relation/static/description/icon.png
  fieldservice_partner_multi_relation/static/description/index.html
  fieldservice_partner_multi_relation/tests/__init__.py
  fieldservice_partner_multi_relation/tests/test_fieldservice_partner_multi_relation.py
  fieldservice_partner_multi_relation/views/fsm_location.xml
  fieldservice_partner_multi_relation/views/menu.xml
  setup/fieldservice_partner_multi_relation/odoo/addons/fieldservice_partner_multi_relation
  setup/fieldservice_partner_multi_relation/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#761 [14.0][MIG] fieldservice_sale
  fieldservice_sale/README.rst
  fieldservice_sale/__init__.py
  fieldservice_sale/__manifest__.py
  fieldservice_sale/i18n/de.po
  fieldservice_sale/i18n/es.po
  fieldservice_sale/i18n/es_CL.po
  fieldservice_sale/i18n/fieldservice_sale.pot
  fieldservice_sale/i18n/pt_BR.po
  fieldservice_sale/migrations/14.0.1.0.0/pre-migration.py
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_order.py
  fieldservice_sale/models/product_template.py
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/readme/CONFIGURE.rst
  fieldservice_sale/readme/CONTRIBUTORS.rst
  fieldservice_sale/readme/DESCRIPTION.rst
  fieldservice_sale/readme/INSTALL.rst
  fieldservice_sale/readme/ROADMAP.rst
  fieldservice_sale/readme/USAGE.rst
  fieldservice_sale/security/ir.model.access.csv
  fieldservice_sale/static/description/icon.png
  fieldservice_sale/static/description/index.html
  fieldservice_sale/tests/__init__.py
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_onchange_partner.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale/views/fsm_location.xml
  fieldservice_sale/views/fsm_order.xml
  fieldservice_sale/views/product_template.xml
  fieldservice_sale/views/res_config_settings.xml
  fieldservice_sale/views/sale_order.xml
  setup/fieldservice_sale/odoo/addons/fieldservice_sale
  setup/fieldservice_sale/setup.py
Labels: Blocked by dependency, bot is merging ⏳, migration

#805 [14.0][MIG] fieldservice_isp_account
  fieldservice_isp_account/README.rst
  fieldservice_isp_account/__init__.py
  fieldservice_isp_account/__manifest__.py
  fieldservice_isp_account/data/time_products.xml
  fieldservice_isp_account/i18n/es_AR.po
  fieldservice_isp_account/i18n/es_CL.po
  fieldservice_isp_account/i18n/fieldservice_isp_account.pot
  fieldservice_isp_account/i18n/pt_BR.po
  fieldservice_isp_account/models/__init__.py
  fieldservice_isp_account/models/fsm_order.py
  fieldservice_isp_account/models/fsm_order_cost.py
  fieldservice_isp_account/models/fsm_person.py
  fieldservice_isp_account/readme/CONFIGURE.rst
  fieldservice_isp_account/readme/CONTRIBUTORS.rst
  fieldservice_isp_account/readme/CREDITS.rst
  fieldservice_isp_account/readme/DESCRIPTION.rst
  fieldservice_isp_account/readme/INSTALL.rst
  fieldservice_isp_account/readme/USAGE.rst
  fieldservice_isp_account/security/fsm_order_cost.xml
  fieldservice_isp_account/security/ir.model.access.csv
  fieldservice_isp_account/static/description/icon.png
  fieldservice_isp_account/static/description/index.html
  fieldservice_isp_account/tests/__init__.py
  fieldservice_isp_account/tests/test_isp_account.py
  fieldservice_isp_account/views/account.xml
  fieldservice_isp_account/views/fsm_order.xml
  fieldservice_isp_account/views/fsm_person.xml
  fieldservice_isp_account/views/hr_timesheet.xml
  setup/fieldservice_isp_account/odoo/addons/fieldservice_isp_account
  setup/fieldservice_isp_account/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#781 [14.0][MIG] fieldservice_agreement (Version 12.0 to 14.0)
  fieldservice_agreement/README.rst
  fieldservice_agreement/__init__.py
  fieldservice_agreement/__manifest__.py
  fieldservice_agreement/i18n/de.po
  fieldservice_agreement/i18n/es.po
  fieldservice_agreement/i18n/es_AR.po
  fieldservice_agreement/i18n/es_CL.po
  fieldservice_agreement/i18n/fieldservice_agreement.pot
  fieldservice_agreement/i18n/pt_BR.po
  fieldservice_agreement/models/__init__.py
  fieldservice_agreement/models/agreement.py
  fieldservice_agreement/models/fsm_equipment.py
  fieldservice_agreement/models/fsm_location.py
  fieldservice_agreement/models/fsm_order.py
  fieldservice_agreement/models/fsm_person.py
  fieldservice_agreement/readme/CONFIGURE.rst
  fieldservice_agreement/readme/CONTRIBUTORS.rst
  fieldservice_agreement/readme/CREDITS.rst
  fieldservice_agreement/readme/DESCRIPTION.rst
  fieldservice_agreement/readme/ROADMAP.rst
  fieldservice_agreement/readme/USAGE.rst
  fieldservice_agreement/static/description/icon.png
  fieldservice_agreement/static/description/index.html
  fieldservice_agreement/tests/__init__.py
  fieldservice_agreement/tests/test_fsm_agreement.py
  fieldservice_agreement/views/agreement_view.xml
  fieldservice_agreement/views/fsm_equipment_view.xml
  fieldservice_agreement/views/fsm_location.xml
  fieldservice_agreement/views/fsm_order_view.xml
  fieldservice_agreement/views/fsm_person.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, migration, ready to merge

#734 [14.0][ADD] fieldservice_calendar
  fieldservice_calendar/README.rst
  fieldservice_calendar/__init__.py
  fieldservice_calendar/__manifest__.py
  fieldservice_calendar/models/__init__.py
  fieldservice_calendar/models/calendar.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_calendar/models/fsm_team.py
  fieldservice_calendar/readme/CONFIGURE.rst
  fieldservice_calendar/readme/CONTRIBUTORS.rst
  fieldservice_calendar/readme/DESCRIPTION.rst
  fieldservice_calendar/static/description/index.html
  fieldservice_calendar/tests/__init__.py
  fieldservice_calendar/tests/test_fsm_calendar.py
  fieldservice_calendar/views/fsm_order.xml
  fieldservice_calendar/views/fsm_team.xml
  setup/fieldservice_calendar/odoo/addons/fieldservice_calendar
  setup/fieldservice_calendar/setup.py
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#818 [14.0][MIG] fieldservice_equipment_stock
  fieldservice_equipment_stock/README.rst
  fieldservice_equipment_stock/__init__.py
  fieldservice_equipment_stock/__manifest__.py
  fieldservice_equipment_stock/i18n/fieldservice_equipment_stock.pot
  fieldservice_equipment_stock/i18n/pt_BR.po
  fieldservice_equipment_stock/models/__init__.py
  fieldservice_equipment_stock/models/fsm_equipment.py
  fieldservice_equipment_stock/models/product_template.py
  fieldservice_equipment_stock/models/stock_move.py
  fieldservice_equipment_stock/models/stock_picking_type.py
  fieldservice_equipment_stock/models/stock_production_lot.py
  fieldservice_equipment_stock/readme/CONFIGURE.rst
  fieldservice_equipment_stock/readme/CONTRIBUTORS.rst
  fieldservice_equipment_stock/readme/CREDITS.rst
  fieldservice_equipment_stock/readme/DESCRIPTION.rst
  fieldservice_equipment_stock/readme/ROADMAP.rst
  fieldservice_equipment_stock/readme/USAGE.rst
  fieldservice_equipment_stock/security/ir.model.access.csv
  fieldservice_equipment_stock/static/description/icon.png
  fieldservice_equipment_stock/static/description/index.html
  fieldservice_equipment_stock/tests/__init__.py
  fieldservice_equipment_stock/tests/test_fsm_equipment.py
  fieldservice_equipment_stock/tests/test_stock_move.py
  fieldservice_equipment_stock/views/fsm_equipment.xml
  fieldservice_equipment_stock/views/product_template.xml
  fieldservice_equipment_stock/views/stock_picking_type.xml
  fieldservice_equipment_stock/views/stock_production_lot.xml
  setup/fieldservice_equipment_stock/odoo/addons/fieldservice_equipment_stock
  setup/fieldservice_equipment_stock/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#828 [14.0][FIX]res.config.settings for AttributeError
  fieldservice/models/res_config_settings.py
Labels: approved, bot is merging ⏳

#700 [14.0][MIG] fieldservice_purchase : Migrated the module in v14.
  fieldservice_purchase/README.rst
  fieldservice_purchase/__init__.py
  fieldservice_purchase/__manifest__.py
  fieldservice_purchase/i18n/de.po
  fieldservice_purchase/i18n/es_CL.po
  fieldservice_purchase/i18n/fieldservice_purchase.pot
  fieldservice_purchase/i18n/pt_BR.po
  fieldservice_purchase/models/__init__.py
  fieldservice_purchase/models/fsm_person.py
  fieldservice_purchase/readme/CONTRIBUTORS.rst
  fieldservice_purchase/readme/CREDITS.rst
  fieldservice_purchase/readme/DESCRIPTION.rst
  fieldservice_purchase/readme/ROADMAP.rst
  fieldservice_purchase/readme/USAGE.rst
  fieldservice_purchase/security/ir.model.access.csv
  fieldservice_purchase/static/description/icon.png
  fieldservice_purchase/static/description/index.html
  fieldservice_purchase/tests/__init__.py
  fieldservice_purchase/tests/test_fieldservice_purchase.py
  fieldservice_purchase/views/fsm_person.xml
  setup/fieldservice_purchase/odoo/addons/fieldservice_purchase
  setup/fieldservice_purchase/setup.py
Labels: bot is merging ⏳, migration

#701 [14.0][MIG] fieldservice_stage_server_action: Migrated the module in v14.
  fieldservice_stage_server_action/README.rst
  fieldservice_stage_server_action/__init__.py
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/data/base_automation.xml
  fieldservice_stage_server_action/data/fsm_stage.xml
  fieldservice_stage_server_action/data/ir_server_action.xml
  fieldservice_stage_server_action/i18n/de.po
  fieldservice_stage_server_action/i18n/es.po
  fieldservice_stage_server_action/i18n/es_CL.po
  fieldservice_stage_server_action/i18n/fieldservice_stage_server_action.pot
  fieldservice_stage_server_action/i18n/pt_BR.po
  fieldservice_stage_server_action/models/__init__.py
  fieldservice_stage_server_action/models/fsm_stage.py
  fieldservice_stage_server_action/readme/CONFIGURE.rst
  fieldservice_stage_server_action/readme/CONTRIBUTORS.rst
  fieldservice_stage_server_action/readme/DESCRIPTION.rst
  fieldservice_stage_server_action/readme/USAGE.rst
  fieldservice_stage_server_action/static/description/icon.png
  fieldservice_stage_server_action/static/description/index.html
  fieldservice_stage_server_action/views/fsm_stage.xml
  setup/fieldservice_stage_server_action/odoo/addons/fieldservice_stage_server_action
  setup/fieldservice_stage_server_action/setup.py
Labels: bot is merging ⏳, migration

#688 [14.0][MIG]fieldservice_activity
  fieldservice/i18n/fieldservice.pot
  fieldservice_activity/README.rst
  fieldservice_activity/__init__.py
  fieldservice_activity/__manifest__.py
  fieldservice_activity/i18n/es_AR.po
  fieldservice_activity/i18n/es_CL.po
  fieldservice_activity/i18n/fieldservice_activity.pot
  fieldservice_activity/i18n/pt_BR.po
  fieldservice_activity/i18n/pt_PT.po
  fieldservice_activity/models/__init__.py
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/models/fsm_template.py
  fieldservice_activity/readme/CONFIGURE.rst
  fieldservice_activity/readme/CONTRIBUTORS.rst
  fieldservice_activity/readme/CREDITS.rst
  fieldservice_activity/readme/DESCRIPTION.rst
  fieldservice_activity/readme/USAGE.rst
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/static/description/icon.png
  fieldservice_activity/static/description/index.html
  fieldservice_activity/tests/__init__.py
  fieldservice_activity/tests/test_fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
  setup/fieldservice_activity/odoo/addons/fieldservice_activity
  setup/fieldservice_activity/setup.py
Labels: bot is merging ⏳, migration

#703 [14.0][MIG] fieldservice_substatus
  fieldservice_substatus/README.rst
  fieldservice_substatus/__init__.py
  fieldservice_substatus/__manifest__.py
  fieldservice_substatus/data/fsm_stage.xml
  fieldservice_substatus/data/fsm_stage_status.xml
  fieldservice_substatus/data/mail_data.xml
  fieldservice_substatus/i18n/de.po
  fieldservice_substatus/i18n/es.po
  fieldservice_substatus/i18n/es_CL.po
  fieldservice_substatus/i18n/fieldservice_substatus.pot
  fieldservice_substatus/i18n/pt_BR.po
  fieldservice_substatus/models/__init__.py
  fieldservice_substatus/models/fsm_order.py
  fieldservice_substatus/models/fsm_stage.py
  fieldservice_substatus/models/fsm_stage_status.py
  fieldservice_substatus/readme/CONFIGURE.rst
  fieldservice_substatus/readme/CONTRIBUTORS.rst
  fieldservice_substatus/readme/CREDITS.rst
  fieldservice_substatus/readme/DESCRIPTION.rst
  fieldservice_substatus/readme/INSTALL.rst
  fieldservice_substatus/readme/ROADMAP.rst
  fieldservice_substatus/readme/USAGE.rst
  fieldservice_substatus/security/ir.model.access.csv
  fieldservice_substatus/static/description/icon.png
  fieldservice_substatus/static/description/index.html
  fieldservice_substatus/tests/__init__.py
  fieldservice_substatus/tests/test_fsm_substatus.py
  fieldservice_substatus/views/fsm_order.xml
  fieldservice_substatus/views/fsm_stage.xml
  fieldservice_substatus/views/fsm_stage_status.xml
  setup/fieldservice_substatus/odoo/addons/fieldservice_substatus
  setup/fieldservice_substatus/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#764 [14.0][MIG] fieldservice_account_payment
  fieldservice_account_payment/README.rst
  fieldservice_account_payment/__init__.py
  fieldservice_account_payment/__manifest__.py
  fieldservice_account_payment/i18n/es.po
  fieldservice_account_payment/i18n/es_CL.po
  fieldservice_account_payment/i18n/fieldservice_account_payment.pot
  fieldservice_account_payment/i18n/pt_BR.po
  fieldservice_account_payment/models/__init__.py
  fieldservice_account_payment/models/account_payment.py
  fieldservice_account_payment/models/fsm_order.py
  fieldservice_account_payment/readme/CONFIGURE.rst
  fieldservice_account_payment/readme/CONTRIBUTORS.rst
  fieldservice_account_payment/readme/CREDITS.rst
  fieldservice_account_payment/readme/DESCRIPTION.rst
  fieldservice_account_payment/readme/INSTALL.rst
  fieldservice_account_payment/readme/USAGE.rst
  fieldservice_account_payment/security/ir.model.access.csv
  fieldservice_account_payment/static/description/icon.png
  fieldservice_account_payment/static/description/index.html
  fieldservice_account_payment/tests/__init__.py
  fieldservice_account_payment/tests/test_fsm_account_payment.py
  fieldservice_account_payment/views/account_payment.xml
  fieldservice_account_payment/views/fsm_order.xml
  setup/fieldservice_account_payment/odoo/addons/fieldservice_account_payment
  setup/fieldservice_account_payment/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#827 [14.0][IMP] fieldservice_sale: remove required attr in product view
  fieldservice_sale/views/product_template.xml
Labels: approved, bot is merging ⏳, ready to merge
