Repository OCA/field-service, pull requests merged in 2021-05, with the labels that each got.

#783 [14.0][FIX] fieldservice_timeline
  fieldservice_timeline/models/fsm_person.py
Labels: approved, bot is merging ⏳

#757 [FIX] [12.0][fieldservice]Fixed issued of unable to set territory in a location.
  fieldservice/models/fsm_location.py
Labels: approved, bot is merging ⏳, bug, ready to merge

#751 [14.0][FIX] fieldservice: remove ref from fsm.location
  fieldservice/models/fsm_location.py
Labels: approved, bot is merging ⏳

#787 [14.0][FIX] fieldservice: Missing action "Convert to FSM Record"
  fieldservice/wizard/fsm_wizard.xml
Labels: approved, bug

#742 [IMP] fieldservice_route: partner route link
  fieldservice_route/__manifest__.py
  fieldservice_route/models/__init__.py
  fieldservice_route/models/res_partner.py
  fieldservice_route/views/res_partner_views.xml
Labels: approved, bot is merging ⏳

#724 [14.0][MIG]fieldservice_project
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/i18n/de.po
  fieldservice_project/i18n/es.po
  fieldservice_project/i18n/es_AR.po
  fieldservice_project/i18n/es_CL.po
  fieldservice_project/i18n/fieldservice_project.pot
  fieldservice_project/i18n/pt_BR.po
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/readme/CONTRIBUTORS.rst
  fieldservice_project/readme/CREDITS.rst
  fieldservice_project/readme/DESCRIPTION.rst
  fieldservice_project/readme/ROADMAP.rst
  fieldservice_project/readme/USAGE.rst
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/description/index.html
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/tests/__init__.py
  fieldservice_project/tests/common.py
  fieldservice_project/tests/test_fsm_location.py
  fieldservice_project/tests/test_fsm_order.py
  fieldservice_project/tests/test_project.py
  fieldservice_project/tests/test_project_task.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/fsm_team.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
  setup/fieldservice_project/odoo/addons/fieldservice_project
  setup/fieldservice_project/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#797 [MIG] [13.0] fieldservice_stock: Migrate to 13.0
  fieldservice_stock/README.rst
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/data/fsm_stock_data.xml
  fieldservice_stock/i18n/de.po
  fieldservice_stock/i18n/es.po
  fieldservice_stock/i18n/es_CL.po
  fieldservice_stock/i18n/fieldservice_stock.pot
  fieldservice_stock/i18n/pt_BR.po
  fieldservice_stock/migrations/13.0.1.0.0/pre-migration.py
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/fsm_wizard.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/res_territory.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_picking.py
  fieldservice_stock/models/stock_rule.py
  fieldservice_stock/readme/CONFIGURE.rst
  fieldservice_stock/readme/CONTRIBUTORS.rst
  fieldservice_stock/readme/CREDITS.rst
  fieldservice_stock/readme/DESCRIPTION.rst
  fieldservice_stock/readme/INSTALL.rst
  fieldservice_stock/readme/ROADMAP.rst
  fieldservice_stock/readme/USAGE.rst
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock/static/description/icon.png
  fieldservice_stock/static/description/index.html
  fieldservice_stock/tests/__init__.py
  fieldservice_stock/tests/common.py
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/res_territory.xml
  fieldservice_stock/views/stock.xml
  setup/fieldservice_stock/odoo/addons/fieldservice_stock
  setup/fieldservice_stock/setup.py
Labels: approved, bot is merging ⏳, migration
