Repository OCA/field-service, pull requests merged in 2021-08, with the labels that each got.

#768 [14.0][MIG] fieldservice_sale_stock
  fieldservice_sale_stock/README.rst
  fieldservice_sale_stock/__init__.py
  fieldservice_sale_stock/__manifest__.py
  fieldservice_sale_stock/i18n/es.po
  fieldservice_sale_stock/i18n/es_CL.po
  fieldservice_sale_stock/i18n/fieldservice_sale_stock.pot
  fieldservice_sale_stock/i18n/pt_BR.po
  fieldservice_sale_stock/models/__init__.py
  fieldservice_sale_stock/models/sale_order.py
  fieldservice_sale_stock/readme/CONFIGURE.rst
  fieldservice_sale_stock/readme/CONTRIBUTORS.rst
  fieldservice_sale_stock/readme/DESCRIPTION.rst
  fieldservice_sale_stock/readme/INSTALL.rst
  fieldservice_sale_stock/readme/ROADMAP.rst
  fieldservice_sale_stock/readme/USAGE.rst
  fieldservice_sale_stock/static/description/icon.png
  fieldservice_sale_stock/static/description/index.html
  fieldservice_sale_stock/tests/__init__.py
  fieldservice_sale_stock/tests/test_fsm_sale_order.py
  setup/fieldservice_sale_stock/odoo/addons/fieldservice_sale_stock
  setup/fieldservice_sale_stock/setup.py
Labels: approved, bot is merging ⏳, migration

#830 [FIX]fieldservice_equipment_stock: Issue 829
  fieldservice_equipment_stock/models/stock_move.py
Labels: bug, needs review, approved, bot is merging ⏳

#697 [14.0] [MIG] fieldservice_maintenance module
  fieldservice_maintenance/README.rst
  fieldservice_maintenance/__init__.py
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/data/fsm_order_type.xml
  fieldservice_maintenance/hooks.py
  fieldservice_maintenance/i18n/de.po
  fieldservice_maintenance/i18n/es_CL.po
  fieldservice_maintenance/i18n/fieldservice_maintenance.pot
  fieldservice_maintenance/i18n/pt_BR.po
  fieldservice_maintenance/models/__init__.py
  fieldservice_maintenance/models/fsm_equipment.py
  fieldservice_maintenance/models/fsm_order.py
  fieldservice_maintenance/models/fsm_order_type.py
  fieldservice_maintenance/models/maintenance_equipment.py
  fieldservice_maintenance/models/maintenance_request.py
  fieldservice_maintenance/readme/CONFIGURE.rst
  fieldservice_maintenance/readme/CONTRIBUTORS.rst
  fieldservice_maintenance/readme/CREDITS.rst
  fieldservice_maintenance/readme/DESCRIPTION.rst
  fieldservice_maintenance/readme/INSTALL.rst
  fieldservice_maintenance/readme/ROADMAP.rst
  fieldservice_maintenance/readme/USAGE.rst
  fieldservice_maintenance/static/description/icon.png
  fieldservice_maintenance/static/description/index.html
  fieldservice_maintenance/tests/__init__.py
  fieldservice_maintenance/tests/test_fsm_maintenance.py
  fieldservice_maintenance/views/fsm_equipment_view.xml
  fieldservice_maintenance/views/fsm_order_view.xml
  fieldservice_maintenance/views/maintenance_equipment_view.xml
  fieldservice_maintenance/views/maintenance_request_view.xml
  setup/fieldservice_equipment_stock/odoo/addons/fieldservice_equipment_stock
  setup/fieldservice_maintenance/odoo/addons/fieldservice_maintenance
  setup/fieldservice_maintenance/setup.py
Labels: approved, migration, bot is merging ⏳

#690 [14.0][MIG]fieldservice_vehicle: Migrated from v13 to v14.
  fieldservice_vehicle/README.rst
  fieldservice_vehicle/__init__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/i18n/de.po
  fieldservice_vehicle/i18n/es.po
  fieldservice_vehicle/i18n/es_CL.po
  fieldservice_vehicle/i18n/fieldservice_vehicle.pot
  fieldservice_vehicle/i18n/pt_BR.po
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_order.py
  fieldservice_vehicle/models/fsm_person.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/readme/CONFIGURE.rst
  fieldservice_vehicle/readme/CONTRIBUTORS.rst
  fieldservice_vehicle/readme/CREDITS.rst
  fieldservice_vehicle/readme/DESCRIPTION.rst
  fieldservice_vehicle/readme/INSTALL.rst
  fieldservice_vehicle/readme/ROADMAP.rst
  fieldservice_vehicle/readme/USAGE.rst
  fieldservice_vehicle/security/ir.model.access.csv
  fieldservice_vehicle/security/res_groups.xml
  fieldservice_vehicle/static/description/icon.png
  fieldservice_vehicle/static/description/index.html
  fieldservice_vehicle/views/fsm_order.xml
  fieldservice_vehicle/views/fsm_person.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
  setup/fieldservice_vehicle/odoo/addons/fieldservice_vehicle
  setup/fieldservice_vehicle/setup.py
Labels: migration, bot is merging ⏳

#730 [14.0][MIG] fieldservice_delivery
  fieldservice_delivery/README.rst
  fieldservice_delivery/__init__.py
  fieldservice_delivery/__manifest__.py
  fieldservice_delivery/i18n/de.po
  fieldservice_delivery/i18n/es.po
  fieldservice_delivery/i18n/es_AR.po
  fieldservice_delivery/i18n/es_CL.po
  fieldservice_delivery/i18n/fieldservice_delivery.pot
  fieldservice_delivery/i18n/pt_BR.po
  fieldservice_delivery/models/__init__.py
  fieldservice_delivery/models/fsm_order.py
  fieldservice_delivery/models/stock.py
  fieldservice_delivery/readme/CONFIGURE.rst
  fieldservice_delivery/readme/CONTRIBUTORS.rst
  fieldservice_delivery/readme/CREDITS.rst
  fieldservice_delivery/readme/DESCRIPTION.rst
  fieldservice_delivery/readme/INSTALL.rst
  fieldservice_delivery/readme/ROADMAP.rst
  fieldservice_delivery/readme/USAGE.rst
  fieldservice_delivery/static/description/icon.png
  fieldservice_delivery/static/description/index.html
  fieldservice_delivery/views/fsm_order.xml
  setup/fieldservice_delivery/odoo/addons/fieldservice_delivery
  setup/fieldservice_delivery/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, Blocked by dependency

#821 [14.0][MIG] fieldservice_vehicle_stock
  fieldservice_vehicle_stock/README.rst
  fieldservice_vehicle_stock/__init__.py
  fieldservice_vehicle_stock/__manifest__.py
  fieldservice_vehicle_stock/data/fsm_stock_data.xml
  fieldservice_vehicle_stock/i18n/de.po
  fieldservice_vehicle_stock/i18n/es.po
  fieldservice_vehicle_stock/i18n/es_CL.po
  fieldservice_vehicle_stock/i18n/fieldservice_vehicle_stock.pot
  fieldservice_vehicle_stock/i18n/pt_BR.po
  fieldservice_vehicle_stock/i18n/pt_PT.po
  fieldservice_vehicle_stock/models/__init__.py
  fieldservice_vehicle_stock/models/fsm_order.py
  fieldservice_vehicle_stock/models/fsm_vehicle.py
  fieldservice_vehicle_stock/models/product_putaway.py
  fieldservice_vehicle_stock/models/stock_picking.py
  fieldservice_vehicle_stock/readme/CONFIGURE.rst
  fieldservice_vehicle_stock/readme/CONTRIBUTORS.rst
  fieldservice_vehicle_stock/readme/CREDITS.rst
  fieldservice_vehicle_stock/readme/DESCRIPTION.rst
  fieldservice_vehicle_stock/readme/ROADMAP.rst
  fieldservice_vehicle_stock/security/ir.model.access.csv
  fieldservice_vehicle_stock/static/description/icon.png
  fieldservice_vehicle_stock/static/description/index.html
  fieldservice_vehicle_stock/tests/__init__.py
  fieldservice_vehicle_stock/tests/test_fsm_order.py
  fieldservice_vehicle_stock/tests/test_product_putaway.py
  fieldservice_vehicle_stock/tests/test_stock_picking.py
  fieldservice_vehicle_stock/views/fsm_vehicle.xml
  fieldservice_vehicle_stock/views/stock_picking.xml
  setup/fieldservice_vehicle_stock/odoo/addons/fieldservice_vehicle_stock
  setup/fieldservice_vehicle_stock/setup.py
Labels: approved, migration, bot is merging ⏳
