Repository OCA/field-service, pull requests merged in 2021-04, with the labels that each got.

#753 [FIX][12.0] fieldservice_vehicle_stock_request: Inherit Wrong View
  fieldservice_vehicle_stock_request/views/fsm_order.xml
Labels: bug

#743 [FIX][12.0] fieldservice_status (Field Requirement)
  fieldservice_substatus/views/fsm_stage.xml
Labels: approved, bot is merging ⏳, ready to merge

#749 [14.0][FIX] fieldservice: fixed unlink method in fsm.order
  fieldservice/models/fsm_order.py
Labels: approved, bot is merging ⏳

#758 [MIG][14.0]Migrated a fieldservice_timeline module.
  fieldservice_timeline/README.rst
  fieldservice_timeline/__init__.py
  fieldservice_timeline/__manifest__.py
  fieldservice_timeline/hooks.py
  fieldservice_timeline/models/__init__.py
  fieldservice_timeline/models/fsm_person.py
  fieldservice_timeline/readme/CONFIGURE.rst
  fieldservice_timeline/readme/CONTRIBUTORS.rst
  fieldservice_timeline/readme/CREDITS.rst
  fieldservice_timeline/readme/DESCRIPTION.rst
  fieldservice_timeline/readme/ROADMAP.rst
  fieldservice_timeline/static/description/icon.png
  fieldservice_timeline/static/description/index.html
  fieldservice_timeline/static/src/js/custom_fillter.js
  fieldservice_timeline/static/src/js/fsm_gantt.js
  fieldservice_timeline/static/src/js/fsm_gantt_person_filter.js
  fieldservice_timeline/static/src/scss/fsm_gantt_person_filter.scss
  fieldservice_timeline/static/src/xml/fsm_gantt_person_filter.xml
  fieldservice_timeline/tests/__init__.py
  fieldservice_timeline/tests/test_fsm_uninstall.py
  fieldservice_timeline/views/fsm_order.xml
  fieldservice_timeline/views/fsm_team.xml
  oca_dependencies.txt
  setup/fieldservice_timeline/odoo/addons/fieldservice_timeline
  setup/fieldservice_timeline/setup.py
Labels: bot is merging ⏳

#750 [FIX][12.0] fix dependencies of fieldservice_stock_account_analytic
  fieldservice_stock_account_analytic/__manifest__.py
Labels: approved, bot is merging ⏳, bug, ready to merge

#745 [14.0][MIG]Migrated fieldservice_skill from v13 to v14
  fieldservice_skill/README.rst
  fieldservice_skill/__init__.py
  fieldservice_skill/__manifest__.py
  fieldservice_skill/i18n/de.po
  fieldservice_skill/i18n/es.po
  fieldservice_skill/i18n/es_CL.po
  fieldservice_skill/i18n/fieldservice_skill.pot
  fieldservice_skill/i18n/pt_BR.po
  fieldservice_skill/models/__init__.py
  fieldservice_skill/models/fsm_category.py
  fieldservice_skill/models/fsm_order.py
  fieldservice_skill/models/fsm_person.py
  fieldservice_skill/models/fsm_person_skill.py
  fieldservice_skill/models/fsm_template.py
  fieldservice_skill/models/hr_skill.py
  fieldservice_skill/readme/CONFIGURE.rst
  fieldservice_skill/readme/CONTRIBUTORS.rst
  fieldservice_skill/readme/CREDITS.rst
  fieldservice_skill/readme/DESCRIPTION.rst
  fieldservice_skill/readme/INSTALL.rst
  fieldservice_skill/readme/ROADMAP.rst
  fieldservice_skill/readme/USAGE.rst
  fieldservice_skill/security/ir.model.access.csv
  fieldservice_skill/static/description/icon.png
  fieldservice_skill/static/description/index.html
  fieldservice_skill/tests/__init__.py
  fieldservice_skill/tests/test_fsm_skill.py
  fieldservice_skill/views/fsm_category.xml
  fieldservice_skill/views/fsm_order.xml
  fieldservice_skill/views/fsm_person.xml
  fieldservice_skill/views/fsm_person_skill.xml
  fieldservice_skill/views/fsm_template.xml
  fieldservice_skill/views/hr_skill.xml
  setup/fieldservice_skill/odoo/addons/fieldservice_skill
  setup/fieldservice_skill/setup.py
Labels: approved, bot is merging ⏳, migration, ready to merge

#771 [13.0][MIG] fieldservice_purchase
  fieldservice_purchase/README.rst
  fieldservice_purchase/__init__.py
  fieldservice_purchase/__manifest__.py
  fieldservice_purchase/i18n/de.po
  fieldservice_purchase/i18n/es_CL.po
  fieldservice_purchase/i18n/fieldservice_purchase.pot
  fieldservice_purchase/i18n/pt_BR.po
  fieldservice_purchase/models/__init__.py
  fieldservice_purchase/models/fsm_person.py
  fieldservice_purchase/readme/CONTRIBUTORS.rst
  fieldservice_purchase/readme/CREDITS.rst
  fieldservice_purchase/readme/DESCRIPTION.rst
  fieldservice_purchase/readme/ROADMAP.rst
  fieldservice_purchase/readme/USAGE.rst
  fieldservice_purchase/security/ir.model.access.csv
  fieldservice_purchase/static/description/icon.png
  fieldservice_purchase/static/description/index.html
  fieldservice_purchase/tests/__init__.py
  fieldservice_purchase/tests/test_fieldservice_purchase.py
  fieldservice_purchase/views/fsm_person.xml
  setup/fieldservice_purchase/odoo/addons/fieldservice_purchase
  setup/fieldservice_purchase/setup.py
Labels: approved, bot is merging ⏳, migration

#772 [13.0][MIG] fieldservice_project
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/i18n/de.po
  fieldservice_project/i18n/es.po
  fieldservice_project/i18n/es_CL.po
  fieldservice_project/i18n/fieldservice_project.pot
  fieldservice_project/i18n/pt_BR.po
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/readme/CONTRIBUTORS.rst
  fieldservice_project/readme/CREDITS.rst
  fieldservice_project/readme/DESCRIPTION.rst
  fieldservice_project/readme/ROADMAP.rst
  fieldservice_project/readme/USAGE.rst
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/description/index.html
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/tests/__init__.py
  fieldservice_project/tests/common.py
  fieldservice_project/tests/test_fsm_location.py
  fieldservice_project/tests/test_fsm_order.py
  fieldservice_project/tests/test_project.py
  fieldservice_project/tests/test_project_task.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/fsm_team.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
  setup/fieldservice_project/odoo/addons/fieldservice_project
  setup/fieldservice_project/setup.py
Labels: approved, bot is merging ⏳, migration

#775 [12.0][FIX] fieldservice_project: New orders do not get default project
  fieldservice_project/models/fsm_order.py
  fieldservice_project/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#776 [13.0][FIX] fieldservice_project: New orders do not get default project
  fieldservice_project/models/fsm_order.py
  fieldservice_project/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳
