Repository OCA/field-service, pull requests merged in 2021-09, with the labels that each got.

#838 [14.0][FIX] Improved _track_subtype method
  fieldservice_substatus/models/fsm_order.py
Labels: approved, bot is merging ⏳

#836 [14.0][FIX] fieldservice_crm: Service Location Field not showing up on Opportunities
  fieldservice_crm/views/crm_lead.xml
Labels: approved, ready to merge, bot is merging ⏳

#733 [14.0][MIG] fieldservice_repair
  fieldservice_repair/README.rst
  fieldservice_repair/__init__.py
  fieldservice_repair/__manifest__.py
  fieldservice_repair/data/fsm_order_type.xml
  fieldservice_repair/i18n/de.po
  fieldservice_repair/i18n/es.po
  fieldservice_repair/i18n/fieldservice_repair.pot
  fieldservice_repair/i18n/pt_BR.po
  fieldservice_repair/models/__init__.py
  fieldservice_repair/models/fsm_order.py
  fieldservice_repair/models/fsm_order_type.py
  fieldservice_repair/readme/CONFIGURE.rst
  fieldservice_repair/readme/CONTRIBUTORS.rst
  fieldservice_repair/readme/CREDITS.rst
  fieldservice_repair/readme/DESCRIPTION.rst
  fieldservice_repair/readme/INSTALL.rst
  fieldservice_repair/readme/ROADMAP.rst
  fieldservice_repair/readme/USAGE.rst
  fieldservice_repair/static/description/icon.png
  fieldservice_repair/static/description/index.html
  fieldservice_repair/tests/__init__.py
  fieldservice_repair/tests/test_fsm_repair.py
  fieldservice_repair/views/fsm_order_view.xml
  setup/fieldservice_repair/odoo/addons/fieldservice_repair
  setup/fieldservice_repair/setup.py
Labels: approved, migration, bot is merging ⏳

#843 [14.0][FIX] fieldservice_timeline : Fixed issued of timeline view not open.
  fieldservice_timeline/static/src/js/custom_fillter.js
Labels: bug, approved, bot is merging ⏳

#844 [12.0][FIX]Added float_time widget to fsm.order form view
  fieldservice/views/fsm_order.xml
Labels: enhancement, bot is merging ⏳
