Repository OCA/field-service, pull requests merged in 2021-01, with the labels that each got.

#591 [12.0][ADD] fieldservice_agreement_helpdesk_mgmt
  fieldservice_agreement_helpdesk_mgmt/README.rst
  fieldservice_agreement_helpdesk_mgmt/__init__.py
  fieldservice_agreement_helpdesk_mgmt/__manifest__.py
  fieldservice_agreement_helpdesk_mgmt/models/__init__.py
  fieldservice_agreement_helpdesk_mgmt/models/helpdesk_ticket.py
  fieldservice_agreement_helpdesk_mgmt/readme/CONTRIBUTORS.rst
  fieldservice_agreement_helpdesk_mgmt/readme/CREDITS.rst
  fieldservice_agreement_helpdesk_mgmt/readme/DESCRIPTION.rst
  fieldservice_agreement_helpdesk_mgmt/readme/USAGE.rst
  fieldservice_agreement_helpdesk_mgmt/static/description/banner.png
  fieldservice_agreement_helpdesk_mgmt/static/description/icon.png
  fieldservice_agreement_helpdesk_mgmt/static/description/index.html
  fieldservice_agreement_helpdesk_mgmt/tests/__init__.py
  fieldservice_agreement_helpdesk_mgmt/tests/test_fieldservice_agreement_helpdesk_mgmt.py
  fieldservice_agreement_helpdesk_mgmt/views/helpdesk_ticket.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#692 [14.0] [MIG] base_territory
  base_territory/README.rst
  base_territory/__init__.py
  base_territory/__manifest__.py
  base_territory/demo/base_territory_demo.xml
  base_territory/i18n/base_territory.pot
  base_territory/models/__init__.py
  base_territory/models/res_branch.py
  base_territory/models/res_country.py
  base_territory/models/res_district.py
  base_territory/models/res_region.py
  base_territory/models/res_territory.py
  base_territory/readme/CONTRIBUTORS.rst
  base_territory/readme/CREDITS.rst
  base_territory/readme/DESCRIPTION.rst
  base_territory/readme/USAGE.rst
  base_territory/security/ir.model.access.csv
  base_territory/static/description/icon.png
  base_territory/static/description/index.html
  base_territory/views/menu.xml
  base_territory/views/res_branch.xml
  base_territory/views/res_country.xml
  base_territory/views/res_district.xml
  base_territory/views/res_region.xml
  base_territory/views/res_territory.xml
  setup/base_territory/odoo/addons/base_territory
  setup/base_territory/setup.py
Labels: bot is merging ⏳, migration

#693 [13.0] [IMP] fieldservice: Minimize partner_fax dependency
  fieldservice/__manifest__.py
  fieldservice/views/fsm_location.xml
  fieldservice_partner_fax/README.rst
  fieldservice_partner_fax/__init__.py
  fieldservice_partner_fax/__manifest__.py
  fieldservice_partner_fax/readme/CONTRIBUTORS.rst
  fieldservice_partner_fax/readme/DESCRIPTION.rst
  fieldservice_partner_fax/readme/USAGE.rst
  fieldservice_partner_fax/static/description/icon.png
  fieldservice_partner_fax/static/description/index.html
  fieldservice_partner_fax/views/fsm_location.xml
  setup/fieldservice_partner_fax/odoo/addons/fieldservice_partner_fax
  setup/fieldservice_partner_fax/setup.py
Labels: bot is merging ⏳, enhancement
