Repository OCA/field-service, pull requests merged in 2021-11, with the labels that each got.

#856 [FIX] [14.0] fieldservice_timeline :- Fixed issued remaning props values.
  fieldservice_timeline/static/src/js/custom_fillter.js
Labels: bug, approved, bot is merging ⏳

#850 [12.0][FIX] Fix default datetime on FSM Order's request_early
  fieldservice/models/fsm_order.py
Labels: approved, ready to merge, bot is merging ⏳

#848 [FIX] by default fsm_category, fsm_tag, fsm_team, fsm_stage are share…
  fieldservice/models/fsm_category.py
  fieldservice/models/fsm_stage.py
  fieldservice/models/fsm_tag.py
  fieldservice/models/fsm_team.py
Labels: bot is merging ⏳
