Repository OCA/field-service, pull requests merged in 2022-04, with the labels that each got.

#924 [FIX][14.0] fielservice_agreement fix pre-commit
  fieldservice_agreement/views/agreement_view.xml
Labels: bug, approved, bot is merging ⏳

#925 [14][FIX] fieldservice_recurring: fsm_order_ids should be readonly
  fieldservice_recurring/views/fsm_recurring.xml
Labels: bot is merging ⏳

#923 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_sale/models/sale_order.py
Labels: help wanted, needs review, bot is merging ⏳

#927 [14.0][FIX] fieldservice: Fix limit issue
  fieldservice/models/res_partner.py
Labels: approved, bot is merging ⏳

#916 [14.0][FIX] fieldservice: adapt access to ir.actions.* records
  fieldservice/models/fsm_location.py
  fieldservice/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#918 [14.0][FIX] fieldservice_project: adapt access to ir.actions.* records
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#917 [14.0][FIX] fieldservice_partner_multi_relation: adapt access to ir.actions.…
  fieldservice_partner_multi_relation/models/fsm_location.py
  fieldservice_partner_multi_relation/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳
