Repository OCA/field-service, pull requests merged in 2022-11, with the labels that each got.

#904 [15.0][MIG] fieldservice_isp_account
  fieldservice_isp_account/README.rst
  fieldservice_isp_account/__init__.py
  fieldservice_isp_account/__manifest__.py
  fieldservice_isp_account/data/time_products.xml
  fieldservice_isp_account/i18n/es_AR.po
  fieldservice_isp_account/i18n/es_CL.po
  fieldservice_isp_account/i18n/fieldservice_isp_account.pot
  fieldservice_isp_account/i18n/pt_BR.po
  fieldservice_isp_account/models/__init__.py
  fieldservice_isp_account/models/fsm_order.py
  fieldservice_isp_account/models/fsm_order_cost.py
  fieldservice_isp_account/models/fsm_person.py
  fieldservice_isp_account/readme/CONFIGURE.rst
  fieldservice_isp_account/readme/CONTRIBUTORS.rst
  fieldservice_isp_account/readme/CREDITS.rst
  fieldservice_isp_account/readme/DESCRIPTION.rst
  fieldservice_isp_account/readme/INSTALL.rst
  fieldservice_isp_account/readme/USAGE.rst
  fieldservice_isp_account/security/fsm_order_cost.xml
  fieldservice_isp_account/security/ir.model.access.csv
  fieldservice_isp_account/static/description/icon.png
  fieldservice_isp_account/static/description/index.html
  fieldservice_isp_account/tests/__init__.py
  fieldservice_isp_account/tests/test_isp_account.py
  fieldservice_isp_account/views/account.xml
  fieldservice_isp_account/views/fsm_order.xml
  fieldservice_isp_account/views/fsm_person.xml
  fieldservice_isp_account/views/hr_timesheet.xml
  setup/fieldservice_isp_account/odoo/addons/fieldservice_isp_account
  setup/fieldservice_isp_account/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, Blocked by dependency

#897 [15.0][MIG]fieldservice_distribution
  fieldservice_distribution/README.rst
  fieldservice_distribution/__init__.py
  fieldservice_distribution/__manifest__.py
  fieldservice_distribution/i18n/de.po
  fieldservice_distribution/i18n/es.po
  fieldservice_distribution/i18n/es_AR.po
  fieldservice_distribution/i18n/es_CL.po
  fieldservice_distribution/i18n/fieldservice_distribution.pot
  fieldservice_distribution/i18n/pt_BR.po
  fieldservice_distribution/models/__init__.py
  fieldservice_distribution/models/fsm_location.py
  fieldservice_distribution/readme/CONTRIBUTORS.rst
  fieldservice_distribution/readme/CREDITS.rst
  fieldservice_distribution/readme/DESCRIPTION.rst
  fieldservice_distribution/readme/ROADMAP.rst
  fieldservice_distribution/readme/USAGE.rst
  fieldservice_distribution/static/description/icon.png
  fieldservice_distribution/static/description/index.html
  fieldservice_distribution/tests/__init__.py
  fieldservice_distribution/tests/test_fsm_distribution.py
  fieldservice_distribution/views/fsm_location.xml
  setup/fieldservice_distribution/odoo/addons/fieldservice_distribution
  setup/fieldservice_distribution/setup.py
Labels: approved, migration, bot is merging ⏳

#987 [15.0][MIG] fieldservice_skill
  fieldservice_skill/README.rst
  fieldservice_skill/__init__.py
  fieldservice_skill/__manifest__.py
  fieldservice_skill/i18n/de.po
  fieldservice_skill/i18n/es.po
  fieldservice_skill/i18n/es_AR.po
  fieldservice_skill/i18n/es_CL.po
  fieldservice_skill/i18n/fieldservice_skill.pot
  fieldservice_skill/i18n/it.po
  fieldservice_skill/i18n/pt_BR.po
  fieldservice_skill/models/__init__.py
  fieldservice_skill/models/fsm_category.py
  fieldservice_skill/models/fsm_order.py
  fieldservice_skill/models/fsm_person.py
  fieldservice_skill/models/fsm_person_skill.py
  fieldservice_skill/models/fsm_template.py
  fieldservice_skill/models/hr_skill.py
  fieldservice_skill/readme/CONFIGURE.rst
  fieldservice_skill/readme/CONTRIBUTORS.rst
  fieldservice_skill/readme/CREDITS.rst
  fieldservice_skill/readme/DESCRIPTION.rst
  fieldservice_skill/readme/INSTALL.rst
  fieldservice_skill/readme/ROADMAP.rst
  fieldservice_skill/readme/USAGE.rst
  fieldservice_skill/security/ir.model.access.csv
  fieldservice_skill/static/description/icon.png
  fieldservice_skill/static/description/index.html
  fieldservice_skill/tests/__init__.py
  fieldservice_skill/tests/test_fsm_skill.py
  fieldservice_skill/views/fsm_category.xml
  fieldservice_skill/views/fsm_order.xml
  fieldservice_skill/views/fsm_person.xml
  fieldservice_skill/views/fsm_person_skill.xml
  fieldservice_skill/views/fsm_template.xml
  fieldservice_skill/views/hr_skill.xml
  setup/fieldservice_skill/odoo/addons/fieldservice_skill
  setup/fieldservice_skill/setup.py
Labels: approved, migration, bot is merging ⏳

#986 [15.0][MIG] fieldservice_purchase
  fieldservice_purchase/README.rst
  fieldservice_purchase/__init__.py
  fieldservice_purchase/__manifest__.py
  fieldservice_purchase/i18n/de.po
  fieldservice_purchase/i18n/es_AR.po
  fieldservice_purchase/i18n/es_CL.po
  fieldservice_purchase/i18n/fieldservice_purchase.pot
  fieldservice_purchase/i18n/it.po
  fieldservice_purchase/i18n/pt_BR.po
  fieldservice_purchase/models/__init__.py
  fieldservice_purchase/models/fsm_person.py
  fieldservice_purchase/readme/CONTRIBUTORS.rst
  fieldservice_purchase/readme/CREDITS.rst
  fieldservice_purchase/readme/DESCRIPTION.rst
  fieldservice_purchase/readme/ROADMAP.rst
  fieldservice_purchase/readme/USAGE.rst
  fieldservice_purchase/security/ir.model.access.csv
  fieldservice_purchase/static/description/icon.png
  fieldservice_purchase/static/description/index.html
  fieldservice_purchase/tests/__init__.py
  fieldservice_purchase/tests/test_fieldservice_purchase.py
  fieldservice_purchase/views/fsm_person.xml
  setup/fieldservice_purchase/odoo/addons/fieldservice_purchase
  setup/fieldservice_purchase/setup.py
Labels: approved, migration, bot is merging ⏳

#977 [15.0][MIG] fieldservice_sale
  fieldservice_sale/README.rst
  fieldservice_sale/__init__.py
  fieldservice_sale/__manifest__.py
  fieldservice_sale/data/fsm_template_group.xml
  fieldservice_sale/i18n/de.po
  fieldservice_sale/i18n/es.po
  fieldservice_sale/i18n/es_AR.po
  fieldservice_sale/i18n/es_CL.po
  fieldservice_sale/i18n/fieldservice_sale.pot
  fieldservice_sale/i18n/pt_BR.po
  fieldservice_sale/migrations/15.0.1.0.0/pre-migration.py
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_order.py
  fieldservice_sale/models/product_template.py
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/readme/CONFIGURE.rst
  fieldservice_sale/readme/CONTRIBUTORS.rst
  fieldservice_sale/readme/DESCRIPTION.rst
  fieldservice_sale/readme/INSTALL.rst
  fieldservice_sale/readme/ROADMAP.rst
  fieldservice_sale/readme/USAGE.rst
  fieldservice_sale/security/ir.model.access.csv
  fieldservice_sale/static/description/icon.png
  fieldservice_sale/static/description/index.html
  fieldservice_sale/tests/__init__.py
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_onchange_partner.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale/views/fsm_location.xml
  fieldservice_sale/views/fsm_order.xml
  fieldservice_sale/views/product_template.xml
  fieldservice_sale/views/sale_order.xml
  setup/fieldservice_sale/odoo/addons/fieldservice_sale
  setup/fieldservice_sale/setup.py
Labels: approved, migration, bot is merging ⏳

#902 [15.0][MIG] fieldservice_recurring
  fieldservice_recurring/README.rst
  fieldservice_recurring/__init__.py
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/data/ir_sequence.xml
  fieldservice_recurring/data/recurring_cron.xml
  fieldservice_recurring/demo/frequency_demo.xml
  fieldservice_recurring/demo/frequency_set_demo.xml
  fieldservice_recurring/demo/recur_template_demo.xml
  fieldservice_recurring/i18n/de.po
  fieldservice_recurring/i18n/es.po
  fieldservice_recurring/i18n/es_AR.po
  fieldservice_recurring/i18n/es_CL.po
  fieldservice_recurring/i18n/fieldservice_recurring.pot
  fieldservice_recurring/i18n/it.po
  fieldservice_recurring/i18n/pt_BR.po
  fieldservice_recurring/i18n/tr.po
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_recurring_template.py
  fieldservice_recurring/readme/CONFIGURE.rst
  fieldservice_recurring/readme/CONTRIBUTORS.rst
  fieldservice_recurring/readme/CREDITS.rst
  fieldservice_recurring/readme/DESCRIPTION.rst
  fieldservice_recurring/readme/INSTALL.rst
  fieldservice_recurring/readme/ROADMAP.rst
  fieldservice_recurring/readme/USAGE.rst
  fieldservice_recurring/security/ir.model.access.csv
  fieldservice_recurring/security/recurring_security.xml
  fieldservice_recurring/security/res_groups.xml
  fieldservice_recurring/static/description/icon.png
  fieldservice_recurring/static/description/index.html
  fieldservice_recurring/tests/__init__.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_frequency.xml
  fieldservice_recurring/views/fsm_frequency_set.xml
  fieldservice_recurring/views/fsm_order.xml
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_recurring_template.xml
  setup/fieldservice_recurring/odoo/addons/fieldservice_recurring
  setup/fieldservice_recurring/setup.py
Labels: approved, migration, bot is merging ⏳, need tests

#983 [16.0][MIG] fieldservice_crm
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/i18n/de.po
  fieldservice_crm/i18n/es_AR.po
  fieldservice_crm/i18n/es_CL.po
  fieldservice_crm/i18n/fieldservice_crm.pot
  fieldservice_crm/i18n/it.po
  fieldservice_crm/i18n/pt_BR.po
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/readme/CONFIGURE.rst
  fieldservice_crm/readme/CONTRIBUTORS.rst
  fieldservice_crm/readme/CREDITS.rst
  fieldservice_crm/readme/DESCRIPTION.rst
  fieldservice_crm/readme/INSTALL.rst
  fieldservice_crm/readme/ROADMAP.rst
  fieldservice_crm/readme/USAGE.rst
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/static/description/index.html
  fieldservice_crm/tests/__init__.py
  fieldservice_crm/tests/test_fsm_crm.py
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
  setup/fieldservice_crm/odoo/addons/fieldservice_crm
  setup/fieldservice_crm/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#901 [15.0][MIG] fieldservice_account_payment
  fieldservice_account_payment/README.rst
  fieldservice_account_payment/__init__.py
  fieldservice_account_payment/__manifest__.py
  fieldservice_account_payment/i18n/es.po
  fieldservice_account_payment/i18n/es_AR.po
  fieldservice_account_payment/i18n/es_CL.po
  fieldservice_account_payment/i18n/fieldservice_account_payment.pot
  fieldservice_account_payment/i18n/it.po
  fieldservice_account_payment/i18n/pt_BR.po
  fieldservice_account_payment/models/__init__.py
  fieldservice_account_payment/models/account_payment.py
  fieldservice_account_payment/models/fsm_order.py
  fieldservice_account_payment/readme/CONFIGURE.rst
  fieldservice_account_payment/readme/CONTRIBUTORS.rst
  fieldservice_account_payment/readme/CREDITS.rst
  fieldservice_account_payment/readme/DESCRIPTION.rst
  fieldservice_account_payment/readme/INSTALL.rst
  fieldservice_account_payment/readme/USAGE.rst
  fieldservice_account_payment/security/ir.model.access.csv
  fieldservice_account_payment/static/description/icon.png
  fieldservice_account_payment/static/description/index.html
  fieldservice_account_payment/tests/__init__.py
  fieldservice_account_payment/tests/test_fsm_account_payment.py
  fieldservice_account_payment/views/account_payment.xml
  fieldservice_account_payment/views/fsm_order.xml
  setup/fieldservice_account_payment/odoo/addons/fieldservice_account_payment
  setup/fieldservice_account_payment/setup.py
Labels: needs fixing, approved, migration, bot is merging ⏳

#896 [15.0][MIG] fieldservice_delivery
  fieldservice_delivery/README.rst
  fieldservice_delivery/__init__.py
  fieldservice_delivery/__manifest__.py
  fieldservice_delivery/i18n/de.po
  fieldservice_delivery/i18n/es.po
  fieldservice_delivery/i18n/es_AR.po
  fieldservice_delivery/i18n/es_CL.po
  fieldservice_delivery/i18n/fieldservice_delivery.pot
  fieldservice_delivery/i18n/it.po
  fieldservice_delivery/i18n/pt_BR.po
  fieldservice_delivery/models/__init__.py
  fieldservice_delivery/models/fsm_order.py
  fieldservice_delivery/models/stock.py
  fieldservice_delivery/readme/CONFIGURE.rst
  fieldservice_delivery/readme/CONTRIBUTORS.rst
  fieldservice_delivery/readme/CREDITS.rst
  fieldservice_delivery/readme/DESCRIPTION.rst
  fieldservice_delivery/readme/INSTALL.rst
  fieldservice_delivery/readme/ROADMAP.rst
  fieldservice_delivery/readme/USAGE.rst
  fieldservice_delivery/static/description/icon.png
  fieldservice_delivery/static/description/index.html
  fieldservice_delivery/tests/__init__.py
  fieldservice_delivery/tests/test_fsm_delivery.py
  fieldservice_delivery/views/fsm_order.xml
  setup/fieldservice_delivery/odoo/addons/fieldservice_delivery
  setup/fieldservice_delivery/setup.py
Labels: needs fixing, approved, migration, ready to merge, bot is merging ⏳

#970 [FIX] fieldervice_activity
  fieldservice_activity/models/fsm_order.py
Labels: bug, needs fixing, needs review, approved, ready to merge, bot is merging ⏳

#988 [15.0][MIG] fieldservice_sale_stock
  fieldservice_sale_stock/README.rst
  fieldservice_sale_stock/__init__.py
  fieldservice_sale_stock/__manifest__.py
  fieldservice_sale_stock/i18n/es.po
  fieldservice_sale_stock/i18n/es_AR.po
  fieldservice_sale_stock/i18n/es_CL.po
  fieldservice_sale_stock/i18n/fieldservice_sale_stock.pot
  fieldservice_sale_stock/i18n/it.po
  fieldservice_sale_stock/i18n/pt_BR.po
  fieldservice_sale_stock/models/__init__.py
  fieldservice_sale_stock/models/sale_order.py
  fieldservice_sale_stock/readme/CONFIGURE.rst
  fieldservice_sale_stock/readme/CONTRIBUTORS.rst
  fieldservice_sale_stock/readme/DESCRIPTION.rst
  fieldservice_sale_stock/readme/INSTALL.rst
  fieldservice_sale_stock/readme/ROADMAP.rst
  fieldservice_sale_stock/readme/USAGE.rst
  fieldservice_sale_stock/static/description/icon.png
  fieldservice_sale_stock/static/description/index.html
  fieldservice_sale_stock/tests/__init__.py
  fieldservice_sale_stock/tests/test_fsm_sale_order.py
  setup/fieldservice_sale_stock/odoo/addons/fieldservice_sale_stock
  setup/fieldservice_sale_stock/setup.py
Labels: migration, bot is merging ⏳, need tests

#894 [15.0][MIG] fieldservice_equipment_stock
  .github/workflows/pre-commit.yml
  fieldservice_equipment_stock/README.rst
  fieldservice_equipment_stock/__init__.py
  fieldservice_equipment_stock/__manifest__.py
  fieldservice_equipment_stock/i18n/es_AR.po
  fieldservice_equipment_stock/i18n/fieldservice_equipment_stock.pot
  fieldservice_equipment_stock/i18n/pt_BR.po
  fieldservice_equipment_stock/models/__init__.py
  fieldservice_equipment_stock/models/fsm_equipment.py
  fieldservice_equipment_stock/models/product_template.py
  fieldservice_equipment_stock/models/stock_move.py
  fieldservice_equipment_stock/models/stock_picking_type.py
  fieldservice_equipment_stock/models/stock_production_lot.py
  fieldservice_equipment_stock/readme/CONFIGURE.rst
  fieldservice_equipment_stock/readme/CONTRIBUTORS.rst
  fieldservice_equipment_stock/readme/CREDITS.rst
  fieldservice_equipment_stock/readme/DESCRIPTION.rst
  fieldservice_equipment_stock/readme/ROADMAP.rst
  fieldservice_equipment_stock/readme/USAGE.rst
  fieldservice_equipment_stock/security/ir.model.access.csv
  fieldservice_equipment_stock/static/description/icon.png
  fieldservice_equipment_stock/static/description/index.html
  fieldservice_equipment_stock/tests/__init__.py
  fieldservice_equipment_stock/tests/test_fsm_equipment.py
  fieldservice_equipment_stock/tests/test_stock_move.py
  fieldservice_equipment_stock/views/fsm_equipment.xml
  fieldservice_equipment_stock/views/product_template.xml
  fieldservice_equipment_stock/views/stock_picking_type.xml
  fieldservice_equipment_stock/views/stock_production_lot.xml
  setup/fieldservice_equipment_stock/odoo/addons/fieldservice_equipment_stock
  setup/fieldservice_equipment_stock/setup.py
Labels: migration, bot is merging ⏳, Blocked by dependency

#991 [14.0] [FIX] fieldservice_google_map
  fieldservice/views/fsm_order.xml
  fieldservice_google_map/views/fsm_order.xml
Labels: bug, needs review, approved, bot is merging ⏳

#989 [15.0][MIG] fieldservice_repair
  fieldservice_repair/README.rst
  fieldservice_repair/__init__.py
  fieldservice_repair/__manifest__.py
  fieldservice_repair/data/fsm_order_type.xml
  fieldservice_repair/i18n/de.po
  fieldservice_repair/i18n/es.po
  fieldservice_repair/i18n/es_AR.po
  fieldservice_repair/i18n/fieldservice_repair.pot
  fieldservice_repair/i18n/it.po
  fieldservice_repair/i18n/pt_BR.po
  fieldservice_repair/models/__init__.py
  fieldservice_repair/models/fsm_order.py
  fieldservice_repair/models/fsm_order_type.py
  fieldservice_repair/readme/CONFIGURE.rst
  fieldservice_repair/readme/CONTRIBUTORS.rst
  fieldservice_repair/readme/CREDITS.rst
  fieldservice_repair/readme/DESCRIPTION.rst
  fieldservice_repair/readme/INSTALL.rst
  fieldservice_repair/readme/ROADMAP.rst
  fieldservice_repair/readme/USAGE.rst
  fieldservice_repair/static/description/icon.png
  fieldservice_repair/static/description/index.html
  fieldservice_repair/tests/__init__.py
  fieldservice_repair/tests/test_fsm_repair.py
  fieldservice_repair/views/fsm_order_view.xml
  setup/fieldservice_repair/odoo/addons/fieldservice_repair
  setup/fieldservice_repair/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, Blocked by dependency

#995 [15.0][MIG] fieldservice_partner_multi_relation
  fieldservice_partner_multi_relation/README.rst
  fieldservice_partner_multi_relation/__init__.py
  fieldservice_partner_multi_relation/__manifest__.py
  fieldservice_partner_multi_relation/data/demo.xml
  fieldservice_partner_multi_relation/i18n/de.po
  fieldservice_partner_multi_relation/i18n/es.po
  fieldservice_partner_multi_relation/i18n/es_AR.po
  fieldservice_partner_multi_relation/i18n/es_CL.po
  fieldservice_partner_multi_relation/i18n/fieldservice_partner_multi_relation.pot
  fieldservice_partner_multi_relation/i18n/it.po
  fieldservice_partner_multi_relation/i18n/pt_BR.po
  fieldservice_partner_multi_relation/models/__init__.py
  fieldservice_partner_multi_relation/models/fsm_location.py
  fieldservice_partner_multi_relation/models/res_partner.py
  fieldservice_partner_multi_relation/models/res_partner_relation_all.py
  fieldservice_partner_multi_relation/models/res_partner_relation_type.py
  fieldservice_partner_multi_relation/readme/CONFIGURE.rst
  fieldservice_partner_multi_relation/readme/CONTRIBUTORS.rst
  fieldservice_partner_multi_relation/readme/CREDITS.rst
  fieldservice_partner_multi_relation/readme/DESCRIPTION.rst
  fieldservice_partner_multi_relation/readme/INSTALL.rst
  fieldservice_partner_multi_relation/readme/ROADMAP.rst
  fieldservice_partner_multi_relation/readme/USAGE.rst
  fieldservice_partner_multi_relation/static/description/icon.png
  fieldservice_partner_multi_relation/static/description/index.html
  fieldservice_partner_multi_relation/tests/__init__.py
  fieldservice_partner_multi_relation/tests/test_fieldservice_partner_multi_relation.py
  fieldservice_partner_multi_relation/views/fsm_location.xml
  fieldservice_partner_multi_relation/views/menu.xml
  setup/fieldservice_partner_multi_relation/odoo/addons/fieldservice_partner_multi_relation
  setup/fieldservice_partner_multi_relation/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#993 [16.0][MIG] fieldservice_stock
  fieldservice_stock/README.rst
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/data/fsm_stock_data.xml
  fieldservice_stock/i18n/de.po
  fieldservice_stock/i18n/es.po
  fieldservice_stock/i18n/es_AR.po
  fieldservice_stock/i18n/es_CL.po
  fieldservice_stock/i18n/fieldservice_stock.pot
  fieldservice_stock/i18n/it.po
  fieldservice_stock/i18n/pt_BR.po
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/fsm_wizard.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/res_territory.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_picking.py
  fieldservice_stock/models/stock_rule.py
  fieldservice_stock/readme/CONFIGURE.rst
  fieldservice_stock/readme/CONTRIBUTORS.rst
  fieldservice_stock/readme/CREDITS.rst
  fieldservice_stock/readme/DESCRIPTION.rst
  fieldservice_stock/readme/INSTALL.rst
  fieldservice_stock/readme/ROADMAP.rst
  fieldservice_stock/readme/USAGE.rst
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock/static/description/icon.png
  fieldservice_stock/static/description/index.html
  fieldservice_stock/tests/__init__.py
  fieldservice_stock/tests/test_fsm_stock.py
  fieldservice_stock/tests/test_fsm_wizard.py
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/res_territory.xml
  fieldservice_stock/views/stock.xml
  fieldservice_stock/views/stock_picking.xml
  setup/fieldservice_stock/odoo/addons/fieldservice_stock
  setup/fieldservice_stock/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1004 [FIX] fieldservice, base_territory
  base_territory/__manifest__.py
  fieldservice/__manifest__.py
Labels: enhancement, needs review

#1001 [FIX] [15.0] fieldservice_skill: test
  fieldservice_skill/tests/test_fsm_skill.py
Labels: bug, needs review, approved, bot is merging ⏳

#1003 [FIX] [15.0] fieldservice_stage_validation: test
  fieldservice_stage_validation/tests/test_fsm_stage_validation.py
Labels: bug, needs review, approved, bot is merging ⏳

#999 [14.0] [IMP] fieldservice_account: Tests
  fieldservice_account/models/account_move.py
  fieldservice_account/tests/test_fsm_account.py
Labels: enhancement, approved, bot is merging ⏳

#998 [IMP] fieldservice_account: Tests
  fieldservice_account/__manifest__.py
  fieldservice_account/tests/test_fsm_account.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#698 [14.0] [MIG] fieldservice_change_management
  fieldservice_change_management/README.rst
  fieldservice_change_management/__init__.py
  fieldservice_change_management/__manifest__.py
  fieldservice_change_management/data/change_log_impact.xml
  fieldservice_change_management/data/change_log_stage.xml
  fieldservice_change_management/data/change_log_type.xml
  fieldservice_change_management/data/ir_sequence.xml
  fieldservice_change_management/i18n/es_AR.po
  fieldservice_change_management/i18n/fieldservice_change_management.pot
  fieldservice_change_management/i18n/pt_BR.po
  fieldservice_change_management/i18n/pt_PT.po
  fieldservice_change_management/models/__init__.py
  fieldservice_change_management/models/change_log.py
  fieldservice_change_management/models/change_log_impact.py
  fieldservice_change_management/models/change_log_stage.py
  fieldservice_change_management/models/change_log_tags.py
  fieldservice_change_management/models/change_log_type.py
  fieldservice_change_management/models/fsm_location.py
  fieldservice_change_management/readme/CONFIGURE.rst
  fieldservice_change_management/readme/CONTRIBUTORS.rst
  fieldservice_change_management/readme/CREDITS.rst
  fieldservice_change_management/readme/DESCRIPTION.rst
  fieldservice_change_management/readme/INSTALL.rst
  fieldservice_change_management/readme/ROADMAP.rst
  fieldservice_change_management/readme/USAGE.rst
  fieldservice_change_management/report/change_log_reports.xml
  fieldservice_change_management/security/ir.model.access.csv
  fieldservice_change_management/security/security.xml
  fieldservice_change_management/static/description/icon.png
  fieldservice_change_management/static/description/icon.svg
  fieldservice_change_management/static/description/index.html
  fieldservice_change_management/tests/__init__.py
  fieldservice_change_management/tests/test_fsm_change_logs.py
  fieldservice_change_management/views/change_log.xml
  fieldservice_change_management/views/change_log_impact.xml
  fieldservice_change_management/views/change_log_stage.xml
  fieldservice_change_management/views/change_log_tags.xml
  fieldservice_change_management/views/change_log_type.xml
  fieldservice_change_management/views/fsm_location.xml
  setup/fieldservice_change_management/odoo/addons/fieldservice_change_management
  setup/fieldservice_change_management/setup.py
Labels: needs review, migration, bot is merging ⏳

#702 [14.0][MIG] fieldservice_fleet
  fieldservice_fleet/README.rst
  fieldservice_fleet/__init__.py
  fieldservice_fleet/__manifest__.py
  fieldservice_fleet/hooks.py
  fieldservice_fleet/i18n/es.po
  fieldservice_fleet/i18n/es_CL.po
  fieldservice_fleet/i18n/fieldservice_fleet.pot
  fieldservice_fleet/i18n/pt_BR.po
  fieldservice_fleet/models/__init__.py
  fieldservice_fleet/models/fleet_vehicle.py
  fieldservice_fleet/models/fsm_vehicle.py
  fieldservice_fleet/readme/CONFIGURE.rst
  fieldservice_fleet/readme/CONTRIBUTORS.rst
  fieldservice_fleet/readme/CREDITS.rst
  fieldservice_fleet/readme/DESCRIPTION.rst
  fieldservice_fleet/readme/INSTALL.rst
  fieldservice_fleet/readme/ROADMAP.rst
  fieldservice_fleet/readme/USAGE.rst
  fieldservice_fleet/security/ir.model.access.csv
  fieldservice_fleet/static/description/icon.png
  fieldservice_fleet/static/description/index.html
  fieldservice_fleet/tests/__init__.py
  fieldservice_fleet/tests/test_fsm_fleet_wizard.py
  fieldservice_fleet/views/fleet_vehicle.xml
  fieldservice_fleet/views/fsm_vehicle.xml
  fieldservice_fleet/wizard/__init__.py
  fieldservice_fleet/wizard/fsm_fleet_wizard.py
  fieldservice_fleet/wizard/fsm_fleet_wizard.xml
  fieldservice_vehicle_stock/tests/test_fsm_order.py
  fieldservice_vehicle_stock/tests/test_product_putaway.py
  fieldservice_vehicle_stock/tests/test_stock_picking.py
  setup/fieldservice_fleet/odoo/addons/fieldservice_fleet
  setup/fieldservice_fleet/setup.py
Labels: needs review, migration, bot is merging ⏳

#813 [14.0][MIG] fieldservice_stock_request
  fieldservice_stock_request/README.rst
  fieldservice_stock_request/__init__.py
  fieldservice_stock_request/__manifest__.py
  fieldservice_stock_request/i18n/fieldservice_stock_request.pot
  fieldservice_stock_request/i18n/pt_BR.po
  fieldservice_stock_request/models/__init__.py
  fieldservice_stock_request/models/fsm_order.py
  fieldservice_stock_request/models/stock_move_line.py
  fieldservice_stock_request/models/stock_request.py
  fieldservice_stock_request/models/stock_request_order.py
  fieldservice_stock_request/readme/CONFIGURE.rst
  fieldservice_stock_request/readme/CONTRIBUTORS.rst
  fieldservice_stock_request/readme/CREDITS.rst
  fieldservice_stock_request/readme/DESCRIPTION.rst
  fieldservice_stock_request/readme/ROADMAP.rst
  fieldservice_stock_request/readme/USAGE.rst
  fieldservice_stock_request/security/ir.model.access.csv
  fieldservice_stock_request/static/description/icon.png
  fieldservice_stock_request/static/description/index.html
  fieldservice_stock_request/tests/__init__.py
  fieldservice_stock_request/tests/test_fsm_stock_request.py
  fieldservice_stock_request/views/fsm_order.xml
  fieldservice_stock_request/views/stock.xml
  fieldservice_stock_request/views/stock_request.xml
  fieldservice_stock_request/views/stock_request_order.xml
  setup/fieldservice_stock_request/odoo/addons/fieldservice_stock_request
  setup/fieldservice_stock_request/setup.py
Labels: needs review, migration, bot is merging ⏳

#1006 [15.0][FIX] fieldservice: FSM Category parent
  fieldservice/models/fsm_category.py
  fieldservice/tests/test_fsm_category.py
Labels: bug, enhancement, approved, bot is merging ⏳

#823 [14.0][MIG] fieldservice_stock_account
  fieldservice_stock_account/README.rst
  fieldservice_stock_account/__init__.py
  fieldservice_stock_account/__manifest__.py
  fieldservice_stock_account/i18n/de.po
  fieldservice_stock_account/i18n/es.po
  fieldservice_stock_account/i18n/es_CL.po
  fieldservice_stock_account/i18n/fieldservice_stock_account.pot
  fieldservice_stock_account/i18n/pt_BR.po
  fieldservice_stock_account/models/__init__.py
  fieldservice_stock_account/models/fsm_order.py
  fieldservice_stock_account/readme/CONTRIBUTORS.rst
  fieldservice_stock_account/readme/CREDITS.rst
  fieldservice_stock_account/readme/DESCRIPTION.rst
  fieldservice_stock_account/readme/USAGE.rst
  fieldservice_stock_account/static/description/icon.png
  fieldservice_stock_account/static/description/index.html
  fieldservice_stock_account/tests/__init__.py
  fieldservice_stock_account/tests/test_fsm_stock_account.py
  setup/fieldservice_stock_account/odoo/addons/fieldservice_stock_account
  setup/fieldservice_stock_account/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#814 [14.0][MIG] fieldservice_vehicle_stock_request
  fieldservice_vehicle_stock_request/README.rst
  fieldservice_vehicle_stock_request/__init__.py
  fieldservice_vehicle_stock_request/__manifest__.py
  fieldservice_vehicle_stock_request/i18n/fieldservice_vehicle_stock_request.pot
  fieldservice_vehicle_stock_request/i18n/pt_BR.po
  fieldservice_vehicle_stock_request/models/__init__.py
  fieldservice_vehicle_stock_request/models/stock_request.py
  fieldservice_vehicle_stock_request/readme/CONTRIBUTORS.rst
  fieldservice_vehicle_stock_request/readme/CREDITS.rst
  fieldservice_vehicle_stock_request/readme/DESCRIPTION.rst
  fieldservice_vehicle_stock_request/readme/ROADMAP.rst
  fieldservice_vehicle_stock_request/static/description/icon.png
  fieldservice_vehicle_stock_request/static/description/index.html
  fieldservice_vehicle_stock_request/tests/__init__.py
  fieldservice_vehicle_stock_request/tests/test_fsm_vehicle_stock_request.py
  fieldservice_vehicle_stock_request/views/fsm_order.xml
  setup/fieldservice_vehicle_stock_request/odoo/addons/fieldservice_vehicle_stock_request
  setup/fieldservice_vehicle_stock_request/setup.py
Labels: needs review, migration, bot is merging ⏳

#770 [14.0] [MIG] fieldservice_google_marker_icon_picker
  fieldservice_google_marker_icon_picker/README.rst
  fieldservice_google_marker_icon_picker/__init__.py
  fieldservice_google_marker_icon_picker/__manifest__.py
  fieldservice_google_marker_icon_picker/i18n/es_AR.po
  fieldservice_google_marker_icon_picker/i18n/es_CL.po
  fieldservice_google_marker_icon_picker/i18n/fieldservice_google_marker_icon_picker.pot
  fieldservice_google_marker_icon_picker/i18n/pt_BR.po
  fieldservice_google_marker_icon_picker/i18n/pt_PT.po
  fieldservice_google_marker_icon_picker/models/__init__.py
  fieldservice_google_marker_icon_picker/models/fsm_stage.py
  fieldservice_google_marker_icon_picker/readme/CONFIGURE.rst
  fieldservice_google_marker_icon_picker/readme/CONTRIBUTORS.rst
  fieldservice_google_marker_icon_picker/readme/CREDITS.rst
  fieldservice_google_marker_icon_picker/readme/DESCRIPTION.rst
  fieldservice_google_marker_icon_picker/readme/INSTALL.rst
  fieldservice_google_marker_icon_picker/readme/USAGE.rst
  fieldservice_google_marker_icon_picker/static/description/icon.png
  fieldservice_google_marker_icon_picker/static/description/index.html
  fieldservice_google_marker_icon_picker/tests/__init__.py
  fieldservice_google_marker_icon_picker/tests/test_fsm_google_marker.py
  fieldservice_google_marker_icon_picker/views/fsm_stage.xml
  requirements.txt
  setup/fieldservice_google_marker_icon_picker/odoo/addons/fieldservice_google_marker_icon_picker
  setup/fieldservice_google_marker_icon_picker/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#816 [14.0][MIG] fieldservice_stock_account_analytic
  fieldservice_stock_account_analytic/README.rst
  fieldservice_stock_account_analytic/__init__.py
  fieldservice_stock_account_analytic/__manifest__.py
  fieldservice_stock_account_analytic/i18n/de.po
  fieldservice_stock_account_analytic/i18n/es.po
  fieldservice_stock_account_analytic/i18n/es_CL.po
  fieldservice_stock_account_analytic/i18n/fieldservice_stock_account_analytic.pot
  fieldservice_stock_account_analytic/i18n/pt_BR.po
  fieldservice_stock_account_analytic/i18n/pt_PT.po
  fieldservice_stock_account_analytic/models/__init__.py
  fieldservice_stock_account_analytic/models/fsm_order.py
  fieldservice_stock_account_analytic/models/stock_request.py
  fieldservice_stock_account_analytic/readme/CONTRIBUTORS.rst
  fieldservice_stock_account_analytic/readme/DESCRIPTION.rst
  fieldservice_stock_account_analytic/readme/ROADMAP.rst
  fieldservice_stock_account_analytic/readme/USAGE.rst
  fieldservice_stock_account_analytic/static/description/icon.png
  fieldservice_stock_account_analytic/static/description/index.html
  fieldservice_stock_account_analytic/tests/__init__.py
  fieldservice_stock_account_analytic/tests/test_fsm_stock_account_analytic.py
  setup/fieldservice_stock_account_analytic/odoo/addons/fieldservice_stock_account_analytic
  setup/fieldservice_stock_account_analytic/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1007 [15.0][MIG] fieldservice_location_builder
  .pre-commit-config.yaml
  fieldservice_location_builder/README.rst
  fieldservice_location_builder/__init__.py
  fieldservice_location_builder/__manifest__.py
  fieldservice_location_builder/i18n/de.po
  fieldservice_location_builder/i18n/es.po
  fieldservice_location_builder/i18n/es_CL.po
  fieldservice_location_builder/i18n/fieldservice_location_builder.pot
  fieldservice_location_builder/i18n/pt_BR.po
  fieldservice_location_builder/readme/CONTRIBUTORS.rst
  fieldservice_location_builder/readme/DESCRIPTION.rst
  fieldservice_location_builder/readme/ROADMAP.rst
  fieldservice_location_builder/readme/USAGE.rst
  fieldservice_location_builder/security/ir.model.access.csv
  fieldservice_location_builder/static/description/icon.png
  fieldservice_location_builder/static/description/index.html
  fieldservice_location_builder/tests/__init__.py
  fieldservice_location_builder/tests/test_fsm_location_builder.py
  fieldservice_location_builder/wizard/__init__.py
  fieldservice_location_builder/wizard/fsm_location_builder_wizard.py
  fieldservice_location_builder/wizard/fsm_location_builder_wizard.xml
  fieldservice_location_builder/wizard/fsm_location_level.py
  fieldservice_location_builder/wizard/fsm_location_level.xml
  setup/fieldservice_location_builder/odoo/addons/fieldservice_location_builder
  setup/fieldservice_location_builder/setup.py
Labels: needs review, migration, bot is merging ⏳

#1010 [REF] copier update
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bug, needs review
