Repository OCA/field-service, pull requests merged in 2022-03, with the labels that each got.

#766 [14.0][FIX] fixed object has no attribute 'group_manage_vendor_price' error
  fieldservice/models/res_config_settings.py
Labels: bug, bot is merging ⏳

#876 [15.0][MIG] base_territory
  base_territory/README.rst
  base_territory/__init__.py
  base_territory/__manifest__.py
  base_territory/demo/base_territory_demo.xml
  base_territory/i18n/base_territory.pot
  base_territory/i18n/es_AR.po
  base_territory/i18n/it.po
  base_territory/i18n/pt_BR.po
  base_territory/i18n/tr.po
  base_territory/models/__init__.py
  base_territory/models/res_branch.py
  base_territory/models/res_country.py
  base_territory/models/res_district.py
  base_territory/models/res_region.py
  base_territory/models/res_territory.py
  base_territory/readme/CONTRIBUTORS.rst
  base_territory/readme/CREDITS.rst
  base_territory/readme/DESCRIPTION.rst
  base_territory/readme/USAGE.rst
  base_territory/security/ir.model.access.csv
  base_territory/static/description/icon.png
  base_territory/static/description/index.html
  base_territory/views/menu.xml
  base_territory/views/res_branch.xml
  base_territory/views/res_country.xml
  base_territory/views/res_district.xml
  base_territory/views/res_region.xml
  base_territory/views/res_territory.xml
  setup/base_territory/odoo/addons/base_territory
  setup/base_territory/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#912 [MIG] fieldservice_route: Migration to v13
  fieldservice/security/ir.model.access.csv
  fieldservice/security/ir_rule.xml
  fieldservice/security/res_groups.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/menu.xml
  fieldservice/views/res_partner.xml
  fieldservice_route/README.rst
  fieldservice_route/__init__.py
  fieldservice_route/__manifest__.py
  fieldservice_route/data/fsm_route_day_data.xml
  fieldservice_route/data/fsm_stage_data.xml
  fieldservice_route/data/ir_sequence.xml
  fieldservice_route/i18n/es_CL.po
  fieldservice_route/i18n/fieldservice_route.pot
  fieldservice_route/i18n/it.po
  fieldservice_route/i18n/pt_BR.po
  fieldservice_route/i18n/pt_PT.po
  fieldservice_route/models/__init__.py
  fieldservice_route/models/fsm_location.py
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route.py
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/models/fsm_stage.py
  fieldservice_route/models/res_partner.py
  fieldservice_route/readme/CONFIGURE.rst
  fieldservice_route/readme/CONTRIBUTORS.rst
  fieldservice_route/readme/CREDITS.rst
  fieldservice_route/readme/DESCRIPTION.rst
  fieldservice_route/readme/USAGE.rst
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/static/description/icon.png
  fieldservice_route/static/description/index.html
  fieldservice_route/tests/__init__.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_location.xml
  fieldservice_route/views/fsm_order.xml
  fieldservice_route/views/fsm_route.xml
  fieldservice_route/views/fsm_route_day.xml
  fieldservice_route/views/fsm_route_dayroute.xml
  fieldservice_route/views/menu.xml
  fieldservice_route/views/res_partner_views.xml
  setup/fieldservice_route/odoo/addons/fieldservice_route
  setup/fieldservice_route/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#867 [14.0][MIG] fieldservice_sale_recurring
  fieldservice_sale_recurring/README.rst
  fieldservice_sale_recurring/__init__.py
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/i18n/de.po
  fieldservice_sale_recurring/i18n/es.po
  fieldservice_sale_recurring/i18n/es_CL.po
  fieldservice_sale_recurring/i18n/fieldservice_sale_recurring.pot
  fieldservice_sale_recurring/i18n/it.po
  fieldservice_sale_recurring/i18n/pt_BR.po
  fieldservice_sale_recurring/models/__init__.py
  fieldservice_sale_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/product_template.py
  fieldservice_sale_recurring/models/sale_order.py
  fieldservice_sale_recurring/models/sale_order_line.py
  fieldservice_sale_recurring/readme/CONFIGURE.rst
  fieldservice_sale_recurring/readme/CONTRIBUTORS.rst
  fieldservice_sale_recurring/readme/DESCRIPTION.rst
  fieldservice_sale_recurring/readme/INSTALL.rst
  fieldservice_sale_recurring/readme/ROADMAP.rst
  fieldservice_sale_recurring/readme/USAGE.rst
  fieldservice_sale_recurring/security/ir.model.access.csv
  fieldservice_sale_recurring/static/description/description/icon.png
  fieldservice_sale_recurring/static/description/description/index.html
  fieldservice_sale_recurring/static/description/icon.png
  fieldservice_sale_recurring/static/description/index.html
  fieldservice_sale_recurring/tests/__init__.py
  fieldservice_sale_recurring/tests/test_fsm_sale_recurring.py
  fieldservice_sale_recurring/views/fsm_recurring.xml
  fieldservice_sale_recurring/views/product_template.xml
  fieldservice_sale_recurring/views/sale_order.xml
Labels: bot is merging ⏳

#919 [14.0] [FIX] fieldservice_recurring: Attempt to fix daylight saving time jumps
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/tests/test_fsm_recurring.py
Labels: approved, bot is merging ⏳

#914 [13.0][FIX] fieldservice_sale - confirm quotation with section or note lines
  fieldservice_sale/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#920 [14.0] Improve FSM Stock Picking Views
  fieldservice_stock/__manifest__.py
  fieldservice_stock/views/stock_picking.xml
  fieldservice_vehicle_stock/__manifest__.py
  fieldservice_vehicle_stock/views/stock_picking.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳
