Repository OCA/field-service, pull requests merged in 2022-10, with the labels that each got.

#955 [FIX] fieldservice_geoengine: Recompute geopoint if either latitude or longitude didn't change
  fieldservice_geoengine/models/fsm_location.py
Labels: bug, approved, bot is merging ⏳

#960 [14.0] [FIX] fieldservice_recurring: Default company
  fieldservice_recurring/models/fsm_recurring.py
Labels: approved, ready to merge, bot is merging ⏳

#959 [FIX] fieldservice_calendar: Attendees list on creation
  fieldservice_calendar/models/fsm_order.py
Labels: approved, ready to merge, bot is merging ⏳

#957 [FIX] fieldservice: Duplicate/copy method
  fieldservice/models/fsm_equipment.py
  fieldservice/tests/test_fsm_equipment.py
Labels: approved, ready to merge, bot is merging ⏳

#949 [14.0][IMP] fieldservice: add person_id in orders view
  fieldservice/views/fsm_order.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#962 [IMP] fieldservice_recurring: Use location_id tz
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_recurring.py
Labels: enhancement, approved, bot is merging ⏳

#966 [MIG] base_territory
  base_territory/README.rst
  base_territory/__init__.py
  base_territory/__manifest__.py
  base_territory/demo/base_territory_demo.xml
  base_territory/i18n/base_territory.pot
  base_territory/i18n/es_AR.po
  base_territory/i18n/it.po
  base_territory/i18n/pt_BR.po
  base_territory/i18n/tr.po
  base_territory/models/__init__.py
  base_territory/models/res_branch.py
  base_territory/models/res_country.py
  base_territory/models/res_district.py
  base_territory/models/res_region.py
  base_territory/models/res_territory.py
  base_territory/readme/CONTRIBUTORS.rst
  base_territory/readme/CREDITS.rst
  base_territory/readme/DESCRIPTION.rst
  base_territory/readme/USAGE.rst
  base_territory/security/ir.model.access.csv
  base_territory/static/description/icon.png
  base_territory/static/description/index.html
  base_territory/views/menu.xml
  base_territory/views/res_branch.xml
  base_territory/views/res_country.xml
  base_territory/views/res_district.xml
  base_territory/views/res_region.xml
  base_territory/views/res_territory.xml
  setup/base_territory/odoo/addons/base_territory
  setup/base_territory/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#931 [FIX] fieldservice_sale: Set FSM Template group by default
  fieldservice_sale/__manifest__.py
  fieldservice_sale/data/fsm_template_group.xml
  fieldservice_sale/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#807 [FIX][12.0]Fix gantt view error with date_range
  fieldservice/static/src/js/fsm_gantt.js
  fieldservice/static/src/js/fsm_gantt_person_filter.js
  fieldservice/static/src/xml/fsm_gantt_person_filter.xml
Labels: bug, bot is merging ⏳

#898 [15.0][MIG] fieldservice_activity
  fieldservice_activity/README.rst
  fieldservice_activity/__init__.py
  fieldservice_activity/__manifest__.py
  fieldservice_activity/i18n/es_AR.po
  fieldservice_activity/i18n/es_CL.po
  fieldservice_activity/i18n/fieldservice_activity.pot
  fieldservice_activity/i18n/it.po
  fieldservice_activity/i18n/pt_BR.po
  fieldservice_activity/i18n/pt_PT.po
  fieldservice_activity/models/__init__.py
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/models/fsm_template.py
  fieldservice_activity/readme/CONFIGURE.rst
  fieldservice_activity/readme/CONTRIBUTORS.rst
  fieldservice_activity/readme/CREDITS.rst
  fieldservice_activity/readme/DESCRIPTION.rst
  fieldservice_activity/readme/USAGE.rst
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/static/description/icon.png
  fieldservice_activity/static/description/index.html
  fieldservice_activity/tests/__init__.py
  fieldservice_activity/tests/test_fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
  setup/fieldservice_activity/odoo/addons/fieldservice_activity
  setup/fieldservice_activity/setup.py
Labels: migration, bot is merging ⏳, Blocked by dependency

#886 [15.0][MIG] fieldservice_crm
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/i18n/de.po
  fieldservice_crm/i18n/es_AR.po
  fieldservice_crm/i18n/es_CL.po
  fieldservice_crm/i18n/fieldservice_crm.pot
  fieldservice_crm/i18n/pt_BR.po
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/readme/CONFIGURE.rst
  fieldservice_crm/readme/CONTRIBUTORS.rst
  fieldservice_crm/readme/CREDITS.rst
  fieldservice_crm/readme/DESCRIPTION.rst
  fieldservice_crm/readme/INSTALL.rst
  fieldservice_crm/readme/ROADMAP.rst
  fieldservice_crm/readme/USAGE.rst
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/static/description/index.html
  fieldservice_crm/tests/__init__.py
  fieldservice_crm/tests/test_fsm_crm.py
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
  setup/fieldservice_crm/odoo/addons/fieldservice_crm
  setup/fieldservice_crm/setup.py
Labels: migration, bot is merging ⏳, Blocked by dependency

#906 [15.0][MIG] fieldservice_substatus
  fieldservice_substatus/README.rst
  fieldservice_substatus/__init__.py
  fieldservice_substatus/__manifest__.py
  fieldservice_substatus/data/fsm_stage.xml
  fieldservice_substatus/data/fsm_stage_status.xml
  fieldservice_substatus/data/mail_data.xml
  fieldservice_substatus/i18n/de.po
  fieldservice_substatus/i18n/es.po
  fieldservice_substatus/i18n/es_AR.po
  fieldservice_substatus/i18n/es_CL.po
  fieldservice_substatus/i18n/fieldservice_substatus.pot
  fieldservice_substatus/i18n/it.po
  fieldservice_substatus/i18n/pt_BR.po
  fieldservice_substatus/models/__init__.py
  fieldservice_substatus/models/fsm_order.py
  fieldservice_substatus/models/fsm_stage.py
  fieldservice_substatus/models/fsm_stage_status.py
  fieldservice_substatus/readme/CONFIGURE.rst
  fieldservice_substatus/readme/CONTRIBUTORS.rst
  fieldservice_substatus/readme/CREDITS.rst
  fieldservice_substatus/readme/DESCRIPTION.rst
  fieldservice_substatus/readme/INSTALL.rst
  fieldservice_substatus/readme/ROADMAP.rst
  fieldservice_substatus/readme/USAGE.rst
  fieldservice_substatus/security/ir.model.access.csv
  fieldservice_substatus/static/description/icon.png
  fieldservice_substatus/static/description/index.html
  fieldservice_substatus/tests/__init__.py
  fieldservice_substatus/tests/test_fsm_substatus.py
  fieldservice_substatus/views/fsm_order.xml
  fieldservice_substatus/views/fsm_stage.xml
  fieldservice_substatus/views/fsm_stage_status.xml
  setup/fieldservice_substatus/odoo/addons/fieldservice_substatus
  setup/fieldservice_substatus/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#926 [14.0][IMP] fieldservice_recurring: refactor stages
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/migrations/14.0.2.0.0/pre-migration.py
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_team.py
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_team.xml
Labels: approved, bot is merging ⏳

#669 [12.0][IMP] fieldservice_maintenance: Convert Maintenance Equipment To FSM
  fieldservice_maintenance/__init__.py
  fieldservice_maintenance/__manifest__.py
  fieldservice_maintenance/models/fsm_equipment.py
  fieldservice_maintenance/models/maintenance_equipment.py
  fieldservice_maintenance/views/maintenance_equipment_view.xml
  fieldservice_maintenance/wizard/__init__.py
  fieldservice_maintenance/wizard/maintenance_equipment_wizard.py
  fieldservice_maintenance/wizard/maintenance_equipment_wizard.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#817 [12.0][IMP] fieldservice: Add settings for automatic calculation of request_late field of fsm.order
  fieldservice/models/fsm_order.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#974 [FIX] fieldservice_agreement, fieldservice_vehicle_stock: pre-commit errors
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  fieldservice_account_payment/__manifest__.py
  fieldservice_agreement/views/agreement_view.xml
  fieldservice_change_management/__manifest__.py
  fieldservice_maintenance/models/maintenance_equipment.py
  fieldservice_maintenance/wizard/maintenance_equipment_wizard.py
  fieldservice_partner_multi_relation/__manifest__.py
  fieldservice_stage_server_action/__manifest__.py
  requirements.txt
Labels: bug, needs review

#968 [15.0] [MIG] fieldservice_isp_flow
  fieldservice_isp_flow/README.rst
  fieldservice_isp_flow/__init__.py
  fieldservice_isp_flow/__manifest__.py
  fieldservice_isp_flow/data/fsm_stage.xml
  fieldservice_isp_flow/i18n/de.po
  fieldservice_isp_flow/i18n/es.po
  fieldservice_isp_flow/i18n/es_AR.po
  fieldservice_isp_flow/i18n/es_CL.po
  fieldservice_isp_flow/i18n/fieldservice_isp_flow.pot
  fieldservice_isp_flow/i18n/pt_BR.po
  fieldservice_isp_flow/models/__init__.py
  fieldservice_isp_flow/models/fsm_order.py
  fieldservice_isp_flow/readme/CONFIGURE.rst
  fieldservice_isp_flow/readme/CONTRIBUTORS.rst
  fieldservice_isp_flow/readme/CREDITS.rst
  fieldservice_isp_flow/readme/DESCRIPTION.rst
  fieldservice_isp_flow/readme/ROADMAP.rst
  fieldservice_isp_flow/readme/USAGE.rst
  fieldservice_isp_flow/static/description/icon.png
  fieldservice_isp_flow/static/description/index.html
  fieldservice_isp_flow/tests/__init__.py
  fieldservice_isp_flow/tests/test_fsm_isp_flow.py
  fieldservice_isp_flow/views/fsm_order.xml
  setup/fieldservice_isp_flow/odoo/addons/fieldservice_isp_flow
  setup/fieldservice_isp_flow/setup.py
Labels: needs review, migration

#899 [15.0][MIG] fieldservice_calendar
  fieldservice_calendar/README.rst
  fieldservice_calendar/__init__.py
  fieldservice_calendar/__manifest__.py
  fieldservice_calendar/i18n/es_AR.po
  fieldservice_calendar/i18n/fieldservice_calendar.pot
  fieldservice_calendar/i18n/pt_BR.po
  fieldservice_calendar/models/__init__.py
  fieldservice_calendar/models/calendar.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_calendar/models/fsm_team.py
  fieldservice_calendar/readme/CONFIGURE.rst
  fieldservice_calendar/readme/CONTRIBUTORS.rst
  fieldservice_calendar/readme/DESCRIPTION.rst
  fieldservice_calendar/static/description/icon.png
  fieldservice_calendar/static/description/index.html
  fieldservice_calendar/tests/__init__.py
  fieldservice_calendar/tests/test_fsm_calendar.py
  fieldservice_calendar/views/fsm_order.xml
  fieldservice_calendar/views/fsm_team.xml
  setup/fieldservice_calendar/odoo/addons/fieldservice_calendar
  setup/fieldservice_calendar/setup.py
Labels: migration, Blocked by dependency

#879 [15.0] [MIG] fieldservice_project
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/i18n/de.po
  fieldservice_project/i18n/es.po
  fieldservice_project/i18n/es_AR.po
  fieldservice_project/i18n/es_CL.po
  fieldservice_project/i18n/fieldservice_project.pot
  fieldservice_project/i18n/pt_BR.po
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/readme/CONTRIBUTORS.rst
  fieldservice_project/readme/CREDITS.rst
  fieldservice_project/readme/DESCRIPTION.rst
  fieldservice_project/readme/ROADMAP.rst
  fieldservice_project/readme/USAGE.rst
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/description/index.html
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/tests/__init__.py
  fieldservice_project/tests/common.py
  fieldservice_project/tests/test_fsm_location.py
  fieldservice_project/tests/test_fsm_order.py
  fieldservice_project/tests/test_project.py
  fieldservice_project/tests/test_project_task.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/fsm_team.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
  setup/fieldservice_project/odoo/addons/fieldservice_project
  setup/fieldservice_project/setup.py
Labels: migration

#954 [FIX] fieldservice_stock
  fieldservice_stock/models/stock_rule.py
Labels: bug

#878 [15.0] [MIG] fieldservice_stage_server_action
  fieldservice_stage_server_action/README.rst
  fieldservice_stage_server_action/__init__.py
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/data/base_automation.xml
  fieldservice_stage_server_action/data/fsm_stage.xml
  fieldservice_stage_server_action/data/ir_server_action.xml
  fieldservice_stage_server_action/i18n/de.po
  fieldservice_stage_server_action/i18n/es.po
  fieldservice_stage_server_action/i18n/es_AR.po
  fieldservice_stage_server_action/i18n/es_CL.po
  fieldservice_stage_server_action/i18n/fieldservice_stage_server_action.pot
  fieldservice_stage_server_action/i18n/pt_BR.po
  fieldservice_stage_server_action/models/__init__.py
  fieldservice_stage_server_action/models/fsm_stage.py
  fieldservice_stage_server_action/readme/CONFIGURE.rst
  fieldservice_stage_server_action/readme/CONTRIBUTORS.rst
  fieldservice_stage_server_action/readme/DESCRIPTION.rst
  fieldservice_stage_server_action/readme/USAGE.rst
  fieldservice_stage_server_action/static/description/icon.png
  fieldservice_stage_server_action/static/description/index.html
  fieldservice_stage_server_action/views/fsm_stage.xml
  setup/fieldservice_stage_server_action/odoo/addons/fieldservice_stage_server_action
  setup/fieldservice_stage_server_action/setup.py
Labels: migration

#905 [15.0][MIG] fieldservice_size
  fieldservice_size/README.rst
  fieldservice_size/__init__.py
  fieldservice_size/__manifest__.py
  fieldservice_size/i18n/es.po
  fieldservice_size/i18n/es_AR.po
  fieldservice_size/i18n/fieldservice_size.pot
  fieldservice_size/i18n/it.po
  fieldservice_size/i18n/pt_BR.po
  fieldservice_size/models/__init__.py
  fieldservice_size/models/fsm_location.py
  fieldservice_size/models/fsm_location_size.py
  fieldservice_size/models/fsm_order.py
  fieldservice_size/models/fsm_size.py
  fieldservice_size/readme/CONFIGURE.rst
  fieldservice_size/readme/CONTRIBUTORS.rst
  fieldservice_size/readme/DESCRIPTION.rst
  fieldservice_size/readme/ROADMAP.rst
  fieldservice_size/readme/USAGE.rst
  fieldservice_size/security/ir.model.access.csv
  fieldservice_size/static/description/icon.png
  fieldservice_size/static/description/index.html
  fieldservice_size/tests/__init__.py
  fieldservice_size/tests/test_fsm_order.py
  fieldservice_size/views/fsm_location.xml
  fieldservice_size/views/fsm_order.xml
  fieldservice_size/views/fsm_size.xml
  fieldservice_size/views/menu.xml
  setup/fieldservice_size/odoo/addons/fieldservice_size
  setup/fieldservice_size/setup.py
Labels: migration, Blocked by dependency

#975 [FIX] fieldservice: views
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
Labels: bug

#884 [MIG][15.0] fieldservice_account
  fieldservice_account/README.rst
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/i18n/de.po
  fieldservice_account/i18n/es.po
  fieldservice_account/i18n/es_AR.po
  fieldservice_account/i18n/es_CL.po
  fieldservice_account/i18n/fieldservice_account.pot
  fieldservice_account/i18n/it.po
  fieldservice_account/i18n/pt_BR.po
  fieldservice_account/i18n/tr.po
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_move.py
  fieldservice_account/models/account_move_line.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/readme/CONFIGURE.rst
  fieldservice_account/readme/CONTRIBUTORS.rst
  fieldservice_account/readme/CREDITS.rst
  fieldservice_account/readme/DESCRIPTION.rst
  fieldservice_account/readme/INSTALL.rst
  fieldservice_account/readme/USAGE.rst
  fieldservice_account/security/ir.model.access.csv
  fieldservice_account/static/description/icon.png
  fieldservice_account/static/description/index.html
  fieldservice_account/tests/__init__.py
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/views/account_move.xml
  fieldservice_account/views/fsm_order.xml
  setup/fieldservice_account/odoo/addons/fieldservice_account
  setup/fieldservice_account/setup.py
Labels: needs fixing, migration, bot is merging ⏳, need tests

#964 [15.0][MIG] fieldservice_route: Migration to 15.0
  fieldservice_route/README.rst
  fieldservice_route/__init__.py
  fieldservice_route/__manifest__.py
  fieldservice_route/data/fsm_route_day_data.xml
  fieldservice_route/data/fsm_stage_data.xml
  fieldservice_route/data/ir_sequence.xml
  fieldservice_route/i18n/es.po
  fieldservice_route/i18n/es_AR.po
  fieldservice_route/i18n/es_CL.po
  fieldservice_route/i18n/fieldservice_route.pot
  fieldservice_route/i18n/pt_BR.po
  fieldservice_route/i18n/pt_PT.po
  fieldservice_route/i18n/tr.po
  fieldservice_route/models/__init__.py
  fieldservice_route/models/fsm_location.py
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route.py
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/models/fsm_stage.py
  fieldservice_route/readme/CONFIGURE.rst
  fieldservice_route/readme/CONTRIBUTORS.rst
  fieldservice_route/readme/CREDITS.rst
  fieldservice_route/readme/DESCRIPTION.rst
  fieldservice_route/readme/USAGE.rst
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/static/description/icon.png
  fieldservice_route/static/description/index.html
  fieldservice_route/tests/__init__.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_location.xml
  fieldservice_route/views/fsm_order.xml
  fieldservice_route/views/fsm_route.xml
  fieldservice_route/views/fsm_route_day.xml
  fieldservice_route/views/fsm_route_dayroute.xml
  fieldservice_route/views/menu.xml
  setup/fieldservice_route/odoo/addons/fieldservice_route
  setup/fieldservice_route/setup.py
Labels: migration, bot is merging ⏳, need tests

#860 [FIX] fieldservice: ValueError: unconverted data remains
  fieldservice/models/fsm_order.py
Labels: bug, needs review, approved, bot is merging ⏳
