Repository OCA/field-service, pull requests merged in 2023-12, with the labels that each got.

#1133 [15.0] Forward Ports from 14.0
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice/models/fsm_stage.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/readme/CONTRIBUTORS.rst
  fieldservice/security/ir.model.access.csv
  fieldservice/security/ir_rule.xml
  fieldservice/security/res_groups.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/menu.xml
  fieldservice/views/res_config_settings.xml
  fieldservice/views/res_partner.xml
Labels: bot is merging ⏳

#1137 [16.0] fieldservice_recurring: Forward ports from 14
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/migrations/16.0.2.0.0/pre-migration.py
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_team.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_order.xml
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_team.xml
Labels: bot is merging ⏳

#1138 [15.0] fieldservice_sale: Forward port from 14
  fieldservice_sale/models/sale_order.py
Labels: bot is merging ⏳

#1147 [16.0] [IMP] fieldservice_account: Forward port from 14,15
  fieldservice_account/__manifest__.py
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_move.py
  fieldservice_account/models/fsm_stage.py
  fieldservice_account/views/fsm_stage.xml
Labels: bot is merging ⏳

#1139 [15.0] fieldservice_sale_recurring: Forward port from 14
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: bot is merging ⏳

#1148 [16.0] fieldservice_sale: Forward port from 14, 15
  fieldservice_sale/models/sale_order.py
Labels: bot is merging ⏳

#1142 [17.0][MIG] fieldservice_route: Migration to 17.0
  fieldservice_route/README.rst
  fieldservice_route/__init__.py
  fieldservice_route/__manifest__.py
  fieldservice_route/data/fsm_route_day_data.xml
  fieldservice_route/data/fsm_stage_data.xml
  fieldservice_route/data/ir_sequence.xml
  fieldservice_route/i18n/es.po
  fieldservice_route/i18n/es_AR.po
  fieldservice_route/i18n/es_CL.po
  fieldservice_route/i18n/fieldservice_route.pot
  fieldservice_route/i18n/it.po
  fieldservice_route/i18n/pt_BR.po
  fieldservice_route/i18n/pt_PT.po
  fieldservice_route/i18n/tr.po
  fieldservice_route/models/__init__.py
  fieldservice_route/models/fsm_location.py
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route.py
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/models/fsm_stage.py
  fieldservice_route/pyproject.toml
  fieldservice_route/readme/CONFIGURE.md
  fieldservice_route/readme/CONTRIBUTORS.md
  fieldservice_route/readme/CREDITS.md
  fieldservice_route/readme/DESCRIPTION.md
  fieldservice_route/readme/USAGE.md
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/static/description/icon.png
  fieldservice_route/static/description/index.html
  fieldservice_route/tests/__init__.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_location.xml
  fieldservice_route/views/fsm_order.xml
  fieldservice_route/views/fsm_route.xml
  fieldservice_route/views/fsm_route_day.xml
  fieldservice_route/views/fsm_route_dayroute.xml
  fieldservice_route/views/menu.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1131 Avoid call to _recompute_tax_lines() after account.move create()
  fieldservice_isp_account/models/fsm_order.py
Labels: approved, ready to merge, bot is merging ⏳
