Repository OCA/field-service, pull requests merged in 2023-11, with the labels that each got.

#1125 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  fieldservice/i18n/fieldservice.pot
  fieldservice_change_management/i18n/fieldservice_change_management.pot
  fieldservice_fleet/i18n/fieldservice_fleet.pot
  fieldservice_recurring/i18n/fieldservice_recurring.pot
  fieldservice_sale_recurring/i18n/fieldservice_sale_recurring.pot
  fieldservice_sale_recurring/models/sale_order_line.py
  fieldservice_stock/views/stock_picking.xml
Labels: help wanted, needs review, bot is merging ⏳

#597 [13.0] [MIG] fieldservice_sale_recurring
  fieldservice_sale_recurring/README.rst
  fieldservice_sale_recurring/__init__.py
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/i18n/de.po
  fieldservice_sale_recurring/i18n/es.po
  fieldservice_sale_recurring/i18n/es_CL.po
  fieldservice_sale_recurring/i18n/fieldservice_sale_recurring.pot
  fieldservice_sale_recurring/i18n/pt_BR.po
  fieldservice_sale_recurring/models/__init__.py
  fieldservice_sale_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/product_template.py
  fieldservice_sale_recurring/models/sale_order.py
  fieldservice_sale_recurring/models/sale_order_line.py
  fieldservice_sale_recurring/readme/CONFIGURE.rst
  fieldservice_sale_recurring/readme/CONTRIBUTORS.rst
  fieldservice_sale_recurring/readme/DESCRIPTION.rst
  fieldservice_sale_recurring/readme/INSTALL.rst
  fieldservice_sale_recurring/readme/ROADMAP.rst
  fieldservice_sale_recurring/readme/USAGE.rst
  fieldservice_sale_recurring/security/ir.model.access.csv
  fieldservice_sale_recurring/static/description/icon.png
  fieldservice_sale_recurring/static/description/index.html
  fieldservice_sale_recurring/views/fsm_recurring.xml
  fieldservice_sale_recurring/views/product_template.xml
  fieldservice_sale_recurring/views/sale_order.xml
Labels: needs review, migration, bot is merging ⏳, no stale

#1102 [14.0] Backport recent fieldservice_sale fixes from 15.0
  fieldservice_sale/models/sale_order.py
Labels: needs review, bot is merging ⏳

#1127 [16.0][MIG] fieldservice_account_analytic
  fieldservice_account_analytic/README.rst
  fieldservice_account_analytic/__init__.py
  fieldservice_account_analytic/__manifest__.py
  fieldservice_account_analytic/data/ir_rule.xml
  fieldservice_account_analytic/demo/fsm_location.xml
  fieldservice_account_analytic/i18n/es.po
  fieldservice_account_analytic/i18n/es_AR.po
  fieldservice_account_analytic/i18n/es_CL.po
  fieldservice_account_analytic/i18n/fieldservice_account_analytic.pot
  fieldservice_account_analytic/i18n/it.po
  fieldservice_account_analytic/i18n/pt_BR.po
  fieldservice_account_analytic/i18n/pt_PT.po
  fieldservice_account_analytic/i18n/tr.po
  fieldservice_account_analytic/init_hook.py
  fieldservice_account_analytic/models/__init__.py
  fieldservice_account_analytic/models/account_move.py
  fieldservice_account_analytic/models/analytic_account.py
  fieldservice_account_analytic/models/fsm_location.py
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_account_analytic/models/res_company.py
  fieldservice_account_analytic/models/res_config_settings.py
  fieldservice_account_analytic/models/res_partner.py
  fieldservice_account_analytic/readme/CONFIGURE.rst
  fieldservice_account_analytic/readme/CONTRIBUTORS.rst
  fieldservice_account_analytic/readme/CREDITS.rst
  fieldservice_account_analytic/readme/DESCRIPTION.rst
  fieldservice_account_analytic/readme/INSTALL.rst
  fieldservice_account_analytic/readme/USAGE.rst
  fieldservice_account_analytic/report/fsm_order_report_template.xml
  fieldservice_account_analytic/security/ir.model.access.csv
  fieldservice_account_analytic/static/description/icon.png
  fieldservice_account_analytic/static/description/index.html
  fieldservice_account_analytic/tests/__init__.py
  fieldservice_account_analytic/tests/test_fsm_account_wizard.py
  fieldservice_account_analytic/views/fsm_location.xml
  fieldservice_account_analytic/views/fsm_order.xml
  fieldservice_account_analytic/views/res_config_settings.xml
  fieldservice_account_analytic/wizard/__init__.py
  fieldservice_account_analytic/wizard/fsm_wizard.py
  setup/fieldservice_account_analytic/odoo/addons/fieldservice_account_analytic
  setup/fieldservice_account_analytic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1126 [16.0][MIG] fieldservice_isp_account
  fieldservice_isp_account/README.rst
  fieldservice_isp_account/__init__.py
  fieldservice_isp_account/__manifest__.py
  fieldservice_isp_account/data/time_products.xml
  fieldservice_isp_account/i18n/es.po
  fieldservice_isp_account/i18n/es_AR.po
  fieldservice_isp_account/i18n/es_CL.po
  fieldservice_isp_account/i18n/fieldservice_isp_account.pot
  fieldservice_isp_account/i18n/it.po
  fieldservice_isp_account/i18n/pt_BR.po
  fieldservice_isp_account/models/__init__.py
  fieldservice_isp_account/models/fsm_order.py
  fieldservice_isp_account/models/fsm_order_cost.py
  fieldservice_isp_account/models/fsm_person.py
  fieldservice_isp_account/readme/CONFIGURE.rst
  fieldservice_isp_account/readme/CONTRIBUTORS.rst
  fieldservice_isp_account/readme/CREDITS.rst
  fieldservice_isp_account/readme/DESCRIPTION.rst
  fieldservice_isp_account/readme/INSTALL.rst
  fieldservice_isp_account/readme/USAGE.rst
  fieldservice_isp_account/security/fsm_order_cost.xml
  fieldservice_isp_account/security/ir.model.access.csv
  fieldservice_isp_account/static/description/icon.png
  fieldservice_isp_account/static/description/index.html
  fieldservice_isp_account/tests/__init__.py
  fieldservice_isp_account/tests/test_isp_account.py
  fieldservice_isp_account/views/account.xml
  fieldservice_isp_account/views/fsm_order.xml
  fieldservice_isp_account/views/fsm_person.xml
  fieldservice_isp_account/views/hr_timesheet.xml
  setup/fieldservice_isp_account/odoo/addons/fieldservice_isp_account
  setup/fieldservice_isp_account/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1135 [16.0] Forward Ports from 14.0
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/security/ir.model.access.csv
  fieldservice/security/ir_rule.xml
  fieldservice/security/res_groups.xml
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_person.xml
  fieldservice/views/menu.xml
  fieldservice/views/res_config_settings.xml
  fieldservice/views/res_partner.xml
Labels: bug, needs review, bot is merging ⏳

#1140 [17.0][MIG] base_territory: Migration to 17.0
  base_territory/README.rst
  base_territory/__init__.py
  base_territory/__manifest__.py
  base_territory/demo/base_territory_demo.xml
  base_territory/i18n/base_territory.pot
  base_territory/i18n/es.po
  base_territory/i18n/es_AR.po
  base_territory/i18n/it.po
  base_territory/i18n/pt_BR.po
  base_territory/i18n/tr.po
  base_territory/models/__init__.py
  base_territory/models/res_branch.py
  base_territory/models/res_country.py
  base_territory/models/res_district.py
  base_territory/models/res_region.py
  base_territory/models/res_territory.py
  base_territory/pyproject.toml
  base_territory/readme/CONTRIBUTORS.md
  base_territory/readme/CREDITS.md
  base_territory/readme/DESCRIPTION.md
  base_territory/readme/USAGE.md
  base_territory/security/ir.model.access.csv
  base_territory/static/description/icon.png
  base_territory/static/description/index.html
  base_territory/views/menu.xml
  base_territory/views/res_branch.xml
  base_territory/views/res_country.xml
  base_territory/views/res_district.xml
  base_territory/views/res_region.xml
  base_territory/views/res_territory.xml
Labels: approved, migration, bot is merging ⏳
