Repository OCA/field-service, pull requests merged in 2023-03, with the labels that each got.

#1026 [14.0][IMP] fieldservice_maintenance: maintenance request is created …
  fieldservice_maintenance/models/maintenance_request.py
  fieldservice_maintenance/tests/test_fsm_maintenance.py
Labels: enhancement, needs review, bot is merging ⏳

#1054 [IMP] fieldservice_sale: Allow overrides in _field_service_generation
  fieldservice_sale/models/sale_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1037 [14.0][IMP] fieldservice: Allow FSM tag name translation
  fieldservice/models/fsm_tag.py
Labels: enhancement, needs review, bot is merging ⏳

#1060 [12.0][IMP] update dotfiles
  .pre-commit-config.yaml
  fieldservice_equipment_stock/models/fsm_equipment.py
  fieldservice_vehicle_stock_request/models/__init__.py
Labels: enhancement
