Repository OCA/field-service, pull requests merged in 2023-01, with the labels that each got.

#1038 [FIX] fieldservice_stock_request: Field must be present in view but is missing.
  fieldservice_stock_request/views/fsm_order.xml
Labels: bug, needs review

#1012 [14.0][IMP] fieldservice_recurring: Add equipment to recurrence
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_recurring.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1024 [14.0][FIX] fieldservice_maintenance: correct dates in equipment maintenance tab
  fieldservice_maintenance/models/maintenance_request.py
Labels: bug, needs review, bot is merging ⏳

#1028 [14.0][IMP]fieldservice_activity: allow group_fsm_user_own to access fsm.order
  fieldservice_activity/__manifest__.py
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/security/ir_rule.xml
Labels: enhancement, needs review, bot is merging ⏳

#1030 [14.0][FIX] fieldservice_activity: Typos and formatting in strings
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
Labels: bug, needs review, approved, ready to merge

#1031 [14.0][FIX]fieldservice_recurring: fix security for group_fsm_user_own
  fieldservice_recurring/views/fsm_order.xml
  fieldservice_recurring/views/fsm_team.xml
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#943 [FIX][14.0]: fieldservice_sale_recurring: recurring order validation …
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: bug, question, approved, bot is merging ⏳

#1023 [14.0][FIX] fieldservice: display avatar in kanban tasks
  fieldservice/views/fsm_order.xml
Labels: bug, approved, ready to merge, bot is merging ⏳

#1043 [16.0][MIG] fieldservice_vehicle
  fieldservice_vehicle/README.rst
  fieldservice_vehicle/__init__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/i18n/de.po
  fieldservice_vehicle/i18n/es.po
  fieldservice_vehicle/i18n/es_AR.po
  fieldservice_vehicle/i18n/es_CL.po
  fieldservice_vehicle/i18n/fieldservice_vehicle.pot
  fieldservice_vehicle/i18n/it.po
  fieldservice_vehicle/i18n/pt_BR.po
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_order.py
  fieldservice_vehicle/models/fsm_person.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/readme/CONFIGURE.rst
  fieldservice_vehicle/readme/CONTRIBUTORS.rst
  fieldservice_vehicle/readme/CREDITS.rst
  fieldservice_vehicle/readme/DESCRIPTION.rst
  fieldservice_vehicle/readme/INSTALL.rst
  fieldservice_vehicle/readme/ROADMAP.rst
  fieldservice_vehicle/readme/USAGE.rst
  fieldservice_vehicle/security/ir.model.access.csv
  fieldservice_vehicle/security/res_groups.xml
  fieldservice_vehicle/static/description/icon.png
  fieldservice_vehicle/static/description/index.html
  fieldservice_vehicle/tests/__init__.py
  fieldservice_vehicle/tests/test_fsm_vehicle.py
  fieldservice_vehicle/views/fsm_order.xml
  fieldservice_vehicle/views/fsm_person.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
  setup/fieldservice_vehicle/odoo/addons/fieldservice_vehicle
  setup/fieldservice_vehicle/setup.py
Labels: approved, bot is merging ⏳
