Repository OCA/field-service, pull requests merged in 2023-08, with the labels that each got.

#1104 [14.0][IMP] fieldservice: add field is_closed on fsm.order
  fieldservice/models/fsm_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1113 [FIX] fieldservice_crm: order smart button
  fieldservice_crm/views/crm_lead.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1114 [14.0][FIX] fieldservice_recurring: Default team
  fieldservice_recurring/models/fsm_recurring.py
Labels: bug, needs review, approved, bot is merging ⏳

#1079 [FIX] fieldservice_equipment_stock: Equipment creation
  fieldservice_equipment_stock/models/stock_move.py
Labels: bug, needs review, bot is merging ⏳, stale
