Repository OCA/field-service, pull requests merged in 2023-04, with the labels that each got.

#1059 [16.0][IMP] fieldservice: improvements for scheduled dates
  fieldservice/models/fsm_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1061 [15.0][IMP] fieldservice: improvements for scheduled dates (PORT FROM #1059)
  fieldservice/models/fsm_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1062 [14.0][IMP] fieldservice improvements for scheduled dates (PORT FROM #1059)
  fieldservice/models/fsm_order.py
Labels: enhancement, needs review, bot is merging ⏳

#1063 [13.0][IMP] fieldservice: improvements for scheduled dates (PORT FROM #1059)
  .pre-commit-config.yaml
  fieldservice/models/fsm_order.py
Labels: enhancement, needs fixing, needs review, approved, bot is merging ⏳

#1064 [12.0][IMP] fieldservice: improvements for scheduled dates (PORT FROM #1059)
  fieldservice/models/fsm_order.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1067 [14.0][FW][IMP] fieldservice: request_late now calculated based on settings
  fieldservice/models/fsm_order.py
  fieldservice/models/res_company.py
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#1068 [15.0][FIX] fieldservice_stock: default inventory location not set
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/tests/test_fsm_stock.py
Labels: bug, needs review, approved, bot is merging ⏳

#1072 [15.0][FIX] fieldservice_sale: duplicated sales order doesn't create FSM Order
  fieldservice_sale/models/sale_order_line.py
Labels: bug, needs review, approved, bot is merging ⏳

#1071 [16.0][FIX] fieldservice_stock: make inventory location editable
  fieldservice_stock/models/fsm_location.py
Labels: bug, needs review, approved, bot is merging ⏳

#1073 [12.0][MIG] fieldservice_calendar: Migration to 12.0
  fieldservice_calendar/README.rst
  fieldservice_calendar/__init__.py
  fieldservice_calendar/__manifest__.py
  fieldservice_calendar/i18n/es_AR.po
  fieldservice_calendar/i18n/fieldservice_calendar.pot
  fieldservice_calendar/i18n/it.po
  fieldservice_calendar/i18n/pt_BR.po
  fieldservice_calendar/models/__init__.py
  fieldservice_calendar/models/calendar.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_calendar/models/fsm_team.py
  fieldservice_calendar/readme/CONFIGURE.rst
  fieldservice_calendar/readme/CONTRIBUTORS.rst
  fieldservice_calendar/readme/DESCRIPTION.rst
  fieldservice_calendar/static/description/icon.png
  fieldservice_calendar/static/description/index.html
  fieldservice_calendar/tests/__init__.py
  fieldservice_calendar/tests/test_fsm_calendar.py
  fieldservice_calendar/views/fsm_order.xml
  fieldservice_calendar/views/fsm_team.xml
  setup/fieldservice_calendar/odoo/addons/fieldservice_calendar
  setup/fieldservice_calendar/setup.py
Labels: approved, bot is merging ⏳

#1069 [15.0][FIX] fieldservice: replace type Text to Html in todo field
  fieldservice/models/fsm_order.py
  fieldservice/tests/test_fsm_order_template_onchange.py
  fieldservice/views/fsm_order.xml
Labels: bug, needs fixing, needs review, approved, ready to merge, bot is merging ⏳
