Repository OCA/field-service, pull requests merged in 2023-02, with the labels that each got.

#1045 [16.0][MIG] fieldservice_project
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/i18n/de.po
  fieldservice_project/i18n/es.po
  fieldservice_project/i18n/es_AR.po
  fieldservice_project/i18n/es_CL.po
  fieldservice_project/i18n/fieldservice_project.pot
  fieldservice_project/i18n/it.po
  fieldservice_project/i18n/pt_BR.po
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/readme/CONTRIBUTORS.rst
  fieldservice_project/readme/CREDITS.rst
  fieldservice_project/readme/DESCRIPTION.rst
  fieldservice_project/readme/ROADMAP.rst
  fieldservice_project/readme/USAGE.rst
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/description/index.html
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/tests/__init__.py
  fieldservice_project/tests/common.py
  fieldservice_project/tests/test_fsm_location.py
  fieldservice_project/tests/test_fsm_order.py
  fieldservice_project/tests/test_project.py
  fieldservice_project/tests/test_project_task.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/fsm_team.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
  setup/fieldservice_project/odoo/addons/fieldservice_project
  setup/fieldservice_project/setup.py
Labels: approved, bot is merging ⏳

#985 [16.0][MIG] fieldservice_account
  fieldservice_account/README.rst
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/i18n/de.po
  fieldservice_account/i18n/es.po
  fieldservice_account/i18n/es_AR.po
  fieldservice_account/i18n/es_CL.po
  fieldservice_account/i18n/fieldservice_account.pot
  fieldservice_account/i18n/it.po
  fieldservice_account/i18n/pt_BR.po
  fieldservice_account/i18n/tr.po
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_move.py
  fieldservice_account/models/account_move_line.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/readme/CONFIGURE.rst
  fieldservice_account/readme/CONTRIBUTORS.rst
  fieldservice_account/readme/CREDITS.rst
  fieldservice_account/readme/DESCRIPTION.rst
  fieldservice_account/readme/INSTALL.rst
  fieldservice_account/readme/USAGE.rst
  fieldservice_account/security/ir.model.access.csv
  fieldservice_account/static/description/icon.png
  fieldservice_account/static/description/index.html
  fieldservice_account/tests/__init__.py
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/views/account_move.xml
  fieldservice_account/views/fsm_order.xml
  setup/fieldservice_account/odoo/addons/fieldservice_account
  setup/fieldservice_account/setup.py
Labels: approved, migration, bot is merging ⏳, need tests

#1002 [16.0][FIX] fieldservice_stock: ensure inventory_location is assigned
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/hooks.py
Labels: bug, needs review, bot is merging ⏳

#1046 [14.0][IMP] fieldservice_stage_validation
  fieldservice_stage_validation/models/validate_utils.py
  fieldservice_stage_validation/readme/CONTRIBUTORS.rst
  fieldservice_stage_validation/tests/test_fsm_stage_validation.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1047 [14.0][IMP] fieldservice: Add freeze_time to test to prevent errors sometimes.
  fieldservice/tests/test_fsm_order.py
  fieldservice/tests/test_fsm_order_template_onchange.py
Labels: approved, bot is merging ⏳

#1048 [15.0][IMP] fieldservice: Add freeze_time to test to prevent errors sometimes.
  fieldservice/models/fsm_category.py
  fieldservice/report/fsm_order_report_template.xml
  fieldservice/tests/test_fsm_order.py
  fieldservice/tests/test_fsm_order_template_onchange.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1039 [14.0][IMP] fielservice_geoengine: refactor of fieldservice_geoengine module
  fieldservice/tests/test_fsm_order.py
  fieldservice_geoengine/__init__.py
  fieldservice_geoengine/__manifest__.py
  fieldservice_geoengine/models/fsm_location.py
  fieldservice_geoengine/models/fsm_order.py
  fieldservice_geoengine/readme/CONTRIBUTORS.rst
  fieldservice_geoengine/tests/test_fsm_location.py
  fieldservice_geoengine/views/fsm_location.xml
  fieldservice_geoengine/views/fsm_order.xml
Labels: enhancement, needs review, bot is merging ⏳

#1049 [IMP] fieldservice_sale: Simplify FSM creation
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale_recurring/models/sale_order.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1050 [15.0] [IMP] fieldservice_sale: Simplify FSM creation
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale_recurring/models/sale_order.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳
