Repository OCA/field-service, pull requests merged in 2023-10, with the labels that each got.

#1053 [14.0] [FIX] fieldservice_sale_recurring: Only invoice invoiceable fsm order
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: bug, needs fixing, needs review, approved, bot is merging ⏳, stale

#1122 [FIX] fieldservice_sale_*
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: bug, needs review, approved, bot is merging ⏳

#1124 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  fieldservice/i18n/fieldservice.pot
  fieldservice_recurring/i18n/fieldservice_recurring.pot
  fieldservice_stock/views/stock_picking.xml
Labels: help wanted, needs review, bot is merging ⏳
