Repository OCA/field-service, pull requests merged in 2023-06, with the labels that each got.

#1097 [14.0] fieldservice_geoengine: fix test to new values from api
  fieldservice_geoengine/tests/test_fsm_location.py
Labels: approved, bot is merging ⏳

#1087 [FIX] fieldservice_route: `clickable` is now an option for the `statusbar` widget
  fieldservice_route/views/fsm_route_dayroute.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1051 [IMP][14.0] fieldservice_account: add _get_invoiceable_stage method &…
  fieldservice_account/models/fsm_stage.py
  fieldservice_account/views/account_move.xml
Labels: enhancement, needs fixing, needs review, approved, bot is merging ⏳, need tests

#1101 [16.0][MIG] fieldservice_sale: Migration to version 16.0
  fieldservice_sale/README.rst
  fieldservice_sale/__init__.py
  fieldservice_sale/__manifest__.py
  fieldservice_sale/i18n/de.po
  fieldservice_sale/i18n/es.po
  fieldservice_sale/i18n/es_AR.po
  fieldservice_sale/i18n/es_CL.po
  fieldservice_sale/i18n/fieldservice_sale.pot
  fieldservice_sale/i18n/it.po
  fieldservice_sale/i18n/pt_BR.po
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_order.py
  fieldservice_sale/models/product_template.py
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/readme/CONFIGURE.rst
  fieldservice_sale/readme/CONTRIBUTORS.rst
  fieldservice_sale/readme/DESCRIPTION.rst
  fieldservice_sale/readme/INSTALL.rst
  fieldservice_sale/readme/ROADMAP.rst
  fieldservice_sale/readme/USAGE.rst
  fieldservice_sale/security/ir.model.access.csv
  fieldservice_sale/security/res_groups.xml
  fieldservice_sale/static/description/icon.png
  fieldservice_sale/static/description/index.html
  fieldservice_sale/tests/__init__.py
  fieldservice_sale/tests/test_fsm_sale_autofill_location.py
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale/views/fsm_location.xml
  fieldservice_sale/views/fsm_order.xml
  fieldservice_sale/views/product_template.xml
  fieldservice_sale/views/sale_order.xml
  setup/fieldservice_sale/odoo/addons/fieldservice_sale
  setup/fieldservice_sale/setup.py
Labels: bot is merging ⏳

#992 [16.0][MIG] fieldservice_route
  fieldservice_route/README.rst
  fieldservice_route/__init__.py
  fieldservice_route/__manifest__.py
  fieldservice_route/data/fsm_route_day_data.xml
  fieldservice_route/data/fsm_stage_data.xml
  fieldservice_route/data/ir_sequence.xml
  fieldservice_route/i18n/es.po
  fieldservice_route/i18n/es_AR.po
  fieldservice_route/i18n/es_CL.po
  fieldservice_route/i18n/fieldservice_route.pot
  fieldservice_route/i18n/it.po
  fieldservice_route/i18n/pt_BR.po
  fieldservice_route/i18n/pt_PT.po
  fieldservice_route/i18n/tr.po
  fieldservice_route/models/__init__.py
  fieldservice_route/models/fsm_location.py
  fieldservice_route/models/fsm_order.py
  fieldservice_route/models/fsm_route.py
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
  fieldservice_route/models/fsm_stage.py
  fieldservice_route/readme/CONFIGURE.rst
  fieldservice_route/readme/CONTRIBUTORS.rst
  fieldservice_route/readme/CREDITS.rst
  fieldservice_route/readme/DESCRIPTION.rst
  fieldservice_route/readme/USAGE.rst
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/static/description/icon.png
  fieldservice_route/static/description/index.html
  fieldservice_route/tests/__init__.py
  fieldservice_route/tests/test_fsm_order.py
  fieldservice_route/views/fsm_location.xml
  fieldservice_route/views/fsm_order.xml
  fieldservice_route/views/fsm_route.xml
  fieldservice_route/views/fsm_route_day.xml
  fieldservice_route/views/fsm_route_dayroute.xml
  fieldservice_route/views/menu.xml
  setup/fieldservice_route/odoo/addons/fieldservice_route
  setup/fieldservice_route/setup.py
Labels: approved, migration, bot is merging ⏳, no stale, need tests
