Repository OCA/field-service, pull requests merged in 2023-07, with the labels that each got.

#1094 [16.0][MIG] fieldservice_skill: Migration to version 16.0
  fieldservice_skill/README.rst
  fieldservice_skill/__init__.py
  fieldservice_skill/__manifest__.py
  fieldservice_skill/i18n/de.po
  fieldservice_skill/i18n/es.po
  fieldservice_skill/i18n/es_AR.po
  fieldservice_skill/i18n/es_CL.po
  fieldservice_skill/i18n/fieldservice_skill.pot
  fieldservice_skill/i18n/it.po
  fieldservice_skill/i18n/pt_BR.po
  fieldservice_skill/models/__init__.py
  fieldservice_skill/models/fsm_category.py
  fieldservice_skill/models/fsm_order.py
  fieldservice_skill/models/fsm_person.py
  fieldservice_skill/models/fsm_person_skill.py
  fieldservice_skill/models/fsm_template.py
  fieldservice_skill/models/hr_skill.py
  fieldservice_skill/readme/CONFIGURE.rst
  fieldservice_skill/readme/CONTRIBUTORS.rst
  fieldservice_skill/readme/CREDITS.rst
  fieldservice_skill/readme/DESCRIPTION.rst
  fieldservice_skill/readme/ROADMAP.rst
  fieldservice_skill/readme/USAGE.rst
  fieldservice_skill/security/ir.model.access.csv
  fieldservice_skill/static/description/icon.png
  fieldservice_skill/static/description/index.html
  fieldservice_skill/tests/__init__.py
  fieldservice_skill/tests/test_fsm_skill.py
  fieldservice_skill/views/fsm_category.xml
  fieldservice_skill/views/fsm_order.xml
  fieldservice_skill/views/fsm_person.xml
  fieldservice_skill/views/fsm_person_skill.xml
  fieldservice_skill/views/fsm_template.xml
  fieldservice_skill/views/hr_skill.xml
  setup/fieldservice_skill/odoo/addons/fieldservice_skill
  setup/fieldservice_skill/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1092 [FIX] fieldservice_stage_server_action
  fieldservice_geoengine/tests/test_fsm_location.py
  fieldservice_stage_server_action/models/fsm_order.py
Labels: bug, needs review

#1106 [16.0][MIG] fieldservice_size: Migration to 16.0
  fieldservice_size/README.rst
  fieldservice_size/__init__.py
  fieldservice_size/__manifest__.py
  fieldservice_size/i18n/es.po
  fieldservice_size/i18n/es_AR.po
  fieldservice_size/i18n/fieldservice_size.pot
  fieldservice_size/i18n/it.po
  fieldservice_size/i18n/pt_BR.po
  fieldservice_size/models/__init__.py
  fieldservice_size/models/fsm_location.py
  fieldservice_size/models/fsm_location_size.py
  fieldservice_size/models/fsm_order.py
  fieldservice_size/models/fsm_size.py
  fieldservice_size/readme/CONFIGURE.rst
  fieldservice_size/readme/CONTRIBUTORS.rst
  fieldservice_size/readme/DESCRIPTION.rst
  fieldservice_size/readme/ROADMAP.rst
  fieldservice_size/readme/USAGE.rst
  fieldservice_size/security/ir.model.access.csv
  fieldservice_size/static/description/icon.png
  fieldservice_size/static/description/index.html
  fieldservice_size/tests/__init__.py
  fieldservice_size/tests/test_fsm_order.py
  fieldservice_size/views/fsm_location.xml
  fieldservice_size/views/fsm_order.xml
  fieldservice_size/views/fsm_size.xml
  fieldservice_size/views/menu.xml
  setup/fieldservice_size/odoo/addons/fieldservice_size
  setup/fieldservice_size/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1107 [15.0][MIG] fieldservice_fleet: Migration to 15.0
  fieldservice_fleet/README.rst
  fieldservice_fleet/__init__.py
  fieldservice_fleet/__manifest__.py
  fieldservice_fleet/hooks.py
  fieldservice_fleet/i18n/es.po
  fieldservice_fleet/i18n/es_AR.po
  fieldservice_fleet/i18n/es_CL.po
  fieldservice_fleet/i18n/fieldservice_fleet.pot
  fieldservice_fleet/i18n/it.po
  fieldservice_fleet/i18n/pt_BR.po
  fieldservice_fleet/models/__init__.py
  fieldservice_fleet/models/fleet_vehicle.py
  fieldservice_fleet/models/fsm_vehicle.py
  fieldservice_fleet/readme/CONFIGURE.rst
  fieldservice_fleet/readme/CONTRIBUTORS.rst
  fieldservice_fleet/readme/CREDITS.rst
  fieldservice_fleet/readme/DESCRIPTION.rst
  fieldservice_fleet/readme/INSTALL.rst
  fieldservice_fleet/readme/ROADMAP.rst
  fieldservice_fleet/readme/USAGE.rst
  fieldservice_fleet/security/ir.model.access.csv
  fieldservice_fleet/static/description/icon.png
  fieldservice_fleet/static/description/index.html
  fieldservice_fleet/tests/__init__.py
  fieldservice_fleet/tests/test_fsm_fleet_wizard.py
  fieldservice_fleet/views/fleet_vehicle.xml
  fieldservice_fleet/views/fsm_vehicle.xml
  fieldservice_fleet/wizard/__init__.py
  fieldservice_fleet/wizard/fsm_fleet_wizard.py
  fieldservice_fleet/wizard/fsm_fleet_wizard.xml
  setup/fieldservice_fleet/odoo/addons/fieldservice_fleet
  setup/fieldservice_fleet/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1074 [16.0][MIG] fieldservice_calendar: Migration to 16.0
  fieldservice_calendar/README.rst
  fieldservice_calendar/__init__.py
  fieldservice_calendar/__manifest__.py
  fieldservice_calendar/i18n/es_AR.po
  fieldservice_calendar/i18n/fieldservice_calendar.pot
  fieldservice_calendar/i18n/it.po
  fieldservice_calendar/i18n/pt_BR.po
  fieldservice_calendar/models/__init__.py
  fieldservice_calendar/models/calendar.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_calendar/models/fsm_team.py
  fieldservice_calendar/readme/CONFIGURE.rst
  fieldservice_calendar/readme/CONTRIBUTORS.rst
  fieldservice_calendar/readme/DESCRIPTION.rst
  fieldservice_calendar/static/description/icon.png
  fieldservice_calendar/static/description/index.html
  fieldservice_calendar/tests/__init__.py
  fieldservice_calendar/tests/test_fsm_calendar.py
  fieldservice_calendar/views/fsm_order.xml
  fieldservice_calendar/views/fsm_team.xml
  setup/fieldservice_calendar/odoo/addons/fieldservice_calendar
  setup/fieldservice_calendar/setup.py
Labels: approved, ready to merge, bot is merging ⏳, need tests
