Repository OCA/field-service, pull requests merged in 2024-07, with the labels that each got.

#1198 [FIX] fieldservice_account_payment:
  fieldservice_account_payment/static/description/index.html
  fieldservice_account_payment/tests/test_fsm_account_payment.py
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1197 [15.0][ADD] fieldservice_logbook
  fieldservice_logbook/README.rst
  fieldservice_logbook/__init__.py
  fieldservice_logbook/__manifest__.py
  fieldservice_logbook/models/__init__.py
  fieldservice_logbook/models/fsm_equipment.py
  fieldservice_logbook/models/fsm_equipment_logbook.py
  fieldservice_logbook/models/fsm_equipment_logbook_mixin.py
  fieldservice_logbook/models/fsm_location.py
  fieldservice_logbook/models/fsm_order.py
  fieldservice_logbook/readme/CONTRIBUTORS.md
  fieldservice_logbook/readme/DESCRIPTION.md
  fieldservice_logbook/security/ir.model.access.csv
  fieldservice_logbook/security/res_groups.xml
  fieldservice_logbook/static/description/icon.png
  fieldservice_logbook/static/description/index.html
  fieldservice_logbook/tests/__init__.py
  fieldservice_logbook/tests/test_fsm_equipment_logbook.py
  fieldservice_logbook/views/fsm_equipment.xml
  fieldservice_logbook/views/fsm_equipment_logbook.xml
  fieldservice_logbook/views/fsm_location.xml
  fieldservice_logbook/views/fsm_order.xml
  setup/fieldservice_logbook/odoo/addons/fieldservice_logbook
  setup/fieldservice_logbook/setup.py
Labels: enhancement, needs fixing, needs review, approved, bot is merging ⏳

#1196 [17.0][MIG] fieldservice_stock_request: Migration to 17.0
  fieldservice_stock_request/README.rst
  fieldservice_stock_request/__init__.py
  fieldservice_stock_request/__manifest__.py
  fieldservice_stock_request/i18n/es.po
  fieldservice_stock_request/i18n/es_AR.po
  fieldservice_stock_request/i18n/fieldservice_stock_request.pot
  fieldservice_stock_request/i18n/it.po
  fieldservice_stock_request/i18n/pt_BR.po
  fieldservice_stock_request/models/__init__.py
  fieldservice_stock_request/models/fsm_order.py
  fieldservice_stock_request/models/stock_move_line.py
  fieldservice_stock_request/models/stock_request.py
  fieldservice_stock_request/models/stock_request_order.py
  fieldservice_stock_request/pyproject.toml
  fieldservice_stock_request/readme/CONFIGURE.md
  fieldservice_stock_request/readme/CONTRIBUTORS.md
  fieldservice_stock_request/readme/CREDITS.md
  fieldservice_stock_request/readme/DESCRIPTION.md
  fieldservice_stock_request/readme/ROADMAP.md
  fieldservice_stock_request/readme/USAGE.md
  fieldservice_stock_request/security/ir.model.access.csv
  fieldservice_stock_request/static/description/icon.png
  fieldservice_stock_request/static/description/index.html
  fieldservice_stock_request/tests/__init__.py
  fieldservice_stock_request/tests/test_fsm_stock_request.py
  fieldservice_stock_request/views/fsm_order.xml
  fieldservice_stock_request/views/stock.xml
  fieldservice_stock_request/views/stock_request.xml
  fieldservice_stock_request/views/stock_request_order.xml
Labels: needs review, approved, migration, bot is merging ⏳
