Repository OCA/field-service, pull requests merged in 2024-01, with the labels that each got.

#1154 [IMP] v17 style icon
  fieldservice/static/description/icon.png
  fieldservice/static/description/icon.svg
Labels: enhancement, needs review, approved, bot is merging ⏳

#1150 17.0 [MIG] fieldservice_account
  fieldservice_account/README.rst
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/i18n/de.po
  fieldservice_account/i18n/es.po
  fieldservice_account/i18n/es_AR.po
  fieldservice_account/i18n/es_CL.po
  fieldservice_account/i18n/fieldservice_account.pot
  fieldservice_account/i18n/it.po
  fieldservice_account/i18n/pt_BR.po
  fieldservice_account/i18n/tr.po
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_move.py
  fieldservice_account/models/account_move_line.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/models/fsm_stage.py
  fieldservice_account/pyproject.toml
  fieldservice_account/readme/CONFIGURE.md
  fieldservice_account/readme/CONTRIBUTORS.md
  fieldservice_account/readme/CREDITS.md
  fieldservice_account/readme/DESCRIPTION.md
  fieldservice_account/readme/INSTALL.md
  fieldservice_account/readme/USAGE.md
  fieldservice_account/security/ir.model.access.csv
  fieldservice_account/static/description/icon.png
  fieldservice_account/static/description/index.html
  fieldservice_account/tests/__init__.py
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/views/account_move.xml
  fieldservice_account/views/fsm_order.xml
  fieldservice_account/views/fsm_stage.xml
Labels: approved, migration, bot is merging ⏳

#1152 [16.0] [FIX] fieldservice: FSM Person Calendar Filter
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice/views/fsm_order.xml
Labels: bug, bot is merging ⏳

#1153 [17.0] [FIX] fieldservice: FSM Person Calendar Filter
  fieldservice/models/fsm_person_calendar_filter.py
  fieldservice/views/fsm_order.xml
Labels: bug, approved, ready to merge, bot is merging ⏳
