Repository OCA/field-service, pull requests merged in 2024-11, with the labels that each got.

#1238 [18.0][MIG] fieldservice_project
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/i18n/de.po
  fieldservice_project/i18n/es.po
  fieldservice_project/i18n/es_AR.po
  fieldservice_project/i18n/es_CL.po
  fieldservice_project/i18n/fieldservice_project.pot
  fieldservice_project/i18n/fr.po
  fieldservice_project/i18n/it.po
  fieldservice_project/i18n/pt_BR.po
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/pyproject.toml
  fieldservice_project/readme/CONTRIBUTORS.md
  fieldservice_project/readme/CREDITS.md
  fieldservice_project/readme/DESCRIPTION.md
  fieldservice_project/readme/ROADMAP.md
  fieldservice_project/readme/USAGE.md
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/description/icon.svg
  fieldservice_project/static/description/index.html
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/tests/__init__.py
  fieldservice_project/tests/common.py
  fieldservice_project/tests/test_fsm_location.py
  fieldservice_project/tests/test_fsm_order.py
  fieldservice_project/tests/test_project.py
  fieldservice_project/tests/test_project_task.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/fsm_team.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1225 [MIG][18.0]fieldservice_account
  fieldservice_account/README.rst
  fieldservice_account/__init__.py
  fieldservice_account/__manifest__.py
  fieldservice_account/i18n/de.po
  fieldservice_account/i18n/es.po
  fieldservice_account/i18n/es_AR.po
  fieldservice_account/i18n/es_CL.po
  fieldservice_account/i18n/fieldservice_account.pot
  fieldservice_account/i18n/it.po
  fieldservice_account/i18n/pt_BR.po
  fieldservice_account/i18n/tr.po
  fieldservice_account/models/__init__.py
  fieldservice_account/models/account_move.py
  fieldservice_account/models/account_move_line.py
  fieldservice_account/models/fsm_order.py
  fieldservice_account/models/fsm_stage.py
  fieldservice_account/pyproject.toml
  fieldservice_account/readme/CONFIGURE.md
  fieldservice_account/readme/CONTRIBUTORS.md
  fieldservice_account/readme/CREDITS.md
  fieldservice_account/readme/DESCRIPTION.md
  fieldservice_account/readme/INSTALL.md
  fieldservice_account/readme/USAGE.md
  fieldservice_account/security/ir.model.access.csv
  fieldservice_account/static/description/icon.png
  fieldservice_account/static/description/index.html
  fieldservice_account/tests/__init__.py
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account/views/account_move.xml
  fieldservice_account/views/fsm_order.xml
  fieldservice_account/views/fsm_stage.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1236 [18.0][MIG] fieldservice_crm
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/i18n/de.po
  fieldservice_crm/i18n/es.po
  fieldservice_crm/i18n/es_AR.po
  fieldservice_crm/i18n/es_CL.po
  fieldservice_crm/i18n/fieldservice_crm.pot
  fieldservice_crm/i18n/fr.po
  fieldservice_crm/i18n/it.po
  fieldservice_crm/i18n/pt_BR.po
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/pyproject.toml
  fieldservice_crm/readme/CONFIGURE.md
  fieldservice_crm/readme/CONTRIBUTORS.md
  fieldservice_crm/readme/CREDITS.md
  fieldservice_crm/readme/DESCRIPTION.md
  fieldservice_crm/readme/INSTALL.md
  fieldservice_crm/readme/ROADMAP.md
  fieldservice_crm/readme/USAGE.md
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/static/description/index.html
  fieldservice_crm/tests/__init__.py
  fieldservice_crm/tests/test_fsm_crm.py
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1255 [IMP] fieldservice_stage_server_action: Add missing code during migration from v14
  fieldservice_stage_server_action/models/fsm_stage_server_action_mixin.py
  fieldservice_stage_server_action/tests/test_fsm_order_run_action.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1235 [18.0][MIG] fieldservice_calendar
  fieldservice_calendar/README.rst
  fieldservice_calendar/__init__.py
  fieldservice_calendar/__manifest__.py
  fieldservice_calendar/i18n/de.po
  fieldservice_calendar/i18n/es.po
  fieldservice_calendar/i18n/es_AR.po
  fieldservice_calendar/i18n/fieldservice_calendar.pot
  fieldservice_calendar/i18n/it.po
  fieldservice_calendar/i18n/pt_BR.po
  fieldservice_calendar/models/__init__.py
  fieldservice_calendar/models/calendar.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_calendar/models/fsm_team.py
  fieldservice_calendar/pyproject.toml
  fieldservice_calendar/readme/CONFIGURE.md
  fieldservice_calendar/readme/CONTRIBUTORS.md
  fieldservice_calendar/readme/DESCRIPTION.md
  fieldservice_calendar/static/description/icon.png
  fieldservice_calendar/static/description/index.html
  fieldservice_calendar/tests/__init__.py
  fieldservice_calendar/tests/test_fsm_calendar.py
  fieldservice_calendar/views/fsm_order.xml
  fieldservice_calendar/views/fsm_team.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1233 [18.0][MIG] fieldservice_vehicle
  fieldservice_vehicle/README.rst
  fieldservice_vehicle/__init__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/i18n/de.po
  fieldservice_vehicle/i18n/es.po
  fieldservice_vehicle/i18n/es_AR.po
  fieldservice_vehicle/i18n/es_CL.po
  fieldservice_vehicle/i18n/fieldservice_vehicle.pot
  fieldservice_vehicle/i18n/it.po
  fieldservice_vehicle/i18n/pt_BR.po
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_order.py
  fieldservice_vehicle/models/fsm_person.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/pyproject.toml
  fieldservice_vehicle/readme/CONFIGURE.md
  fieldservice_vehicle/readme/CONTRIBUTORS.md
  fieldservice_vehicle/readme/CREDITS.md
  fieldservice_vehicle/readme/DESCRIPTION.md
  fieldservice_vehicle/readme/INSTALL.md
  fieldservice_vehicle/readme/ROADMAP.md
  fieldservice_vehicle/readme/USAGE.md
  fieldservice_vehicle/security/ir.model.access.csv
  fieldservice_vehicle/security/res_groups.xml
  fieldservice_vehicle/static/description/icon.png
  fieldservice_vehicle/static/description/index.html
  fieldservice_vehicle/tests/__init__.py
  fieldservice_vehicle/tests/test_fsm_vehicle.py
  fieldservice_vehicle/views/fsm_order.xml
  fieldservice_vehicle/views/fsm_person.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1262 [FIX] fieldservice: replace kanban-box for card
  fieldservice/views/fsm_equipment.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_team.xml
Labels: bug, needs review, bot is merging ⏳

#1231 [18.0][MIG] fieldservice_sale
  fieldservice_sale/README.rst
  fieldservice_sale/__init__.py
  fieldservice_sale/__manifest__.py
  fieldservice_sale/i18n/de.po
  fieldservice_sale/i18n/es.po
  fieldservice_sale/i18n/es_AR.po
  fieldservice_sale/i18n/es_CL.po
  fieldservice_sale/i18n/fieldservice_sale.pot
  fieldservice_sale/i18n/it.po
  fieldservice_sale/i18n/pt_BR.po
  fieldservice_sale/i18n/sk.po
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_order.py
  fieldservice_sale/models/product_template.py
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/pyproject.toml
  fieldservice_sale/readme/CONFIGURE.md
  fieldservice_sale/readme/CONTRIBUTORS.md
  fieldservice_sale/readme/DESCRIPTION.md
  fieldservice_sale/readme/INSTALL.md
  fieldservice_sale/readme/ROADMAP.md
  fieldservice_sale/readme/USAGE.md
  fieldservice_sale/security/ir.model.access.csv
  fieldservice_sale/security/res_groups.xml
  fieldservice_sale/static/description/icon.png
  fieldservice_sale/static/description/index.html
  fieldservice_sale/tests/__init__.py
  fieldservice_sale/tests/test_fsm_sale_autofill_location.py
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale/views/fsm_location.xml
  fieldservice_sale/views/fsm_order.xml
  fieldservice_sale/views/product_template.xml
  fieldservice_sale/views/sale_order.xml
Labels: needs review, migration, bot is merging ⏳

#1234 [18.0][MIG] fieldservice_activity
  fieldservice_activity/README.rst
  fieldservice_activity/__init__.py
  fieldservice_activity/__manifest__.py
  fieldservice_activity/i18n/es.po
  fieldservice_activity/i18n/es_AR.po
  fieldservice_activity/i18n/es_CL.po
  fieldservice_activity/i18n/fieldservice_activity.pot
  fieldservice_activity/i18n/it.po
  fieldservice_activity/i18n/pt_BR.po
  fieldservice_activity/i18n/pt_PT.po
  fieldservice_activity/models/__init__.py
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/models/fsm_template.py
  fieldservice_activity/pyproject.toml
  fieldservice_activity/readme/CONFIGURE.md
  fieldservice_activity/readme/CONTRIBUTORS.md
  fieldservice_activity/readme/CREDITS.md
  fieldservice_activity/readme/DESCRIPTION.md
  fieldservice_activity/readme/USAGE.md
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/static/description/field_service_settings_manage_templates.png
  fieldservice_activity/static/description/field_service_template.png
  fieldservice_activity/static/description/field_service_template_activities.png
  fieldservice_activity/static/description/fsm_order_activity_tab.png
  fieldservice_activity/static/description/icon.png
  fieldservice_activity/static/description/icon.svg
  fieldservice_activity/static/description/index.html
  fieldservice_activity/tests/__init__.py
  fieldservice_activity/tests/test_fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1244 [18.0][MIG] fieldservice_sale_recurring
  fieldservice_sale_recurring/README.rst
  fieldservice_sale_recurring/__init__.py
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/i18n/de.po
  fieldservice_sale_recurring/i18n/es.po
  fieldservice_sale_recurring/i18n/es_AR.po
  fieldservice_sale_recurring/i18n/es_CL.po
  fieldservice_sale_recurring/i18n/fieldservice_sale_recurring.pot
  fieldservice_sale_recurring/i18n/fr.po
  fieldservice_sale_recurring/i18n/it.po
  fieldservice_sale_recurring/i18n/pt_BR.po
  fieldservice_sale_recurring/models/__init__.py
  fieldservice_sale_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/product_template.py
  fieldservice_sale_recurring/models/sale_order.py
  fieldservice_sale_recurring/models/sale_order_line.py
  fieldservice_sale_recurring/pyproject.toml
  fieldservice_sale_recurring/readme/CONFIGURE.md
  fieldservice_sale_recurring/readme/CONTRIBUTORS.md
  fieldservice_sale_recurring/readme/DESCRIPTION.md
  fieldservice_sale_recurring/readme/ROADMAP.md
  fieldservice_sale_recurring/readme/USAGE.md
  fieldservice_sale_recurring/security/ir.model.access.csv
  fieldservice_sale_recurring/static/description/icon.png
  fieldservice_sale_recurring/static/description/icon.svg
  fieldservice_sale_recurring/static/description/index.html
  fieldservice_sale_recurring/tests/__init__.py
  fieldservice_sale_recurring/tests/test_fsm_sale_recurring.py
  fieldservice_sale_recurring/views/fsm_recurring.xml
  fieldservice_sale_recurring/views/product_template.xml
  fieldservice_sale_recurring/views/sale_order.xml
Labels: needs review, migration, bot is merging ⏳

#1232 [18.0][MIG] fieldservice_stock
  fieldservice_stock/README.rst
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/data/fsm_stock_data.xml
  fieldservice_stock/hooks.py
  fieldservice_stock/i18n/de.po
  fieldservice_stock/i18n/es.po
  fieldservice_stock/i18n/es_AR.po
  fieldservice_stock/i18n/es_CL.po
  fieldservice_stock/i18n/fieldservice_stock.pot
  fieldservice_stock/i18n/fr.po
  fieldservice_stock/i18n/it.po
  fieldservice_stock/i18n/pt_BR.po
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/fsm_wizard.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/res_territory.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_picking.py
  fieldservice_stock/models/stock_rule.py
  fieldservice_stock/pyproject.toml
  fieldservice_stock/readme/CONFIGURE.md
  fieldservice_stock/readme/CONTRIBUTORS.md
  fieldservice_stock/readme/CREDITS.md
  fieldservice_stock/readme/DESCRIPTION.md
  fieldservice_stock/readme/INSTALL.md
  fieldservice_stock/readme/ROADMAP.md
  fieldservice_stock/readme/USAGE.md
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock/static/description/icon.png
  fieldservice_stock/static/description/icon.svg
  fieldservice_stock/static/description/index.html
  fieldservice_stock/tests/__init__.py
  fieldservice_stock/tests/test_fsm_stock.py
  fieldservice_stock/tests/test_fsm_wizard.py
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/res_territory.xml
  fieldservice_stock/views/stock.xml
  fieldservice_stock/views/stock_picking.xml
Labels: needs review, migration, bot is merging ⏳

#1246 [18.0][MIG] fieldservice_size
  fieldservice_size/README.rst
  fieldservice_size/__init__.py
  fieldservice_size/__manifest__.py
  fieldservice_size/i18n/es.po
  fieldservice_size/i18n/es_AR.po
  fieldservice_size/i18n/fieldservice_size.pot
  fieldservice_size/i18n/it.po
  fieldservice_size/i18n/pt_BR.po
  fieldservice_size/models/__init__.py
  fieldservice_size/models/fsm_location.py
  fieldservice_size/models/fsm_location_size.py
  fieldservice_size/models/fsm_order.py
  fieldservice_size/models/fsm_size.py
  fieldservice_size/pyproject.toml
  fieldservice_size/readme/CONFIGURE.md
  fieldservice_size/readme/CONTRIBUTORS.md
  fieldservice_size/readme/DESCRIPTION.md
  fieldservice_size/readme/ROADMAP.md
  fieldservice_size/readme/USAGE.md
  fieldservice_size/security/ir.model.access.csv
  fieldservice_size/static/description/icon.png
  fieldservice_size/static/description/icon.svg
  fieldservice_size/static/description/index.html
  fieldservice_size/tests/__init__.py
  fieldservice_size/tests/test_fsm_order.py
  fieldservice_size/views/fsm_location.xml
  fieldservice_size/views/fsm_order.xml
  fieldservice_size/views/fsm_size.xml
  fieldservice_size/views/menu.xml
Labels: needs review, migration, bot is merging ⏳

#1247 [18.0][MIG] fieldservice_stage_server_action
  fieldservice_stage_server_action/README.rst
  fieldservice_stage_server_action/__init__.py
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/data/base_automation.xml
  fieldservice_stage_server_action/data/fsm_stage.xml
  fieldservice_stage_server_action/data/ir_server_action.xml
  fieldservice_stage_server_action/i18n/de.po
  fieldservice_stage_server_action/i18n/es.po
  fieldservice_stage_server_action/i18n/es_AR.po
  fieldservice_stage_server_action/i18n/es_CL.po
  fieldservice_stage_server_action/i18n/fieldservice_stage_server_action.pot
  fieldservice_stage_server_action/i18n/it.po
  fieldservice_stage_server_action/i18n/pt_BR.po
  fieldservice_stage_server_action/models/__init__.py
  fieldservice_stage_server_action/models/fsm_order.py
  fieldservice_stage_server_action/models/fsm_stage.py
  fieldservice_stage_server_action/pyproject.toml
  fieldservice_stage_server_action/readme/CONFIGURE.md
  fieldservice_stage_server_action/readme/CONTRIBUTORS.md
  fieldservice_stage_server_action/readme/DESCRIPTION.md
  fieldservice_stage_server_action/readme/USAGE.md
  fieldservice_stage_server_action/static/description/icon.png
  fieldservice_stage_server_action/static/description/icon.svg
  fieldservice_stage_server_action/static/description/index.html
  fieldservice_stage_server_action/tests/__init__.py
  fieldservice_stage_server_action/tests/test_fsm_order_run_action.py
  fieldservice_stage_server_action/views/fsm_stage.xml
Labels: needs fixing, needs review, migration, bot is merging ⏳
