Repository OCA/field-service, pull requests merged in 2024-06, with the labels that each got.

#1193 [16.0][FIX] fieldservice_geoengine: Get extent when open the map
  fieldservice_geoengine/views/fsm_order.xml
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1195 [17.0][MIG] fieldservice_sale
  fieldservice_sale/README.rst
  fieldservice_sale/__init__.py
  fieldservice_sale/__manifest__.py
  fieldservice_sale/i18n/de.po
  fieldservice_sale/i18n/es.po
  fieldservice_sale/i18n/es_AR.po
  fieldservice_sale/i18n/es_CL.po
  fieldservice_sale/i18n/fieldservice_sale.pot
  fieldservice_sale/i18n/it.po
  fieldservice_sale/i18n/pt_BR.po
  fieldservice_sale/i18n/sk.po
  fieldservice_sale/models/__init__.py
  fieldservice_sale/models/fsm_order.py
  fieldservice_sale/models/product_template.py
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/pyproject.toml
  fieldservice_sale/readme/CONFIGURE.md
  fieldservice_sale/readme/CONTRIBUTORS.md
  fieldservice_sale/readme/DESCRIPTION.md
  fieldservice_sale/readme/INSTALL.md
  fieldservice_sale/readme/ROADMAP.md
  fieldservice_sale/readme/USAGE.md
  fieldservice_sale/security/ir.model.access.csv
  fieldservice_sale/security/res_groups.xml
  fieldservice_sale/static/description/icon.png
  fieldservice_sale/static/description/index.html
  fieldservice_sale/tests/__init__.py
  fieldservice_sale/tests/test_fsm_sale_autofill_location.py
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale/views/fsm_location.xml
  fieldservice_sale/views/fsm_order.xml
  fieldservice_sale/views/product_template.xml
  fieldservice_sale/views/sale_order.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1172 [16.0][MIG] fieldservice_stock_request: Migration to 16.0
  fieldservice_stock_request/README.rst
  fieldservice_stock_request/__init__.py
  fieldservice_stock_request/__manifest__.py
  fieldservice_stock_request/i18n/es.po
  fieldservice_stock_request/i18n/es_AR.po
  fieldservice_stock_request/i18n/fieldservice_stock_request.pot
  fieldservice_stock_request/i18n/it.po
  fieldservice_stock_request/i18n/pt_BR.po
  fieldservice_stock_request/models/__init__.py
  fieldservice_stock_request/models/fsm_order.py
  fieldservice_stock_request/models/stock_move_line.py
  fieldservice_stock_request/models/stock_request.py
  fieldservice_stock_request/models/stock_request_order.py
  fieldservice_stock_request/readme/CONFIGURE.rst
  fieldservice_stock_request/readme/CONTRIBUTORS.rst
  fieldservice_stock_request/readme/CREDITS.rst
  fieldservice_stock_request/readme/DESCRIPTION.rst
  fieldservice_stock_request/readme/ROADMAP.rst
  fieldservice_stock_request/readme/USAGE.rst
  fieldservice_stock_request/security/ir.model.access.csv
  fieldservice_stock_request/static/description/icon.png
  fieldservice_stock_request/static/description/index.html
  fieldservice_stock_request/tests/__init__.py
  fieldservice_stock_request/tests/test_fsm_stock_request.py
  fieldservice_stock_request/views/fsm_order.xml
  fieldservice_stock_request/views/stock.xml
  fieldservice_stock_request/views/stock_request.xml
  fieldservice_stock_request/views/stock_request_order.xml
  setup/fieldservice_stock_request/odoo/addons/fieldservice_stock_request
  setup/fieldservice_stock_request/setup.py
Labels: needs fixing, approved, migration, bot is merging ⏳
