Repository OCA/field-service, pull requests merged in 2024-10, with the labels that each got.

#1217 [17.0][IMP] fieldservice_activity: improve Readme Usage.
  fieldservice_activity/readme/CONTRIBUTORS.md
  fieldservice_activity/readme/USAGE.md
  fieldservice_activity/static/description/field_service_settings_manage_templates.png
  fieldservice_activity/static/description/field_service_template.png
  fieldservice_activity/static/description/field_service_template_activities.png
  fieldservice_activity/static/description/fsm_order_activity_tab.png
Labels: enhancement, needs review, bot is merging ⏳

#1216 [IMP] fieldservice: Documentation
  fieldservice/readme/DESCRIPTION.md
Labels: needs review, bot is merging ⏳

#1199 [16.0][IMP] fieldservice_calendar: Sync description
  fieldservice_calendar/models/calendar.py
  fieldservice_calendar/models/fsm_order.py
  fieldservice_calendar/readme/CONTRIBUTORS.rst
  fieldservice_calendar/tests/test_fsm_calendar.py
Labels: enhancement, needs review, bot is merging ⏳

#1221 [FIX] fieldservice: order check for holiday
  fieldservice/models/fsm_order.py
Labels: bug, needs review, bot is merging ⏳

#1219 [FIX] fieldservice_account_analytic: automatically fill Contact in FSM Order
  fieldservice_account_analytic/README.rst
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_account_analytic/readme/CONTRIBUTORS.rst
  fieldservice_account_analytic/static/description/index.html
  fieldservice_stock_account/tests/test_fsm_stock_account.py
Labels: bug, needs review, approved, bot is merging ⏳

#1222 [MIG][18.0] base_territory
  base_territory/README.rst
  base_territory/__init__.py
  base_territory/__manifest__.py
  base_territory/demo/base_territory_demo.xml
  base_territory/i18n/base_territory.pot
  base_territory/i18n/es.po
  base_territory/i18n/es_AR.po
  base_territory/i18n/it.po
  base_territory/i18n/pt_BR.po
  base_territory/i18n/tr.po
  base_territory/models/__init__.py
  base_territory/models/res_branch.py
  base_territory/models/res_country.py
  base_territory/models/res_district.py
  base_territory/models/res_region.py
  base_territory/models/res_territory.py
  base_territory/pyproject.toml
  base_territory/readme/CONTRIBUTORS.md
  base_territory/readme/CREDITS.md
  base_territory/readme/DESCRIPTION.md
  base_territory/readme/USAGE.md
  base_territory/security/ir.model.access.csv
  base_territory/static/description/icon.png
  base_territory/static/description/index.html
  base_territory/tests/__init__.py
  base_territory/tests/test_res_branch.py
  base_territory/tests/test_res_country.py
  base_territory/tests/test_res_district.py
  base_territory/tests/test_res_region.py
  base_territory/tests/test_res_territory.py
  base_territory/views/menu.xml
  base_territory/views/res_branch.xml
  base_territory/views/res_country.xml
  base_territory/views/res_district.xml
  base_territory/views/res_region.xml
  base_territory/views/res_territory.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1242 [17.0][FIX] fieldservice: buttons under stage_id cond. not displayed
  fieldservice/views/fsm_order.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1224 [16.0][MIG] fieldservice_portal: Migration to 16.0
  fieldservice_portal/README.rst
  fieldservice_portal/__init__.py
  fieldservice_portal/__manifest__.py
  fieldservice_portal/controllers/__init__.py
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/demo/fsm_location_demo.xml
  fieldservice_portal/demo/fsm_order_demo.xml
  fieldservice_portal/readme/CONTRIBUTORS.rst
  fieldservice_portal/readme/DESCRIPTION.rst
  fieldservice_portal/security/ir.model.access.csv
  fieldservice_portal/security/portal_security.xml
  fieldservice_portal/static/description/index.html
  fieldservice_portal/static/src/js/fsm_order_portal.esm.js
  fieldservice_portal/tests/__init__.py
  fieldservice_portal/tests/test_portal.py
  fieldservice_portal/views/fsm_order_template.xml
  fieldservice_portal/views/portal_template.xml
  setup/fieldservice_portal/odoo/addons/fieldservice_portal
  setup/fieldservice_portal/setup.py
Labels: needs review, approved, migration, bot is merging ⏳
