Repository OCA/field-service, pull requests merged in 2024-09, with the labels that each got.

#1206 [17.0][MIG] fieldservice_stage_server_action
  fieldservice_stage_server_action/README.rst
  fieldservice_stage_server_action/__init__.py
  fieldservice_stage_server_action/__manifest__.py
  fieldservice_stage_server_action/data/base_automation.xml
  fieldservice_stage_server_action/data/fsm_stage.xml
  fieldservice_stage_server_action/data/ir_server_action.xml
  fieldservice_stage_server_action/i18n/de.po
  fieldservice_stage_server_action/i18n/es.po
  fieldservice_stage_server_action/i18n/es_AR.po
  fieldservice_stage_server_action/i18n/es_CL.po
  fieldservice_stage_server_action/i18n/fieldservice_stage_server_action.pot
  fieldservice_stage_server_action/i18n/it.po
  fieldservice_stage_server_action/i18n/pt_BR.po
  fieldservice_stage_server_action/models/__init__.py
  fieldservice_stage_server_action/models/fsm_stage.py
  fieldservice_stage_server_action/pyproject.toml
  fieldservice_stage_server_action/readme/CONFIGURE.md
  fieldservice_stage_server_action/readme/CONTRIBUTORS.md
  fieldservice_stage_server_action/readme/DESCRIPTION.md
  fieldservice_stage_server_action/readme/USAGE.md
  fieldservice_stage_server_action/static/description/icon.png
  fieldservice_stage_server_action/static/description/index.html
  fieldservice_stage_server_action/views/fsm_stage.xml
Labels: approved, ready to merge, bot is merging ⏳

#1194 [16.0] [FIX] fieldservice: schedule date methods
  fieldservice/models/fsm_order.py
Labels: bug, needs review, approved, bot is merging ⏳

#1201 [15.0][FIX] fieldservice: Manual location creation
  fieldservice/views/fsm_person.xml
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1202 [16.0][FIX] fieldservice: Manual location creation
  fieldservice/views/fsm_person.xml
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1200 [15.0][FIX] fieldservice: Fix manual location creation issue #1166
  fieldservice/views/fsm_location.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1205 [17.0][MIG] fieldservice_equipment_stock: Migration to 17.0
  fieldservice_equipment_stock/README.rst
  fieldservice_equipment_stock/__init__.py
  fieldservice_equipment_stock/__manifest__.py
  fieldservice_equipment_stock/i18n/es.po
  fieldservice_equipment_stock/i18n/es_AR.po
  fieldservice_equipment_stock/i18n/fieldservice_equipment_stock.pot
  fieldservice_equipment_stock/i18n/it.po
  fieldservice_equipment_stock/i18n/pt_BR.po
  fieldservice_equipment_stock/models/__init__.py
  fieldservice_equipment_stock/models/fsm_equipment.py
  fieldservice_equipment_stock/models/product_template.py
  fieldservice_equipment_stock/models/stock_lot.py
  fieldservice_equipment_stock/models/stock_move.py
  fieldservice_equipment_stock/models/stock_picking_type.py
  fieldservice_equipment_stock/pyproject.toml
  fieldservice_equipment_stock/readme/CONFIGURE.md
  fieldservice_equipment_stock/readme/CONTRIBUTORS.md
  fieldservice_equipment_stock/readme/CREDITS.md
  fieldservice_equipment_stock/readme/DESCRIPTION.md
  fieldservice_equipment_stock/readme/ROADMAP.md
  fieldservice_equipment_stock/readme/USAGE.md
  fieldservice_equipment_stock/security/ir.model.access.csv
  fieldservice_equipment_stock/static/description/icon.png
  fieldservice_equipment_stock/static/description/index.html
  fieldservice_equipment_stock/tests/__init__.py
  fieldservice_equipment_stock/tests/test_fsm_equipment.py
  fieldservice_equipment_stock/tests/test_stock_move.py
  fieldservice_equipment_stock/views/fsm_equipment.xml
  fieldservice_equipment_stock/views/product_template.xml
  fieldservice_equipment_stock/views/stock_lot.xml
  fieldservice_equipment_stock/views/stock_picking_type.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1211 [17.0][MIG] fieldservice_activity
  fieldservice_activity/README.rst
  fieldservice_activity/__init__.py
  fieldservice_activity/__manifest__.py
  fieldservice_activity/i18n/es.po
  fieldservice_activity/i18n/es_AR.po
  fieldservice_activity/i18n/es_CL.po
  fieldservice_activity/i18n/fieldservice_activity.pot
  fieldservice_activity/i18n/it.po
  fieldservice_activity/i18n/pt_BR.po
  fieldservice_activity/i18n/pt_PT.po
  fieldservice_activity/models/__init__.py
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/models/fsm_order.py
  fieldservice_activity/models/fsm_template.py
  fieldservice_activity/pyproject.toml
  fieldservice_activity/readme/CONFIGURE.md
  fieldservice_activity/readme/CONTRIBUTORS.md
  fieldservice_activity/readme/CREDITS.md
  fieldservice_activity/readme/DESCRIPTION.md
  fieldservice_activity/readme/USAGE.md
  fieldservice_activity/security/ir.model.access.csv
  fieldservice_activity/static/description/icon.png
  fieldservice_activity/static/description/index.html
  fieldservice_activity/tests/__init__.py
  fieldservice_activity/tests/test_fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1214 [FIX] fieldservice_stage_server_action: run server action on stage change
  fieldservice_stage_server_action/models/__init__.py
  fieldservice_stage_server_action/models/fsm_order.py
  fieldservice_stage_server_action/tests/__init__.py
  fieldservice_stage_server_action/tests/test_fsm_order_run_action.py
Labels: bug, needs review, approved, bot is merging ⏳

#1212 [17.0][MIG] fieldservice_sale_stock: Migration to 17.0
  fieldservice_sale_stock/README.rst
  fieldservice_sale_stock/__init__.py
  fieldservice_sale_stock/__manifest__.py
  fieldservice_sale_stock/i18n/es.po
  fieldservice_sale_stock/i18n/es_AR.po
  fieldservice_sale_stock/i18n/es_CL.po
  fieldservice_sale_stock/i18n/fieldservice_sale_stock.pot
  fieldservice_sale_stock/i18n/it.po
  fieldservice_sale_stock/i18n/pt_BR.po
  fieldservice_sale_stock/models/__init__.py
  fieldservice_sale_stock/models/sale_order.py
  fieldservice_sale_stock/pyproject.toml
  fieldservice_sale_stock/readme/CONFIGURE.md
  fieldservice_sale_stock/readme/CONTRIBUTORS.md
  fieldservice_sale_stock/readme/DESCRIPTION.md
  fieldservice_sale_stock/readme/ROADMAP.md
  fieldservice_sale_stock/readme/USAGE.md
  fieldservice_sale_stock/static/description/icon.png
  fieldservice_sale_stock/static/description/index.html
  fieldservice_sale_stock/tests/__init__.py
  fieldservice_sale_stock/tests/test_fsm_sale_order.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1209 [17.0][MIG] fieldservice_repair: Migration to 17.0
  fieldservice_repair/README.rst
  fieldservice_repair/__init__.py
  fieldservice_repair/__manifest__.py
  fieldservice_repair/data/fsm_order_type.xml
  fieldservice_repair/i18n/de.po
  fieldservice_repair/i18n/es.po
  fieldservice_repair/i18n/es_AR.po
  fieldservice_repair/i18n/fieldservice_repair.pot
  fieldservice_repair/i18n/it.po
  fieldservice_repair/i18n/pt_BR.po
  fieldservice_repair/models/__init__.py
  fieldservice_repair/models/fsm_order.py
  fieldservice_repair/models/fsm_order_type.py
  fieldservice_repair/pyproject.toml
  fieldservice_repair/readme/CONFIGURE.md
  fieldservice_repair/readme/CONTRIBUTORS.md
  fieldservice_repair/readme/CREDITS.md
  fieldservice_repair/readme/DESCRIPTION.md
  fieldservice_repair/readme/INSTALL.md
  fieldservice_repair/readme/ROADMAP.md
  fieldservice_repair/readme/USAGE.md
  fieldservice_repair/static/description/icon.png
  fieldservice_repair/static/description/index.html
  fieldservice_repair/tests/__init__.py
  fieldservice_repair/tests/test_fsm_repair.py
  fieldservice_repair/views/fsm_order_view.xml
Labels: needs fixing, needs review, approved, migration, bot is merging ⏳

#1190 [17.0][MIG] fieldservice_geoengine: Migration to 17.0
  .github/workflows/test.yml
  fieldservice_geoengine/README.rst
  fieldservice_geoengine/__init__.py
  fieldservice_geoengine/__manifest__.py
  fieldservice_geoengine/i18n/de.po
  fieldservice_geoengine/i18n/es.po
  fieldservice_geoengine/i18n/es_AR.po
  fieldservice_geoengine/i18n/es_CL.po
  fieldservice_geoengine/i18n/fieldservice_geoengine.pot
  fieldservice_geoengine/i18n/fr_FR.po
  fieldservice_geoengine/i18n/it.po
  fieldservice_geoengine/i18n/pt_BR.po
  fieldservice_geoengine/models/__init__.py
  fieldservice_geoengine/models/fsm_location.py
  fieldservice_geoengine/models/fsm_order.py
  fieldservice_geoengine/models/vector_layer.py
  fieldservice_geoengine/pyproject.toml
  fieldservice_geoengine/readme/CONFIGURE.md
  fieldservice_geoengine/readme/CONTRIBUTORS.md
  fieldservice_geoengine/readme/CREDITS.md
  fieldservice_geoengine/readme/DESCRIPTION.md
  fieldservice_geoengine/readme/INSTALL.md
  fieldservice_geoengine/readme/ROADMAP.md
  fieldservice_geoengine/readme/USAGE.md
  fieldservice_geoengine/security/res_groups.xml
  fieldservice_geoengine/static/description/icon.png
  fieldservice_geoengine/static/description/index.html
  fieldservice_geoengine/static/src/js/views/geoengine/geoengine_renderer/geoengine_renderer.esm.js
  fieldservice_geoengine/tests/__init__.py
  fieldservice_geoengine/tests/test_fsm_location.py
  fieldservice_geoengine/views/fsm_location.xml
  fieldservice_geoengine/views/fsm_order.xml
  fieldservice_geoengine/views/fsm_team.xml
Labels: needs review, approved, migration, bot is merging ⏳, Blocked by dependency

#1215 [17.0][MIG] fieldservice_project
  fieldservice_project/README.rst
  fieldservice_project/__init__.py
  fieldservice_project/__manifest__.py
  fieldservice_project/i18n/de.po
  fieldservice_project/i18n/es.po
  fieldservice_project/i18n/es_AR.po
  fieldservice_project/i18n/es_CL.po
  fieldservice_project/i18n/fieldservice_project.pot
  fieldservice_project/i18n/fr.po
  fieldservice_project/i18n/it.po
  fieldservice_project/i18n/pt_BR.po
  fieldservice_project/models/__init__.py
  fieldservice_project/models/fsm_location.py
  fieldservice_project/models/fsm_order.py
  fieldservice_project/models/fsm_team.py
  fieldservice_project/models/project.py
  fieldservice_project/models/project_task.py
  fieldservice_project/pyproject.toml
  fieldservice_project/readme/CONTRIBUTORS.md
  fieldservice_project/readme/CREDITS.md
  fieldservice_project/readme/DESCRIPTION.md
  fieldservice_project/readme/ROADMAP.md
  fieldservice_project/readme/USAGE.md
  fieldservice_project/security/ir.model.access.csv
  fieldservice_project/static/description/icon.png
  fieldservice_project/static/description/icon.svg
  fieldservice_project/static/description/index.html
  fieldservice_project/static/src/scss/project_column.scss
  fieldservice_project/tests/__init__.py
  fieldservice_project/tests/common.py
  fieldservice_project/tests/test_fsm_location.py
  fieldservice_project/tests/test_fsm_order.py
  fieldservice_project/tests/test_project.py
  fieldservice_project/tests/test_project_task.py
  fieldservice_project/views/fsm_location_views.xml
  fieldservice_project/views/fsm_order_views.xml
  fieldservice_project/views/fsm_team.xml
  fieldservice_project/views/project_task_views.xml
  fieldservice_project/views/project_views.xml
Labels: needs review, approved, migration, bot is merging ⏳
