Repository OCA/field-service, pull requests merged in 2024-04, with the labels that each got.

#1170 [14.0] [REF] fieldservice_recurring: move rruleset params in methods
  fieldservice_recurring/models/fsm_recurring.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1167 [14.0][FIX] fieldservice_recurring: company required on recurring
  fieldservice_recurring/models/fsm_recurring.py
Labels: bug, needs review, approved, bot is merging ⏳

#1168 [16.0][MIG] fieldservice_isp_flow: Migration to 16.0
  fieldservice_isp_flow/README.rst
  fieldservice_isp_flow/__init__.py
  fieldservice_isp_flow/__manifest__.py
  fieldservice_isp_flow/data/fsm_stage.xml
  fieldservice_isp_flow/i18n/de.po
  fieldservice_isp_flow/i18n/es.po
  fieldservice_isp_flow/i18n/es_AR.po
  fieldservice_isp_flow/i18n/es_CL.po
  fieldservice_isp_flow/i18n/fieldservice_isp_flow.pot
  fieldservice_isp_flow/i18n/it.po
  fieldservice_isp_flow/i18n/pt_BR.po
  fieldservice_isp_flow/models/__init__.py
  fieldservice_isp_flow/models/fsm_order.py
  fieldservice_isp_flow/readme/CONFIGURE.rst
  fieldservice_isp_flow/readme/CONTRIBUTORS.rst
  fieldservice_isp_flow/readme/CREDITS.rst
  fieldservice_isp_flow/readme/DESCRIPTION.rst
  fieldservice_isp_flow/readme/ROADMAP.rst
  fieldservice_isp_flow/readme/USAGE.rst
  fieldservice_isp_flow/static/description/icon.png
  fieldservice_isp_flow/static/description/index.html
  fieldservice_isp_flow/tests/__init__.py
  fieldservice_isp_flow/tests/test_fsm_isp_flow.py
  fieldservice_isp_flow/views/fsm_order.xml
  setup/fieldservice_isp_flow/odoo/addons/fieldservice_isp_flow
  setup/fieldservice_isp_flow/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#1162 [16.0][FIX] fieldservice: Fix HTML field declaration
  fieldservice/models/fsm_location.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_template.py
  fieldservice/readme/CONTRIBUTORS.rst
  fieldservice/views/fsm_location.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_template.xml
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1163 [16.0][FIX] fieldservice: Fix manual location creation
  fieldservice/views/fsm_location.xml
Labels: bug, needs review, bot is merging ⏳

#1164 [16.0][FIX] fieldservice: Fix location partner type
  fieldservice/models/fsm_location.py
  fieldservice/models/res_partner.py
  fieldservice/tests/test_fsm_location.py
  fieldservice/tests/test_fsm_wizard.py
  fieldservice/wizard/fsm_wizard.py
Labels: bug, needs review, bot is merging ⏳

#1173 [17.0][MIG] fieldservice_crm: Migration to 17.0
  fieldservice_crm/README.rst
  fieldservice_crm/__init__.py
  fieldservice_crm/__manifest__.py
  fieldservice_crm/i18n/de.po
  fieldservice_crm/i18n/es.po
  fieldservice_crm/i18n/es_AR.po
  fieldservice_crm/i18n/es_CL.po
  fieldservice_crm/i18n/fieldservice_crm.pot
  fieldservice_crm/i18n/fr.po
  fieldservice_crm/i18n/it.po
  fieldservice_crm/i18n/pt_BR.po
  fieldservice_crm/models/__init__.py
  fieldservice_crm/models/crm_lead.py
  fieldservice_crm/models/fsm_location.py
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/pyproject.toml
  fieldservice_crm/readme/CONFIGURE.md
  fieldservice_crm/readme/CONTRIBUTORS.md
  fieldservice_crm/readme/CREDITS.md
  fieldservice_crm/readme/DESCRIPTION.md
  fieldservice_crm/readme/INSTALL.md
  fieldservice_crm/readme/ROADMAP.md
  fieldservice_crm/readme/USAGE.md
  fieldservice_crm/security/ir.model.access.csv
  fieldservice_crm/static/description/icon.png
  fieldservice_crm/static/description/index.html
  fieldservice_crm/tests/__init__.py
  fieldservice_crm/tests/test_fsm_crm.py
  fieldservice_crm/views/crm_lead.xml
  fieldservice_crm/views/fsm_location.xml
  fieldservice_crm/views/fsm_order.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1165 [16.0][IMP] fieldservice: Set location parent to owner
  fieldservice/models/fsm_location.py
  fieldservice/tests/test_fsm_location.py
  fieldservice/wizard/fsm_wizard.py
Labels: enhancement, needs review, bot is merging ⏳

#1158 [17.0][MIG] fieldservice_stock: Migration to 17.0
  fieldservice_stock/README.rst
  fieldservice_stock/__init__.py
  fieldservice_stock/__manifest__.py
  fieldservice_stock/data/fsm_stock_data.xml
  fieldservice_stock/hooks.py
  fieldservice_stock/i18n/de.po
  fieldservice_stock/i18n/es.po
  fieldservice_stock/i18n/es_AR.po
  fieldservice_stock/i18n/es_CL.po
  fieldservice_stock/i18n/fieldservice_stock.pot
  fieldservice_stock/i18n/fr.po
  fieldservice_stock/i18n/it.po
  fieldservice_stock/i18n/pt_BR.po
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_location.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/fsm_wizard.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/res_territory.py
  fieldservice_stock/models/stock_move.py
  fieldservice_stock/models/stock_picking.py
  fieldservice_stock/models/stock_rule.py
  fieldservice_stock/pyproject.toml
  fieldservice_stock/readme/CONFIGURE.md
  fieldservice_stock/readme/CONTRIBUTORS.md
  fieldservice_stock/readme/CREDITS.md
  fieldservice_stock/readme/DESCRIPTION.md
  fieldservice_stock/readme/INSTALL.md
  fieldservice_stock/readme/ROADMAP.md
  fieldservice_stock/readme/USAGE.md
  fieldservice_stock/security/ir.model.access.csv
  fieldservice_stock/static/description/icon.png
  fieldservice_stock/static/description/index.html
  fieldservice_stock/tests/__init__.py
  fieldservice_stock/tests/test_fsm_stock.py
  fieldservice_stock/tests/test_fsm_wizard.py
  fieldservice_stock/views/fsm_location.xml
  fieldservice_stock/views/fsm_order.xml
  fieldservice_stock/views/res_territory.xml
  fieldservice_stock/views/stock.xml
  fieldservice_stock/views/stock_picking.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1160 [16.0][FIX] fieldservice_sale: Fix sale order line create method
  fieldservice_sale/models/sale_order_line.py
Labels: bug, approved, bot is merging ⏳

#1129 [16.0][MIG] fieldservice equipment stock: Migration to 16.0
  fieldservice_equipment_stock/README.rst
  fieldservice_equipment_stock/__init__.py
  fieldservice_equipment_stock/__manifest__.py
  fieldservice_equipment_stock/i18n/es.po
  fieldservice_equipment_stock/i18n/es_AR.po
  fieldservice_equipment_stock/i18n/fieldservice_equipment_stock.pot
  fieldservice_equipment_stock/i18n/it.po
  fieldservice_equipment_stock/i18n/pt_BR.po
  fieldservice_equipment_stock/models/__init__.py
  fieldservice_equipment_stock/models/fsm_equipment.py
  fieldservice_equipment_stock/models/product_template.py
  fieldservice_equipment_stock/models/stock_lot.py
  fieldservice_equipment_stock/models/stock_move.py
  fieldservice_equipment_stock/models/stock_picking_type.py
  fieldservice_equipment_stock/readme/CONFIGURE.rst
  fieldservice_equipment_stock/readme/CONTRIBUTORS.rst
  fieldservice_equipment_stock/readme/CREDITS.rst
  fieldservice_equipment_stock/readme/DESCRIPTION.rst
  fieldservice_equipment_stock/readme/ROADMAP.rst
  fieldservice_equipment_stock/readme/USAGE.rst
  fieldservice_equipment_stock/security/ir.model.access.csv
  fieldservice_equipment_stock/static/description/icon.png
  fieldservice_equipment_stock/static/description/index.html
  fieldservice_equipment_stock/tests/__init__.py
  fieldservice_equipment_stock/tests/test_fsm_equipment.py
  fieldservice_equipment_stock/tests/test_stock_move.py
  fieldservice_equipment_stock/views/fsm_equipment.xml
  fieldservice_equipment_stock/views/product_template.xml
  fieldservice_equipment_stock/views/stock_lot.xml
  fieldservice_equipment_stock/views/stock_picking_type.xml
  setup/fieldservice_equipment_stock/odoo/addons/fieldservice_equipment_stock
  setup/fieldservice_equipment_stock/setup.py
Labels: needs review, migration, bot is merging ⏳

#1174 [17.0][MIG] fieldservice_recurring: Migration to 17.0
  fieldservice_recurring/README.rst
  fieldservice_recurring/__init__.py
  fieldservice_recurring/__manifest__.py
  fieldservice_recurring/data/ir_sequence.xml
  fieldservice_recurring/data/recurring_cron.xml
  fieldservice_recurring/demo/frequency_demo.xml
  fieldservice_recurring/demo/frequency_set_demo.xml
  fieldservice_recurring/demo/recur_template_demo.xml
  fieldservice_recurring/i18n/de.po
  fieldservice_recurring/i18n/es.po
  fieldservice_recurring/i18n/es_AR.po
  fieldservice_recurring/i18n/es_CL.po
  fieldservice_recurring/i18n/fieldservice_recurring.pot
  fieldservice_recurring/i18n/it.po
  fieldservice_recurring/i18n/pt_BR.po
  fieldservice_recurring/i18n/tr.po
  fieldservice_recurring/models/__init__.py
  fieldservice_recurring/models/fsm_frequency.py
  fieldservice_recurring/models/fsm_frequency_set.py
  fieldservice_recurring/models/fsm_order.py
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_recurring/models/fsm_recurring_template.py
  fieldservice_recurring/models/fsm_team.py
  fieldservice_recurring/pyproject.toml
  fieldservice_recurring/readme/CONFIGURE.md
  fieldservice_recurring/readme/CONTRIBUTORS.md
  fieldservice_recurring/readme/CREDITS.md
  fieldservice_recurring/readme/DESCRIPTION.md
  fieldservice_recurring/readme/INSTALL.md
  fieldservice_recurring/readme/ROADMAP.md
  fieldservice_recurring/readme/USAGE.md
  fieldservice_recurring/security/ir.model.access.csv
  fieldservice_recurring/security/recurring_security.xml
  fieldservice_recurring/security/res_groups.xml
  fieldservice_recurring/static/description/icon.png
  fieldservice_recurring/static/description/index.html
  fieldservice_recurring/tests/__init__.py
  fieldservice_recurring/tests/test_fsm_recurring.py
  fieldservice_recurring/views/fsm_frequency.xml
  fieldservice_recurring/views/fsm_frequency_set.xml
  fieldservice_recurring/views/fsm_order.xml
  fieldservice_recurring/views/fsm_recurring.xml
  fieldservice_recurring/views/fsm_recurring_template.xml
  fieldservice_recurring/views/fsm_team.xml
  fieldservice_route/views/fsm_route_dayroute.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#1175 [17.0][MIG] fieldservice_vehicle: Migration to 17.0
  fieldservice_vehicle/README.rst
  fieldservice_vehicle/__init__.py
  fieldservice_vehicle/__manifest__.py
  fieldservice_vehicle/i18n/de.po
  fieldservice_vehicle/i18n/es.po
  fieldservice_vehicle/i18n/es_AR.po
  fieldservice_vehicle/i18n/es_CL.po
  fieldservice_vehicle/i18n/fieldservice_vehicle.pot
  fieldservice_vehicle/i18n/it.po
  fieldservice_vehicle/i18n/pt_BR.po
  fieldservice_vehicle/models/__init__.py
  fieldservice_vehicle/models/fsm_order.py
  fieldservice_vehicle/models/fsm_person.py
  fieldservice_vehicle/models/fsm_vehicle.py
  fieldservice_vehicle/pyproject.toml
  fieldservice_vehicle/readme/CONFIGURE.md
  fieldservice_vehicle/readme/CONTRIBUTORS.md
  fieldservice_vehicle/readme/CREDITS.md
  fieldservice_vehicle/readme/DESCRIPTION.md
  fieldservice_vehicle/readme/INSTALL.md
  fieldservice_vehicle/readme/ROADMAP.md
  fieldservice_vehicle/readme/USAGE.md
  fieldservice_vehicle/security/ir.model.access.csv
  fieldservice_vehicle/security/res_groups.xml
  fieldservice_vehicle/static/description/icon.png
  fieldservice_vehicle/static/description/index.html
  fieldservice_vehicle/tests/__init__.py
  fieldservice_vehicle/tests/test_fsm_vehicle.py
  fieldservice_vehicle/views/fsm_order.xml
  fieldservice_vehicle/views/fsm_person.xml
  fieldservice_vehicle/views/fsm_vehicle.xml
  fieldservice_vehicle/views/menu.xml
Labels: needs review, migration, bot is merging ⏳

#1182 [14.0][FIX]fieldservice_stage_validation: validate only with explicit fields
  fieldservice_stage_validation/models/validate_utils.py
Labels: approved, bot is merging ⏳

#1181 [14.0] [FIX] fieldservice_activity: activities string warning
  fieldservice_activity/models/fsm_order.py
Labels: approved, bot is merging ⏳

#1155 [14.0][ADD] fieldservice_survey: add new module
  fieldservice_survey/README.rst
  fieldservice_survey/__init__.py
  fieldservice_survey/__manifest__.py
  fieldservice_survey/controllers/__init__.py
  fieldservice_survey/controllers/main.py
  fieldservice_survey/data/fsm_order_survey_data.xml
  fieldservice_survey/data/mail_data.xml
  fieldservice_survey/models/__init__.py
  fieldservice_survey/models/fsm_order.py
  fieldservice_survey/models/res_company.py
  fieldservice_survey/models/res_config_settings.py
  fieldservice_survey/models/survey_survey.py
  fieldservice_survey/models/survey_user_input.py
  fieldservice_survey/readme/CONTRIBUTORS.rst
  fieldservice_survey/readme/DESCRIPTION.rst
  fieldservice_survey/readme/ROADMAP.rst
  fieldservice_survey/readme/USAGE.rst
  fieldservice_survey/security/ir.model.access.csv
  fieldservice_survey/security/res_groups.xml
  fieldservice_survey/static/description/icon.png
  fieldservice_survey/static/description/index.html
  fieldservice_survey/tests/__init__.py
  fieldservice_survey/tests/test_fsm_order.py
  fieldservice_survey/tests/test_fsm_order_survey_submit.py
  fieldservice_survey/views/fsm_order.xml
  fieldservice_survey/views/res_config_settings.xml
  fieldservice_survey/views/survey_survey.xml
  fieldservice_survey/views/survey_templates_statistics.xml
  fieldservice_survey/views/survey_user_input.xml
  fieldservice_survey/wizard/__init__.py
  fieldservice_survey/wizard/fsm_order_survey_submit.py
  fieldservice_survey/wizard/fsm_order_survey_submit.xml
  setup/fieldservice_survey/odoo/addons/fieldservice_survey
  setup/fieldservice_survey/setup.py
Labels: approved, bot is merging ⏳

#1176 [17.0][MIG] fieldservice_account_analytic: Migration to 17.0
  fieldservice_account_analytic/README.rst
  fieldservice_account_analytic/__init__.py
  fieldservice_account_analytic/__manifest__.py
  fieldservice_account_analytic/data/ir_rule.xml
  fieldservice_account_analytic/demo/fsm_location.xml
  fieldservice_account_analytic/i18n/es.po
  fieldservice_account_analytic/i18n/es_AR.po
  fieldservice_account_analytic/i18n/es_CL.po
  fieldservice_account_analytic/i18n/fieldservice_account_analytic.pot
  fieldservice_account_analytic/i18n/it.po
  fieldservice_account_analytic/i18n/pt_BR.po
  fieldservice_account_analytic/i18n/pt_PT.po
  fieldservice_account_analytic/i18n/tr.po
  fieldservice_account_analytic/init_hook.py
  fieldservice_account_analytic/models/__init__.py
  fieldservice_account_analytic/models/account_move.py
  fieldservice_account_analytic/models/analytic_account.py
  fieldservice_account_analytic/models/fsm_location.py
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_account_analytic/models/res_company.py
  fieldservice_account_analytic/models/res_config_settings.py
  fieldservice_account_analytic/models/res_partner.py
  fieldservice_account_analytic/pyproject.toml
  fieldservice_account_analytic/readme/CONFIGURE.md
  fieldservice_account_analytic/readme/CONTRIBUTORS.md
  fieldservice_account_analytic/readme/CREDITS.md
  fieldservice_account_analytic/readme/DESCRIPTION.md
  fieldservice_account_analytic/readme/INSTALL.md
  fieldservice_account_analytic/readme/USAGE.md
  fieldservice_account_analytic/report/fsm_order_report_template.xml
  fieldservice_account_analytic/security/ir.model.access.csv
  fieldservice_account_analytic/static/description/icon.png
  fieldservice_account_analytic/static/description/index.html
  fieldservice_account_analytic/tests/__init__.py
  fieldservice_account_analytic/tests/test_fsm_account_wizard.py
  fieldservice_account_analytic/views/fsm_location.xml
  fieldservice_account_analytic/views/fsm_order.xml
  fieldservice_account_analytic/views/res_config_settings.xml
  fieldservice_account_analytic/wizard/__init__.py
  fieldservice_account_analytic/wizard/fsm_wizard.py
Labels: bot is merging ⏳

#1180 [17.0][MIG] fieldservice_isp_flow: Migration to 17.0
  fieldservice_isp_flow/README.rst
  fieldservice_isp_flow/__init__.py
  fieldservice_isp_flow/__manifest__.py
  fieldservice_isp_flow/data/fsm_stage.xml
  fieldservice_isp_flow/i18n/de.po
  fieldservice_isp_flow/i18n/es.po
  fieldservice_isp_flow/i18n/es_AR.po
  fieldservice_isp_flow/i18n/es_CL.po
  fieldservice_isp_flow/i18n/fieldservice_isp_flow.pot
  fieldservice_isp_flow/i18n/it.po
  fieldservice_isp_flow/i18n/pt_BR.po
  fieldservice_isp_flow/models/__init__.py
  fieldservice_isp_flow/models/fsm_order.py
  fieldservice_isp_flow/pyproject.toml
  fieldservice_isp_flow/readme/CONFIGURE.md
  fieldservice_isp_flow/readme/CONTRIBUTORS.md
  fieldservice_isp_flow/readme/CREDITS.md
  fieldservice_isp_flow/readme/DESCRIPTION.md
  fieldservice_isp_flow/readme/ROADMAP.md
  fieldservice_isp_flow/readme/USAGE.md
  fieldservice_isp_flow/static/description/icon.png
  fieldservice_isp_flow/static/description/index.html
  fieldservice_isp_flow/tests/__init__.py
  fieldservice_isp_flow/tests/test_fsm_isp_flow.py
  fieldservice_isp_flow/views/fsm_order.xml
Labels: bot is merging ⏳

#1178 [17.0][MIG] fieldservice_size: Migration to 17.0
  fieldservice_size/README.rst
  fieldservice_size/__init__.py
  fieldservice_size/__manifest__.py
  fieldservice_size/i18n/es.po
  fieldservice_size/i18n/es_AR.po
  fieldservice_size/i18n/fieldservice_size.pot
  fieldservice_size/i18n/it.po
  fieldservice_size/i18n/pt_BR.po
  fieldservice_size/models/__init__.py
  fieldservice_size/models/fsm_location.py
  fieldservice_size/models/fsm_location_size.py
  fieldservice_size/models/fsm_order.py
  fieldservice_size/models/fsm_size.py
  fieldservice_size/pyproject.toml
  fieldservice_size/readme/CONFIGURE.md
  fieldservice_size/readme/CONTRIBUTORS.md
  fieldservice_size/readme/DESCRIPTION.md
  fieldservice_size/readme/ROADMAP.md
  fieldservice_size/readme/USAGE.md
  fieldservice_size/security/ir.model.access.csv
  fieldservice_size/static/description/icon.png
  fieldservice_size/static/description/index.html
  fieldservice_size/tests/__init__.py
  fieldservice_size/tests/test_fsm_order.py
  fieldservice_size/views/fsm_location.xml
  fieldservice_size/views/fsm_order.xml
  fieldservice_size/views/fsm_size.xml
  fieldservice_size/views/menu.xml
Labels: bot is merging ⏳

#1179 [17.0][MIG] fieldservice_stage_validation: Migration to 17.0
  fieldservice_stage_validation/README.rst
  fieldservice_stage_validation/__init__.py
  fieldservice_stage_validation/__manifest__.py
  fieldservice_stage_validation/i18n/es.po
  fieldservice_stage_validation/i18n/es_AR.po
  fieldservice_stage_validation/i18n/fieldservice_stage_validation.pot
  fieldservice_stage_validation/i18n/fr_FR.po
  fieldservice_stage_validation/i18n/it.po
  fieldservice_stage_validation/i18n/pt_BR.po
  fieldservice_stage_validation/i18n/pt_PT.po
  fieldservice_stage_validation/i18n/tr.po
  fieldservice_stage_validation/models/__init__.py
  fieldservice_stage_validation/models/fsm_equipment.py
  fieldservice_stage_validation/models/fsm_location.py
  fieldservice_stage_validation/models/fsm_order.py
  fieldservice_stage_validation/models/fsm_person.py
  fieldservice_stage_validation/models/fsm_stage.py
  fieldservice_stage_validation/models/validate_utils.py
  fieldservice_stage_validation/pyproject.toml
  fieldservice_stage_validation/readme/CONFIGURE.md
  fieldservice_stage_validation/readme/CONTRIBUTORS.md
  fieldservice_stage_validation/readme/DESCRIPTION.md
  fieldservice_stage_validation/readme/ROADMAP.md
  fieldservice_stage_validation/readme/USAGE.md
  fieldservice_stage_validation/static/description/icon.png
  fieldservice_stage_validation/static/description/index.html
  fieldservice_stage_validation/tests/__init__.py
  fieldservice_stage_validation/tests/test_fsm_stage_validation.py
  fieldservice_stage_validation/views/fsm_stage.xml
Labels: approved, ready to merge, bot is merging ⏳
