Repository OCA/field-service, pull requests merged in 2024-12, with the labels that each got.

#1265 [17.0] [FIX] fieldservice_activity: deprecated field "states"
  fieldservice_activity/models/fsm_activity.py
  fieldservice_activity/views/fsm_order.xml
  fieldservice_activity/views/fsm_template.xml
Labels: bug, needs review, approved, bot is merging ⏳

#1252 [17.0][MIG] fieldservice_portal: Migration to 17.0
  fieldservice_portal/README.rst
  fieldservice_portal/__init__.py
  fieldservice_portal/__manifest__.py
  fieldservice_portal/controllers/__init__.py
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/demo/fsm_location_demo.xml
  fieldservice_portal/demo/fsm_order_demo.xml
  fieldservice_portal/i18n/ca.po
  fieldservice_portal/i18n/es.po
  fieldservice_portal/i18n/fieldservice_portal.pot
  fieldservice_portal/pyproject.toml
  fieldservice_portal/readme/CONTRIBUTORS.md
  fieldservice_portal/readme/DESCRIPTION.md
  fieldservice_portal/security/ir.model.access.csv
  fieldservice_portal/security/portal_security.xml
  fieldservice_portal/static/description/icon.png
  fieldservice_portal/static/description/index.html
  fieldservice_portal/static/src/img/fsmorder.svg
  fieldservice_portal/static/src/js/fsm_order_portal.esm.js
  fieldservice_portal/tests/__init__.py
  fieldservice_portal/tests/test_portal.py
  fieldservice_portal/views/fsm_order_template.xml
  fieldservice_portal/views/portal_template.xml
Labels: needs review, approved, migration, bot is merging ⏳

#1274 [IMP] fieldservice_recurring: populate team_id from order template
  fieldservice_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1280 [17.0] [REM] fieldservice: unused `_get_stage_color` method
  fieldservice/models/fsm_order.py
  fieldservice/tests/test_fsm_order.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1278 [17.0] [IMP] fieldservice: implement check_company on related fields
  fieldservice/models/fsm_equipment.py
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_stage.py
  fieldservice/models/fsm_tag.py
  fieldservice/models/fsm_team.py
  fieldservice/models/fsm_template.py
  fieldservice/tests/test_fsm_order_template_onchange.py
  fieldservice/views/fsm_equipment.xml
  fieldservice/views/fsm_order.xml
  fieldservice/views/fsm_stage.xml
  fieldservice/views/fsm_tag.xml
  fieldservice/views/fsm_template.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1286 [IMP] fieldservice: stage names translatable
  fieldservice/models/fsm_stage.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1282 [15.0][IMP] fieldservice_sale[_*]: Automatically cancel and regenerate FSM and picking orders with sale order changes
  fieldservice_sale/README.rst
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/static/description/index.html
  fieldservice_sale/tests/test_fsm_sale_common.py
  fieldservice_sale/tests/test_fsm_sale_onchange_partner.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale_stock/models/sale_order.py
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/procurement_group.py
  fieldservice_stock/models/stock_picking.py
Labels: enhancement, needs fixing, needs review, approved, ready to merge, bot is merging ⏳

#1149 [16.0] [MIG] fieldservice_sale_recurring
  fieldservice_sale_recurring/README.rst
  fieldservice_sale_recurring/__init__.py
  fieldservice_sale_recurring/__manifest__.py
  fieldservice_sale_recurring/i18n/de.po
  fieldservice_sale_recurring/i18n/es.po
  fieldservice_sale_recurring/i18n/es_AR.po
  fieldservice_sale_recurring/i18n/es_CL.po
  fieldservice_sale_recurring/i18n/fieldservice_sale_recurring.pot
  fieldservice_sale_recurring/i18n/fr.po
  fieldservice_sale_recurring/i18n/it.po
  fieldservice_sale_recurring/i18n/pt_BR.po
  fieldservice_sale_recurring/models/__init__.py
  fieldservice_sale_recurring/models/fsm_recurring.py
  fieldservice_sale_recurring/models/product_template.py
  fieldservice_sale_recurring/models/sale_order.py
  fieldservice_sale_recurring/models/sale_order_line.py
  fieldservice_sale_recurring/readme/CONFIGURE.rst
  fieldservice_sale_recurring/readme/CONTRIBUTORS.rst
  fieldservice_sale_recurring/readme/DESCRIPTION.rst
  fieldservice_sale_recurring/readme/INSTALL.rst
  fieldservice_sale_recurring/readme/ROADMAP.rst
  fieldservice_sale_recurring/readme/USAGE.rst
  fieldservice_sale_recurring/security/ir.model.access.csv
  fieldservice_sale_recurring/static/description/description/icon.png
  fieldservice_sale_recurring/static/description/description/index.html
  fieldservice_sale_recurring/static/description/icon.png
  fieldservice_sale_recurring/static/description/index.html
  fieldservice_sale_recurring/tests/__init__.py
  fieldservice_sale_recurring/tests/test_fsm_sale_recurring.py
  fieldservice_sale_recurring/views/fsm_recurring.xml
  fieldservice_sale_recurring/views/product_template.xml
  fieldservice_sale_recurring/views/sale_order.xml
  setup/fieldservice_sale_recurring/odoo/addons/fieldservice_sale_recurring
  setup/fieldservice_sale_recurring/setup.py
Labels: approved, bot is merging ⏳, no stale

#1293 [16.0] fieldservice_account: Add _get_invoicable_stage method from v14
  fieldservice_account/models/fsm_stage.py
  fieldservice_account/views/account_move.xml
Labels: bot is merging ⏳

#1292 [IMP] fieldservice: Display FSM Location address on FSM order form view
  fieldservice/views/fsm_order.xml
Labels: approved, bot is merging ⏳
