Repository OCA/field-service, pull requests merged in 2025-01, with the labels that each got.

#1288 [16.0][ADD] fieldservice_repair
  fieldservice_repair/README.rst
  fieldservice_repair/__init__.py
  fieldservice_repair/__manifest__.py
  fieldservice_repair/data/fsm_order_type.xml
  fieldservice_repair/i18n/de.po
  fieldservice_repair/i18n/es.po
  fieldservice_repair/i18n/es_AR.po
  fieldservice_repair/i18n/fieldservice_repair.pot
  fieldservice_repair/i18n/it.po
  fieldservice_repair/i18n/pt_BR.po
  fieldservice_repair/models/__init__.py
  fieldservice_repair/models/fsm_order.py
  fieldservice_repair/models/fsm_order_type.py
  fieldservice_repair/readme/CONFIGURE.rst
  fieldservice_repair/readme/CONTRIBUTORS.rst
  fieldservice_repair/readme/CREDITS.rst
  fieldservice_repair/readme/DESCRIPTION.rst
  fieldservice_repair/readme/INSTALL.rst
  fieldservice_repair/readme/ROADMAP.rst
  fieldservice_repair/readme/USAGE.rst
  fieldservice_repair/static/description/icon.png
  fieldservice_repair/static/description/index.html
  fieldservice_repair/tests/__init__.py
  fieldservice_repair/tests/test_fsm_repair.py
  fieldservice_repair/views/fsm_order_view.xml
  setup/fieldservice_repair/odoo/addons/fieldservice_repair
  setup/fieldservice_repair/setup.py
Labels: needs review, migration, bot is merging ⏳

#1289 [15.0][MIG] fieldservice_portal: Migration to 15.0
  fieldservice_portal/README.rst
  fieldservice_portal/__init__.py
  fieldservice_portal/__manifest__.py
  fieldservice_portal/controllers/__init__.py
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/demo/fsm_location_demo.xml
  fieldservice_portal/demo/fsm_order_demo.xml
  fieldservice_portal/i18n/ca.po
  fieldservice_portal/i18n/es.po
  fieldservice_portal/i18n/fieldservice_portal.pot
  fieldservice_portal/readme/CONTRIBUTORS.rst
  fieldservice_portal/readme/DESCRIPTION.rst
  fieldservice_portal/security/ir.model.access.csv
  fieldservice_portal/security/portal_security.xml
  fieldservice_portal/static/description/icon.png
  fieldservice_portal/static/description/index.html
  fieldservice_portal/static/src/js/fsm_order_portal.esm.js
  fieldservice_portal/tests/__init__.py
  fieldservice_portal/tests/test_portal.py
  fieldservice_portal/views/fsm_order_template.xml
  fieldservice_portal/views/portal_template.xml
  setup/fieldservice_portal/odoo/addons/fieldservice_portal
  setup/fieldservice_portal/setup.py
Labels: approved, bot is merging ⏳

#1294 [16.0][FIX] fieldservice_isp_account: project_id in timesheet
  fieldservice_isp_account/models/fsm_order.py
Labels: bug, needs review, bot is merging ⏳

#1296 [15.0][IMP] fieldservice_stock: Compute move_ids from related pickings
  fieldservice_stock/models/fsm_order.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#1291 [17.0][FIX] fieldservice_repair: Allow changing type properly
  fieldservice_repair/models/fsm_order.py
Labels: bug, needs review, approved, bot is merging ⏳

#1275 [17.0] [ADD] fieldservice_sale_agreement
  fieldservice_sale_agreement/README.rst
  fieldservice_sale_agreement/__init__.py
  fieldservice_sale_agreement/__manifest__.py
  fieldservice_sale_agreement/models/__init__.py
  fieldservice_sale_agreement/models/sale_order.py
  fieldservice_sale_agreement/pyproject.toml
  fieldservice_sale_agreement/readme/CONTRIBUTORS.md
  fieldservice_sale_agreement/readme/DESCRIPTION.md
  fieldservice_sale_agreement/static/description/index.html
  fieldservice_sale_agreement/tests/__init__.py
  fieldservice_sale_agreement/tests/test_fsm_sale_agreement.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1277 [17.0] [ADD] fieldservice_sale_agreement_equipment_stock
  fieldservice_sale_agreement_equipment_stock/README.rst
  fieldservice_sale_agreement_equipment_stock/__init__.py
  fieldservice_sale_agreement_equipment_stock/__manifest__.py
  fieldservice_sale_agreement_equipment_stock/models/__init__.py
  fieldservice_sale_agreement_equipment_stock/models/stock_move.py
  fieldservice_sale_agreement_equipment_stock/pyproject.toml
  fieldservice_sale_agreement_equipment_stock/readme/CONTRIBUTORS.md
  fieldservice_sale_agreement_equipment_stock/readme/DESCRIPTION.md
  fieldservice_sale_agreement_equipment_stock/static/description/index.html
  fieldservice_sale_agreement_equipment_stock/tests/__init__.py
  fieldservice_sale_agreement_equipment_stock/tests/test_fsm_sale_agreement_equipment_stock.py
Labels: approved, ready to merge, bot is merging ⏳

#1299 [15.0][FW] fieldservice_recurring: multiple ports from 14.0
  fieldservice_recurring/models/fsm_recurring.py
Labels: approved, bot is merging ⏳

#1307 [15.0][IMP] fieldservice: Add scheduled_date_end to tree view
  fieldservice/views/fsm_order.xml
Labels: approved, bot is merging ⏳
