Repository OCA/field-service, pull requests merged in 2025-05, with the labels that each got.

#1345 [17.0][IMP] fieldservice_crm: Added more filters on fsm_orders
  fieldservice_crm/i18n/es.po
  fieldservice_crm/models/fsm_order.py
  fieldservice_crm/tests/test_fsm_crm.py
  fieldservice_crm/views/fsm_order.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1384 [17.0][IMP] fieldservice: Display stages in calendar using their stage color
  fieldservice/views/fsm_order.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1343 [15.0][ADD] fieldservice_sale_stock_route
  fieldservice_sale_stock_route/README.rst
  fieldservice_sale_stock_route/__init__.py
  fieldservice_sale_stock_route/__manifest__.py
  fieldservice_sale_stock_route/i18n/ca.po
  fieldservice_sale_stock_route/i18n/es.po
  fieldservice_sale_stock_route/i18n/fieldservice_sale_stock_route.pot
  fieldservice_sale_stock_route/models/__init__.py
  fieldservice_sale_stock_route/models/fsm_order.py
  fieldservice_sale_stock_route/models/fsm_route.py
  fieldservice_sale_stock_route/models/fsm_route_dayroute.py
  fieldservice_sale_stock_route/models/sale_order.py
  fieldservice_sale_stock_route/readme/CONTRIBUTORS.rst
  fieldservice_sale_stock_route/readme/DESCRIPTION.rst
  fieldservice_sale_stock_route/readme/USAGE.rst
  fieldservice_sale_stock_route/static/description/icon.png
  fieldservice_sale_stock_route/static/description/index.html
  fieldservice_sale_stock_route/tests/__init__.py
  fieldservice_sale_stock_route/tests/test_fieldservice_sale_stock_route.py
  fieldservice_sale_stock_route/views/fsm_order.xml
  fieldservice_sale_stock_route/views/fsm_route.xml
  fieldservice_sale_stock_route/views/sale_order.xml
  setup/fieldservice_sale_stock_route/odoo/addons/fieldservice_sale_stock_route
  setup/fieldservice_sale_stock_route/setup.py
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1374 [17.0][IMP] fieldservice_stock: Autocomplete order warehouse with default worker warehouse
  fieldservice_stock/README.rst
  fieldservice_stock/__manifest__.py
  fieldservice_stock/models/__init__.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/fsm_person.py
  fieldservice_stock/views/fsm_person.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1387 [17.0][IMP] fieldservice: Link teams with workers
  fieldservice/README.rst
  fieldservice/i18n/es.po
  fieldservice/models/fsm_order.py
  fieldservice/models/fsm_person.py
  fieldservice/readme/CONTRIBUTORS.md
  fieldservice/static/description/index.html
  fieldservice/views/fsm_person.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1388 [FIX] fieldservice_vehicle: Fix onchange person_id
  fieldservice_vehicle/models/fsm_order.py
Labels: bug, needs review, approved, bot is merging ⏳

#1389 [15.0][FIX] fieldservice_sale: avoid singleton error in _field_service_generation
  fieldservice_sale/models/sale_order.py
Labels: bug, needs review, approved, bot is merging ⏳

#1390 [15.0][FIX] fieldservice_sale_stock_route: avoid singleton error in write
  fieldservice_sale_stock_route/models/sale_order.py
Labels: approved, bot is merging ⏳

#1391 [15.0][FIX] fieldservice_sale_stock_route: Fix FSM delivery postponement to skip current route day
  fieldservice_sale_stock_route/models/fsm_order.py
  fieldservice_sale_stock_route/tests/test_fieldservice_sale_stock_route.py
Labels: approved, bot is merging ⏳

#1392 [15.0][FIX] fieldservice_sale_stock_route: Use @freeze_time for time-sensitive tests
  fieldservice_sale_stock_route/tests/test_fieldservice_sale_stock_route.py
Labels: approved, bot is merging ⏳

#1363 [15.0][IMP] fieldservice_route: Add many2many_tags widget to day_ids
  fieldservice_route/views/fsm_route.xml
Labels: enhancement, approved, ready to merge, merged 🎉

#1364 [15.0][FIX] fieldservice_route: Ensure FSMRouteDay selection values are properly translated
  fieldservice_route/i18n/es.po
  fieldservice_route/models/fsm_route_day.py
  fieldservice_route/models/fsm_route_dayroute.py
Labels: enhancement, approved, merged 🎉

#1237 [18.0][MIG] fieldservice_equipment_stock
  fieldservice_equipment_stock/README.rst
  fieldservice_equipment_stock/__init__.py
  fieldservice_equipment_stock/__manifest__.py
  fieldservice_equipment_stock/i18n/es.po
  fieldservice_equipment_stock/i18n/es_AR.po
  fieldservice_equipment_stock/i18n/fieldservice_equipment_stock.pot
  fieldservice_equipment_stock/i18n/it.po
  fieldservice_equipment_stock/i18n/pt_BR.po
  fieldservice_equipment_stock/models/__init__.py
  fieldservice_equipment_stock/models/fsm_equipment.py
  fieldservice_equipment_stock/models/product_template.py
  fieldservice_equipment_stock/models/stock_lot.py
  fieldservice_equipment_stock/models/stock_move.py
  fieldservice_equipment_stock/models/stock_picking_type.py
  fieldservice_equipment_stock/pyproject.toml
  fieldservice_equipment_stock/readme/CONFIGURE.md
  fieldservice_equipment_stock/readme/CONTRIBUTORS.md
  fieldservice_equipment_stock/readme/CREDITS.md
  fieldservice_equipment_stock/readme/DESCRIPTION.md
  fieldservice_equipment_stock/readme/ROADMAP.md
  fieldservice_equipment_stock/readme/USAGE.md
  fieldservice_equipment_stock/security/ir.model.access.csv
  fieldservice_equipment_stock/static/description/icon.png
  fieldservice_equipment_stock/static/description/index.html
  fieldservice_equipment_stock/tests/__init__.py
  fieldservice_equipment_stock/tests/test_fsm_equipment.py
  fieldservice_equipment_stock/tests/test_stock_move.py
  fieldservice_equipment_stock/views/fsm_equipment.xml
  fieldservice_equipment_stock/views/product_template.xml
  fieldservice_equipment_stock/views/stock_lot.xml
  fieldservice_equipment_stock/views/stock_picking_type.xml
Labels: needs review, migration, bot is merging ⏳, stale

#1245 [18.0][MIG] fieldservice_sale_stock
  fieldservice_sale_stock/README.rst
  fieldservice_sale_stock/__init__.py
  fieldservice_sale_stock/__manifest__.py
  fieldservice_sale_stock/i18n/es.po
  fieldservice_sale_stock/i18n/es_AR.po
  fieldservice_sale_stock/i18n/es_CL.po
  fieldservice_sale_stock/i18n/fieldservice_sale_stock.pot
  fieldservice_sale_stock/i18n/it.po
  fieldservice_sale_stock/i18n/pt_BR.po
  fieldservice_sale_stock/models/__init__.py
  fieldservice_sale_stock/models/sale_order.py
  fieldservice_sale_stock/pyproject.toml
  fieldservice_sale_stock/readme/CONFIGURE.md
  fieldservice_sale_stock/readme/CONTRIBUTORS.md
  fieldservice_sale_stock/readme/DESCRIPTION.md
  fieldservice_sale_stock/readme/ROADMAP.md
  fieldservice_sale_stock/readme/USAGE.md
  fieldservice_sale_stock/static/description/icon.png
  fieldservice_sale_stock/static/description/icon.svg
  fieldservice_sale_stock/static/description/index.html
  fieldservice_sale_stock/tests/__init__.py
  fieldservice_sale_stock/tests/test_fsm_sale_order.py
Labels: needs review, migration, bot is merging ⏳, stale

#1372 [17.0][FIX] fieldservice_stock_request: process all records in _action_confirm
  fieldservice_stock_request/models/stock_request.py
Labels: approved, ready to merge, bot is merging ⏳

#1385 [17.0][FIX] fieldservice_vehicle: Fixed permissions for user own documents
  fieldservice_vehicle/security/ir.model.access.csv
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#1358 [15.0][FIX] fieldservice_route: Allow FSM own users to see all routes and assigned orders
  fieldservice_route/security/ir_rule.xml
Labels: approved, ready to merge, bot is merging ⏳

#1356 [17.0][IMP] fieldservice_recurring: Add access rules and permissions for fsm_frequency, fms_frequency_set, fsm_recurring_template and fsm_recurring
  fieldservice_recurring/security/ir.model.access.csv
  fieldservice_recurring/security/recurring_security.xml
  fieldservice_recurring/security/res_groups.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1379 [17.0] [MIG] fieldservice_skill: migration to 17.0
  fieldservice_skill/README.rst
  fieldservice_skill/__init__.py
  fieldservice_skill/__manifest__.py
  fieldservice_skill/i18n/de.po
  fieldservice_skill/i18n/es.po
  fieldservice_skill/i18n/es_AR.po
  fieldservice_skill/i18n/es_CL.po
  fieldservice_skill/i18n/fieldservice_skill.pot
  fieldservice_skill/i18n/it.po
  fieldservice_skill/i18n/pt_BR.po
  fieldservice_skill/models/__init__.py
  fieldservice_skill/models/fsm_category.py
  fieldservice_skill/models/fsm_order.py
  fieldservice_skill/models/fsm_person.py
  fieldservice_skill/models/fsm_person_skill.py
  fieldservice_skill/models/fsm_template.py
  fieldservice_skill/models/hr_skill.py
  fieldservice_skill/pyproject.toml
  fieldservice_skill/readme/CONFIGURE.md
  fieldservice_skill/readme/CONTRIBUTORS.md
  fieldservice_skill/readme/CREDITS.md
  fieldservice_skill/readme/DESCRIPTION.md
  fieldservice_skill/readme/ROADMAP.md
  fieldservice_skill/readme/USAGE.md
  fieldservice_skill/security/ir.model.access.csv
  fieldservice_skill/static/description/icon.png
  fieldservice_skill/static/description/index.html
  fieldservice_skill/tests/__init__.py
  fieldservice_skill/tests/test_fsm_skill.py
  fieldservice_skill/views/fsm_category.xml
  fieldservice_skill/views/fsm_order.xml
  fieldservice_skill/views/fsm_person.xml
  fieldservice_skill/views/fsm_person_skill.xml
  fieldservice_skill/views/fsm_template.xml
  fieldservice_skill/views/hr_skill.xml
Labels: approved, ready to merge, bot is merging ⏳

#1395 [17.0][IMP] fieldservice: Added description to calendar view
  fieldservice/views/fsm_order.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1404 [15.0][FIX] fieldservice_sale_stock_route: Start route day calculation from tomorrow
  fieldservice_sale_stock_route/models/sale_order.py
  fieldservice_sale_stock_route/tests/test_fieldservice_sale_stock_route.py
Labels: bot is merging ⏳

#1399 [17.0][IMP] fieldservice: Added wizard to create sub-locations
  fieldservice/README.rst
  fieldservice/__manifest__.py
  fieldservice/security/ir.model.access.csv
  fieldservice/tests/__init__.py
  fieldservice/tests/test_fsm_wizard_create_sub_location.py
  fieldservice/wizard/__init__.py
  fieldservice/wizard/fsm_create_sublocation_wizard.py
  fieldservice/wizard/fsm_create_sublocation_wizard.xml
Labels: enhancement, needs review, approved, bot is merging ⏳
