Repository OCA/field-service, pull requests merged in 2025-04, with the labels that each got.

#1329 [16.0][FIX] fieldservice: request_early default to current time
  fieldservice/models/fsm_order.py
Labels: approved, ready to merge, merged 🎉

#1328 [15.0][FIX] fieldservice: request_early default to current time
  fieldservice/models/fsm_order.py
Labels: approved, ready to merge, merged 🎉

#1335 [17.0][FIX] fieldservice_geoengine: Remove widget for shape field
  fieldservice_geoengine/views/fsm_location.xml
Labels: approved, ready to merge, merged 🎉

#1336 [17.0][IMP] fieldservice_sale[_*]: Automatically cancel and regenerate FSM and picking orders with sale order changes
  fieldservice_sale/models/sale_order.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale/tests/test_fsm_sale_order.py
  fieldservice_sale_stock/models/sale_order.py
  fieldservice_stock/models/fsm_order.py
  fieldservice_stock/models/stock_picking.py
Labels: approved, ready to merge, merged 🎉

#1370 [16.0][FIX]field_service_recurring: fixed tree view formatting
  fieldservice_recurring/views/fsm_frequency_set.xml
Labels: approved, bot is merging ⏳

#1375 [17.0][MIG] fieldservice_availability: Migration to 17.0
  fieldservice_availability/README.rst
  fieldservice_availability/__init__.py
  fieldservice_availability/__manifest__.py
  fieldservice_availability/i18n/ca.po
  fieldservice_availability/i18n/es.po
  fieldservice_availability/i18n/fieldservice_availability.pot
  fieldservice_availability/models/__init__.py
  fieldservice_availability/models/fsm_blackout_day.py
  fieldservice_availability/models/fsm_delivery_time_range.py
  fieldservice_availability/models/fsm_stress_day.py
  fieldservice_availability/pyproject.toml
  fieldservice_availability/readme/CONTRIBUTORS.md
  fieldservice_availability/readme/DESCRIPTION.md
  fieldservice_availability/readme/USAGE.md
  fieldservice_availability/security/ir.model.access.csv
  fieldservice_availability/static/description/icon.png
  fieldservice_availability/static/description/index.html
  fieldservice_availability/tests/__init__.py
  fieldservice_availability/tests/test_fsm_delivery_time_range.py
  fieldservice_availability/views/fsm_blackout_day_templates.xml
  fieldservice_availability/views/fsm_delivery_time_range_templates.xml
  fieldservice_availability/views/fsm_stress_day_templates.xml
  fieldservice_availability/views/menu.xml
Labels: approved, bot is merging ⏳

#1376 [17.0][IMP] fieldservice_availability: Group black out days
  fieldservice_availability/README.rst
  fieldservice_availability/i18n/ca.po
  fieldservice_availability/i18n/es.po
  fieldservice_availability/models/__init__.py
  fieldservice_availability/models/fsm_blackout_group.py
  fieldservice_availability/readme/DESCRIPTION.md
  fieldservice_availability/readme/USAGE.md
  fieldservice_availability/security/ir.model.access.csv
  fieldservice_availability/static/description/index.html
  fieldservice_availability/views/fsm_blackout_day_templates.xml
  fieldservice_availability/views/menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#1337 [15.0][IMP] fieldservice_sale: Show FSM Orders button for own documents users
  fieldservice_sale/views/sale_order.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#1381 [17.0][ADD] fieldservice_route_availability: New module fieldservice_route_availability
  fieldservice/i18n/es.po
  fieldservice/models/res_config_settings.py
  fieldservice/views/res_config_settings.xml
  fieldservice_route_availability/README.rst
  fieldservice_route_availability/__init__.py
  fieldservice_route_availability/__manifest__.py
  fieldservice_route_availability/i18n/ca.po
  fieldservice_route_availability/i18n/es.po
  fieldservice_route_availability/models/__init__.py
  fieldservice_route_availability/models/fsm_order.py
  fieldservice_route_availability/models/fsm_route.py
  fieldservice_route_availability/pyproject.toml
  fieldservice_route_availability/readme/CONTRIBUTORS.md
  fieldservice_route_availability/readme/DESCRIPTION.md
  fieldservice_route_availability/readme/USAGE.md
  fieldservice_route_availability/static/description/icon.png
  fieldservice_route_availability/static/description/index.html
  fieldservice_route_availability/tests/__init__.py
  fieldservice_route_availability/tests/test_route_availability.py
  fieldservice_route_availability/views/fsm_route.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1347 [17.0][IMP] fieldservice: Added filter Due This Week
  fieldservice/i18n/es.po
  fieldservice/views/fsm_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1352 [17.0][IMP] fieldservice_stock_request: Set default expected_date from scheduled_date_start
  fieldservice_stock_request/models/stock_request.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#1351 [17.0][[FW] fieldservice_route: Add access rules and permissions for fsm_route, fsm_route_day and fsm_route_dayroute models from 15.0 to 17.0
  fieldservice_route/README.rst
  fieldservice_route/__manifest__.py
  fieldservice_route/readme/CONTRIBUTORS.md
  fieldservice_route/security/ir.model.access.csv
  fieldservice_route/security/ir_rule.xml
  fieldservice_route/static/description/index.html
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
