Repository OCA/field-service, pull requests merged in 2025-08, with the labels that each got.

#1426 [18.0][MIG] fieldservice_availability: Migration to 18.0
  fieldservice_availability/README.rst
  fieldservice_availability/__init__.py
  fieldservice_availability/__manifest__.py
  fieldservice_availability/i18n/ca.po
  fieldservice_availability/i18n/es.po
  fieldservice_availability/i18n/fieldservice_availability.pot
  fieldservice_availability/i18n/it.po
  fieldservice_availability/models/__init__.py
  fieldservice_availability/models/fsm_blackout_day.py
  fieldservice_availability/models/fsm_blackout_group.py
  fieldservice_availability/models/fsm_delivery_time_range.py
  fieldservice_availability/models/fsm_stress_day.py
  fieldservice_availability/pyproject.toml
  fieldservice_availability/readme/CONTRIBUTORS.md
  fieldservice_availability/readme/DESCRIPTION.md
  fieldservice_availability/readme/USAGE.md
  fieldservice_availability/security/ir.model.access.csv
  fieldservice_availability/static/description/icon.png
  fieldservice_availability/static/description/index.html
  fieldservice_availability/tests/__init__.py
  fieldservice_availability/tests/test_fsm_delivery_time_range.py
  fieldservice_availability/views/fsm_blackout_day_templates.xml
  fieldservice_availability/views/fsm_delivery_time_range_templates.xml
  fieldservice_availability/views/fsm_stress_day_templates.xml
  fieldservice_availability/views/menu.xml
Labels: approved, bot is merging ⏳

#1428 [16.0][IMP] fieldservice: Allow to archive FSM Teams
  fieldservice/models/fsm_team.py
  fieldservice/views/fsm_team.xml
Labels: approved, ready to merge, bot is merging ⏳

#1436 [FIX] fieldservice_kanban_info: Use freezetime in tests
  fieldservice_kanban_info/tests/test_fieldservice_kanban_info.py
Labels: bot is merging ⏳

#1429 [18.0][MIG] fieldservice_portal: Migration to 18.0
  fieldservice_portal/README.rst
  fieldservice_portal/__init__.py
  fieldservice_portal/__manifest__.py
  fieldservice_portal/controllers/__init__.py
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/demo/fsm_location_demo.xml
  fieldservice_portal/demo/fsm_order_demo.xml
  fieldservice_portal/i18n/ca.po
  fieldservice_portal/i18n/es.po
  fieldservice_portal/i18n/fieldservice_portal.pot
  fieldservice_portal/i18n/it.po
  fieldservice_portal/i18n/pt_BR.po
  fieldservice_portal/models/__init__.py
  fieldservice_portal/models/fsm_stage.py
  fieldservice_portal/pyproject.toml
  fieldservice_portal/readme/CONFIGURE.md
  fieldservice_portal/readme/CONTRIBUTORS.md
  fieldservice_portal/readme/DESCRIPTION.md
  fieldservice_portal/security/ir.model.access.csv
  fieldservice_portal/security/portal_security.xml
  fieldservice_portal/static/description/icon.png
  fieldservice_portal/static/description/index.html
  fieldservice_portal/static/src/img/fsmorder.svg
  fieldservice_portal/static/src/js/fsm_order_portal.esm.js
  fieldservice_portal/tests/__init__.py
  fieldservice_portal/tests/test_portal.py
  fieldservice_portal/views/fsm_order_template.xml
  fieldservice_portal/views/fsm_stage.xml
  fieldservice_portal/views/portal_template.xml
Labels: approved, bot is merging ⏳

#1359 [15.0][ADD] fieldservice_kanban_info_route: New module fieldservice_kanban_info_route
  fieldservice_kanban_info_route/README.rst
  fieldservice_kanban_info_route/__init__.py
  fieldservice_kanban_info_route/__manifest__.py
  fieldservice_kanban_info_route/i18n/ca.po
  fieldservice_kanban_info_route/i18n/es.po
  fieldservice_kanban_info_route/i18n/fieldservice_kanban_info_route.pot
  fieldservice_kanban_info_route/readme/CONTRIBUTORS.rst
  fieldservice_kanban_info_route/readme/DESCRIPTION.rst
  fieldservice_kanban_info_route/readme/USAGE.rst
  fieldservice_kanban_info_route/static/description/icon.png
  fieldservice_kanban_info_route/static/description/index.html
  fieldservice_kanban_info_route/views/fsm_order.xml
  setup/fieldservice_kanban_info_route/odoo/addons/fieldservice_kanban_info_route
  setup/fieldservice_kanban_info_route/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1416 [15.0][ADD] fieldservice_sale_note: New module fieldservice_sale_note
  fieldservice_sale_note/README.rst
  fieldservice_sale_note/__init__.py
  fieldservice_sale_note/__manifest__.py
  fieldservice_sale_note/i18n/es.po
  fieldservice_sale_note/models/__init__.py
  fieldservice_sale_note/models/sale_order.py
  fieldservice_sale_note/readme/CONTRIBUTORS.md
  fieldservice_sale_note/readme/DESCRIPTION.md
  fieldservice_sale_note/readme/ROADMAP.md
  fieldservice_sale_note/readme/USAGE.md
  fieldservice_sale_note/static/description/icon.png
  fieldservice_sale_note/static/description/icon.svg
  fieldservice_sale_note/static/description/index.html
  fieldservice_sale_note/tests/__init__.py
  fieldservice_sale_note/tests/test_fms_sale_order_note.py
  fieldservice_sale_note/views/sale_order_views.xml
  setup/fieldservice_sale_note/odoo/addons/fieldservice_sale_note
  setup/fieldservice_sale_note/setup.py
Labels: approved, ready to merge

#1309 [15.0][ADD] fieldservice_delivery_quantities: New module fieldservice_delivery_quantities
  fieldservice_delivery_quantities/README.rst
  fieldservice_delivery_quantities/__init__.py
  fieldservice_delivery_quantities/__manifest__.py
  fieldservice_delivery_quantities/i18n/ca.po
  fieldservice_delivery_quantities/i18n/es.po
  fieldservice_delivery_quantities/i18n/fieldservice_delivery_quantities.pot
  fieldservice_delivery_quantities/models/__init__.py
  fieldservice_delivery_quantities/models/stock_move.py
  fieldservice_delivery_quantities/readme/CONTRIBUTORS.rst
  fieldservice_delivery_quantities/readme/DESCRIPTION.rst
  fieldservice_delivery_quantities/readme/USAGE.rst
  fieldservice_delivery_quantities/security/ir_rule.xml
  fieldservice_delivery_quantities/static/description/icon.png
  fieldservice_delivery_quantities/static/description/index.html
  fieldservice_delivery_quantities/views/menu.xml
  fieldservice_delivery_quantities/views/stock_move_views.xml
  setup/fieldservice_delivery_quantities/odoo/addons/fieldservice_delivery_quantities
  setup/fieldservice_delivery_quantities/setup.py
Labels: approved, ready to merge, bot is merging ⏳
