Repository OCA/field-service, pull requests merged in 2025-03, with the labels that each got.

#1315 [18.0] [FW] [IMP] fieldservice_sale: Only invoice invoiceable fsm order
  .oca/oca-port/blacklist/fieldservice_account.json
  .oca/oca-port/blacklist/fieldservice_sale.json
  fieldservice_account/models/fsm_stage.py
  fieldservice_sale/models/sale_order_line.py
  fieldservice_sale_recurring/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1326 [17.0][FIX] fieldservice[*]: Fix error when viewing team orders
  fieldservice/README.rst
  fieldservice/readme/CONTRIBUTORS.md
  fieldservice/static/description/index.html
  fieldservice/views/fsm_team.xml
  fieldservice_geoengine/views/fsm_team.xml
Labels: approved, ready to merge

#1324 [16.0][FIX] fieldservice_geoengine: Remove widget for shape field
  fieldservice_geoengine/views/fsm_location.xml
Labels: approved, ready to merge, bot is merging ⏳

#1332 [16.0][FIX] fieldservice_account + fieldservice_sale: Post-install test + fallback to load CoA
  fieldservice_account/tests/test_fsm_account.py
  fieldservice_account_analytic/models/fsm_location.py
  fieldservice_sale/tests/test_fsm_sale_order.py
Labels: bot is merging ⏳

#1331 [15.0][ADD] fieldservice_kanban_info: New module fieldservice_kanban_info
  fieldservice_kanban_info/README.rst
  fieldservice_kanban_info/__init__.py
  fieldservice_kanban_info/__manifest__.py
  fieldservice_kanban_info/i18n/ca.po
  fieldservice_kanban_info/i18n/es.po
  fieldservice_kanban_info/i18n/fieldservice_kanban_info.pot
  fieldservice_kanban_info/models/__init__.py
  fieldservice_kanban_info/models/fsm_order.py
  fieldservice_kanban_info/models/res_config_settings.py
  fieldservice_kanban_info/readme/CONTRIBUTORS.rst
  fieldservice_kanban_info/readme/DESCRIPTION.rst
  fieldservice_kanban_info/readme/USAGE.rst
  fieldservice_kanban_info/static/description/icon.png
  fieldservice_kanban_info/static/description/index.html
  fieldservice_kanban_info/tests/__init__.py
  fieldservice_kanban_info/tests/test_fieldservice_kanban_info.py
  fieldservice_kanban_info/views/fsm_order.xml
  fieldservice_kanban_info/views/res_config_settings_views.xml
  setup/fieldservice_kanban_info/odoo/addons/fieldservice_kanban_info
  setup/fieldservice_kanban_info/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1341 [17.0][MIG] fieldservice_kanban_info: Migration to 17.0
  fieldservice_kanban_info/README.rst
  fieldservice_kanban_info/__init__.py
  fieldservice_kanban_info/__manifest__.py
  fieldservice_kanban_info/i18n/ca.po
  fieldservice_kanban_info/i18n/es.po
  fieldservice_kanban_info/i18n/fieldservice_kanban_info.pot
  fieldservice_kanban_info/models/__init__.py
  fieldservice_kanban_info/models/fsm_order.py
  fieldservice_kanban_info/models/res_config_settings.py
  fieldservice_kanban_info/pyproject.toml
  fieldservice_kanban_info/readme/CONTRIBUTORS.md
  fieldservice_kanban_info/readme/DESCRIPTION.md
  fieldservice_kanban_info/readme/USAGE.md
  fieldservice_kanban_info/static/description/icon.png
  fieldservice_kanban_info/static/description/index.html
  fieldservice_kanban_info/tests/__init__.py
  fieldservice_kanban_info/tests/test_fieldservice_kanban_info.py
  fieldservice_kanban_info/views/fsm_order.xml
  fieldservice_kanban_info/views/res_config_settings_views.xml
Labels: approved, bot is merging ⏳

#1325 [17.0][FIX] fieldservice-geoengine: Fix geoengine view filter
  fieldservice_geoengine/readme/CONTRIBUTORS.md
  fieldservice_geoengine/views/fsm_order.xml
Labels: approved, ready to merge, bot is merging ⏳

#1338 [FIX] fieldservice_route: clickable option for dayroute view
  fieldservice_route/views/fsm_route_dayroute.xml
Labels: bug, bot is merging ⏳

#1346 [16.0][IMP] fieldservice: Define @freeze_time decorator in tests and not in TestFSMOrderBase to avoid side effects
  fieldservice/tests/test_fsm_order.py
Labels: approved, bot is merging ⏳

#1349 [15.0][FIX] fieldservice_delivery: Fix tests
  fieldservice_delivery/tests/test_fsm_delivery.py
Labels: bot is merging ⏳

#1348 [15.0][FIX] fieldservice_sale_recurring: Fix tests
  fieldservice_sale_recurring/tests/test_fsm_sale_recurring.py
Labels: bot is merging ⏳

#1353 [15.0][IMP] fieldservice_activity: Use @freeze_time for time-sensitive tests
  fieldservice_activity/tests/test_fsm_activity.py
Labels: approved, bot is merging ⏳
