Repository OCA/field-service, pull requests merged in 2025-02, with the labels that each got.

#1310 [14.0][IMP] fieldservice_sale: Only invoice invoiceable fsm order
  fieldservice_geoengine/tests/test_fsm_location.py
  fieldservice_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1271 [17.0] [ADD] fieldservice_repair_order_template
  fieldservice_repair_order_template/README.rst
  fieldservice_repair_order_template/__init__.py
  fieldservice_repair_order_template/__manifest__.py
  fieldservice_repair_order_template/models/__init__.py
  fieldservice_repair_order_template/models/fsm_order.py
  fieldservice_repair_order_template/models/fsm_template.py
  fieldservice_repair_order_template/pyproject.toml
  fieldservice_repair_order_template/readme/CONFIGURE.md
  fieldservice_repair_order_template/readme/CONTRIBUTORS.md
  fieldservice_repair_order_template/readme/DESCRIPTION.md
  fieldservice_repair_order_template/static/description/index.html
  fieldservice_repair_order_template/tests/__init__.py
  fieldservice_repair_order_template/tests/test_repair_order_template.py
  fieldservice_repair_order_template/views/fsm_template.xml
Labels: approved, bot is merging ⏳

#1303 [16.0][FW] [17.0][FIX] fieldservice_recurring: Fix form view
  fieldservice_recurring/views/fsm_recurring.xml
Labels: bot is merging ⏳

#1306 [17.0][FW] [FIX] fieldservice_portal: Prevent order variable conflict with Purchase module
  .oca/oca-port/blacklist/fieldservice_portal.json
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/views/fsm_order_template.xml
Labels: bot is merging ⏳

#1305 [16.0][FW] [FIX] fieldservice_portal: Prevent order variable conflict with Purchase module
  .oca/oca-port/blacklist/fieldservice_portal.json
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/views/fsm_order_template.xml
Labels: bot is merging ⏳

#1311 [15.0] [FW] [IMP] fieldservice_sale: Only invoice invoiceable fsm order
  .oca/oca-port/blacklist/fieldservice_account.json
  .oca/oca-port/blacklist/fieldservice_sale.json
  fieldservice_account/models/fsm_stage.py
  fieldservice_account/views/account_move.xml
  fieldservice_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1313 [16.0] [FW] [IMP] fieldservice_sale: Only invoice invoiceable fsm order
  .oca/oca-port/blacklist/fieldservice_account.json
  .oca/oca-port/blacklist/fieldservice_sale.json
  fieldservice_account/models/fsm_stage.py
  fieldservice_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#1319 [IMP] fieldservice_portal: order visibility by stage
  fieldservice_portal/README.rst
  fieldservice_portal/__init__.py
  fieldservice_portal/__manifest__.py
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/models/__init__.py
  fieldservice_portal/models/fsm_stage.py
  fieldservice_portal/readme/CONFIGURE.rst
  fieldservice_portal/static/description/index.html
  fieldservice_portal/views/fsm_stage.xml
Labels: approved, bot is merging ⏳

#1320 [16.0] [IMP] fieldservice_portal: order visibility by stage
  fieldservice_portal/README.rst
  fieldservice_portal/__init__.py
  fieldservice_portal/__manifest__.py
  fieldservice_portal/controllers/fsm_order_portal.py
  fieldservice_portal/models/__init__.py
  fieldservice_portal/models/fsm_stage.py
  fieldservice_portal/readme/CONFIGURE.rst
  fieldservice_portal/static/description/index.html
  fieldservice_portal/views/fsm_stage.xml
Labels: bot is merging ⏳

#1317 [16.0][FIX] fieldservice: unaccent parent path
  fieldservice/models/fsm_category.py
Labels: bot is merging ⏳

#1322 [IMP] fieldservice_account_analytic: Invoice customer not related to any location
  fieldservice_account_analytic/README.rst
  fieldservice_account_analytic/models/fsm_order.py
  fieldservice_account_analytic/readme/CONTRIBUTORS.rst
  fieldservice_account_analytic/static/description/index.html
  fieldservice_account_analytic/tests/test_fsm_account_wizard.py
Labels: enhancement, needs review, approved, bot is merging ⏳
