Repository OCA/field-service, pull requests merged in 2025-07, with the labels that each got.

#1410 [17.0][IMP] fieldservice_stock_scrap: Use intermediate location when scrap stock
  fieldservice_stock_scrap/README.rst
  fieldservice_stock_scrap/__manifest__.py
  fieldservice_stock_scrap/data/stock_location.xml
  fieldservice_stock_scrap/readme/CONTRIBUTORS.md
  fieldservice_stock_scrap/static/description/index.html
  fieldservice_stock_scrap/wizards/scrap_stock_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#1424 [IMP] fieldservice_activity: Use @freeze_time for time-sensitive tests
  fieldservice_activity/tests/test_fsm_activity.py
Labels: bot is merging ⏳

#1342 [16.0][FIX] fieldservice_geoengine: Restore geoengine views
  fieldservice_geoengine/views/fsm_location.xml
  fieldservice_geoengine/views/fsm_order.xml
Labels: bot is merging ⏳, stale
